/**
 * Phase 51.4 — bundled asset loader for the slide-deck templates.
 *
 * Source of truth = `assets.generated.ts` (committed, regenerated by
 * `pnpm -F @ofoq/api build:assets`). This module reads zero binary
 * files at runtime — every PNG and TTF lives in the compiled JS
 * module graph as a base64 string const. That makes the loader
 * proof against every "the .png never made it into dist/" / "Docker
 * COPY missed the binaries" / "tsx hot-reload didn't pick it up"
 * class of bug.
 *
 * The guards below fail loudly at module init if a const is empty
 * (which would mean the generator was never run). Rendering would
 * otherwise silently produce a blank PDF — the exact prod regression
 * this hotfix repairs.
 */
import {
  BG_GREEN_B64,
  BG_NAVY_B64,
  FONT_PLAYFAIR_B64,
  FONT_LORA_REGULAR_B64,
  FONT_LORA_SEMIBOLD_B64,
} from './assets.generated.js';

function ensureLoaded(name: string, b64: string): string {
  if (!b64 || b64.length === 0) {
    throw new Error(
      `Export asset ${name} missing — run \`pnpm -F @ofoq/api build:assets\` to regenerate.`,
    );
  }
  return b64;
}

const _bgGreen = ensureLoaded('BG_GREEN_B64', BG_GREEN_B64);
const _bgNavy = ensureLoaded('BG_NAVY_B64', BG_NAVY_B64);
const _fontPlayfair = ensureLoaded('FONT_PLAYFAIR_B64', FONT_PLAYFAIR_B64);
const _fontLoraReg = ensureLoaded('FONT_LORA_REGULAR_B64', FONT_LORA_REGULAR_B64);
const _fontLoraSemi = ensureLoaded('FONT_LORA_SEMIBOLD_B64', FONT_LORA_SEMIBOLD_B64);

export const ASSETS = {
  bgGreen: `data:image/png;base64,${_bgGreen}`,
  bgNavy: `data:image/png;base64,${_bgNavy}`,
  fonts: {
    playfairBold: `data:font/ttf;base64,${_fontPlayfair}`,
    loraRegular: `data:font/ttf;base64,${_fontLoraReg}`,
    loraSemiBold: `data:font/ttf;base64,${_fontLoraSemi}`,
  },
} as const;

/**
 * The `@font-face` block — emitted at the top of every slide-deck
 * template's <style>. Kept here so proposal + (later) SOW + future
 * slide templates share the same registration without duplicating
 * the base64 payload across template files.
 */
export function fontFaceCss(): string {
  return `
@font-face {
  font-family: 'Playfair Display';
  font-style: normal;
  font-weight: 700;
  font-display: block;
  src: url(${ASSETS.fonts.playfairBold}) format('truetype');
}
@font-face {
  font-family: 'Lora';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url(${ASSETS.fonts.loraRegular}) format('truetype');
}
@font-face {
  font-family: 'Lora';
  font-style: normal;
  font-weight: 600;
  font-display: block;
  src: url(${ASSETS.fonts.loraSemiBold}) format('truetype');
}
`;
}
