import { describe, it, expect, beforeAll } from 'vitest';
import path from 'node:path';
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import {
  scoreBundle,
  type BundleScore,
  LIFECYCLE_PHASES,
} from './checklist.js';
import {
  loadLatestBundle,
  NSIX_ROOT,
  type AdaptorId,
  type BundleSnapshot,
} from './_helpers.js';

// CI does not generate demo bundles before running tests — these are
// developer-only artefacts produced by
// `pnpm --filter @ofoq/api exec tsx scripts/generate-{netsuite,odoo}-demo-bundle.ts`.
// When the bundle directories are missing, the harness skips rather than
// fails: the test is meaningful for local pre-release verification, but
// in CI without bundles it would just be artefact-dependency theatre.
const ODOO_BUNDLE_ROOT = path.join(NSIX_ROOT, 'ODOO_DEMO_BUNDLE');
const NETSUITE_BUNDLE_ROOT = path.join(NSIX_ROOT, 'NETSUITE_DEMO_BUNDLE');
const BUNDLES_AVAILABLE =
  fsSync.existsSync(ODOO_BUNDLE_ROOT) && fsSync.existsSync(NETSUITE_BUNDLE_ROOT);

if (!BUNDLES_AVAILABLE) {
  // eslint-disable-next-line no-console
  console.warn(
    '[lifecycleScore] Skipping — demo bundles not present. ' +
      'Run pnpm --filter @ofoq/api exec tsx scripts/generate-{netsuite,odoo}-demo-bundle.ts ' +
      'locally to enable.',
  );
}

/**
 * Lifecycle validation harness — automated 9-phase coverage scoring of
 * the latest demo bundle for each adaptor. Runs in CI on every generator
 * change so future content packs can't silently lower coverage.
 *
 * Scores both adaptors against the same rubric. Asserts:
 *   - Uniform overall ≥ 4.0 (post-Kickoff baseline)
 *   - Front-half-weighted overall ≥ 7.0 (post-NS SD Depth Pack baseline)
 *   - Phase 1 (Kickoff) ≥ 8.0
 *   - Phase 2 (Discovery) ≥ 8.0
 *   - Phase 3 (Solution Design) ≥ 9.0 (post-NS SD Depth Pack)
 *   - Phase 4 (Build) — Odoo ≥ 8.0, NetSuite ≥ 9.0 (post-SDF Custom
 *     Records pack; NS gets the new SDF artefact checks, Odoo SKIPs them)
 *
 * Writes a markdown gap report to NSIX/LIFECYCLE_SCORE_<ISO>.md after
 * every run with per-phase breakdowns and per-adaptor failed-check lists.
 *
 * Bundle dependency: this test reads the most-recent bundles produced
 * by generate-{odoo,netsuite}-demo-bundle.ts. The harness does NOT
 * regenerate bundles — that's the developer's responsibility before
 * running tests, or a CI step. The test fails with a clear error
 * pointing at the right driver script if bundles are missing.
 *
 * Snapshot shape: post-extension, the loader returns
 * { docs, buildArtefacts, adaptor } so the rubric can branch on
 * adaptor identity (e.g. SDF checks SKIP on Odoo) and read deployable
 * artefacts (e.g. SDF/Objects/customrecord_*.xml) separately from prose.
 */

interface AdaptorRun {
  adaptor: AdaptorId;
  bundlePath: string;
  snap: BundleSnapshot;
  score: BundleScore;
}

let runs: AdaptorRun[] = [];

beforeAll(async () => {
  if (!BUNDLES_AVAILABLE) return; // describe.skipIf below handles the it-block skip.
  const adaptors: AdaptorId[] = ['odoo', 'netsuite'];
  runs = [];
  for (const adaptor of adaptors) {
    const snap = await loadLatestBundle(adaptor);
    const score = scoreBundle(snap);
    runs.push({ adaptor, bundlePath: snap.bundlePath, snap, score });
  }
  await writeGapReport(runs);
});

async function writeGapReport(runs: AdaptorRun[]): Promise<void> {
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const reportPath = path.join(NSIX_ROOT, `LIFECYCLE_SCORE_${ts}.md`);

  const totalChecks = LIFECYCLE_PHASES.reduce((sum, p) => sum + p.checks.length, 0);

  let md = `# ERPLaunch Lifecycle Score — ${new Date().toISOString().slice(0, 10)}\n\n`;
  md += `Generated by \`apps/api/tests/lifecycle/lifecycleScore.test.ts\`. `;
  md += `Scores both demo bundles (Odoo + NetSuite) against a 9-phase rubric, `;
  md += `${totalChecks} binary checks total.\n\n`;
  md += `**Scoring**: phase_score = passed / (passed + failed) × 10 — SKIP'd checks excluded from the denominator. `;
  md += `Uniform = mean of 9 phases. Front-half-weighted = phases 1–4 weighted ×2, phases 5–9 weighted ×1. `;
  md += `When every check in a phase SKIPs, score defaults to 10 (vacuous-truth contract).\n\n`;
  md += `---\n\n`;

  for (const run of runs) {
    const adaptorLabel = run.adaptor === 'odoo' ? 'Odoo' : 'NetSuite';
    md += `## ${adaptorLabel}\n\n`;
    md += `**Bundle**: \`${path.relative(NSIX_ROOT, run.bundlePath)}\`\n\n`;
    md += `**Uniform overall**: ${run.score.uniformOverall} / 10  |  `;
    md += `**Front-half-weighted overall**: ${run.score.frontHalfWeightedOverall} / 10\n\n`;
    md += `| Phase | Score | Passed/Applicable | Skipped | Failed checks |\n`;
    md += `|---|---:|---:|---:|---|\n`;
    for (const phase of run.score.perPhase) {
      const failed = phase.failedCheckIds.length === 0
        ? '_(all passing)_'
        : phase.failedCheckIds.map((id) => `\`${id}\``).join(', ');
      const skippedCol = phase.skipped === 0
        ? '0'
        : `${phase.skipped} (${phase.skippedCheckIds.map((id) => `\`${id}\``).join(', ')})`;
      md += `| ${phase.number}. ${phase.name} | ${phase.score} | ${phase.passed}/${phase.applicable} | ${skippedCol} | ${failed} |\n`;
    }
    md += `\n`;
  }

  // ── Cross-adaptor gap summary ──
  md += `## Gap summary (across both adaptors)\n\n`;
  const failuresByCheck = new Map<string, { description: string; adaptors: Set<AdaptorId> }>();
  for (const run of runs) {
    for (const phase of run.score.perPhase) {
      for (let i = 0; i < phase.failedCheckIds.length; i++) {
        const id = phase.failedCheckIds[i];
        const desc = phase.failedCheckDescriptions[i];
        if (!failuresByCheck.has(id)) {
          failuresByCheck.set(id, { description: desc, adaptors: new Set() });
        }
        failuresByCheck.get(id)!.adaptors.add(run.adaptor);
      }
    }
  }
  if (failuresByCheck.size === 0) {
    md += `_No failed checks. All ${totalChecks} rubric items either pass or SKIP on both adaptors._\n\n`;
  } else {
    // Sort by phase id (the prefix p1/p2/... before the dot).
    const sorted = [...failuresByCheck.entries()].sort(([a], [b]) => a.localeCompare(b));
    for (const [id, { description, adaptors }] of sorted) {
      const adaptorList = [...adaptors].sort().join(' + ');
      md += `- \`${id}\` — ${description}  _(failing on: **${adaptorList}**)_\n`;
    }
    md += `\n`;
  }

  // ── Skipped checks summary ──
  md += `## Skipped checks (adaptor-conditional)\n\n`;
  const skipsByCheck = new Map<string, Set<AdaptorId>>();
  for (const run of runs) {
    for (const phase of run.score.perPhase) {
      for (const id of phase.skippedCheckIds) {
        if (!skipsByCheck.has(id)) skipsByCheck.set(id, new Set());
        skipsByCheck.get(id)!.add(run.adaptor);
      }
    }
  }
  if (skipsByCheck.size === 0) {
    md += `_No checks SKIP'd on either adaptor._\n\n`;
  } else {
    const sortedSkips = [...skipsByCheck.entries()].sort(([a], [b]) => a.localeCompare(b));
    for (const [id, adaptors] of sortedSkips) {
      const adaptorList = [...adaptors].sort().join(' + ');
      md += `- \`${id}\` — _(skipped on: **${adaptorList}**)_\n`;
    }
    md += `\n`;
  }

  // ── Threshold-gate table ──
  md += `## Threshold gates (assertion targets)\n\n`;
  md += `| Gate | Threshold | Odoo | NetSuite |\n`;
  md += `|---|---|---:|---:|\n`;
  const o = runs.find((r) => r.adaptor === 'odoo')!.score;
  const n = runs.find((r) => r.adaptor === 'netsuite')!.score;
  md += `| Uniform overall | ≥ 4.0 | ${o.uniformOverall} | ${n.uniformOverall} |\n`;
  md += `| Front-half-weighted overall | ≥ 7.0 | ${o.frontHalfWeightedOverall} | ${n.frontHalfWeightedOverall} |\n`;
  const oP1 = o.perPhase.find((p) => p.number === 1)!;
  const nP1 = n.perPhase.find((p) => p.number === 1)!;
  const oP2 = o.perPhase.find((p) => p.number === 2)!;
  const nP2 = n.perPhase.find((p) => p.number === 2)!;
  const oP3 = o.perPhase.find((p) => p.number === 3)!;
  const nP3 = n.perPhase.find((p) => p.number === 3)!;
  const oP4 = o.perPhase.find((p) => p.number === 4)!;
  const nP4 = n.perPhase.find((p) => p.number === 4)!;
  md += `| Phase 1 (Kickoff) | ≥ 8.0 | ${oP1.score} | ${nP1.score} |\n`;
  md += `| Phase 2 (Discovery) | ≥ 8.0 | ${oP2.score} | ${nP2.score} |\n`;
  md += `| Phase 3 (Solution Design) | ≥ 9.0 | ${oP3.score} | ${nP3.score} |\n`;
  md += `| Phase 4 (Build) — Odoo ≥ 8.0, NetSuite ≥ 9.0 | adaptor-specific | ${oP4.score} | ${nP4.score} |\n`;
  md += `\n`;

  await fs.writeFile(reportPath, md, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[lifecycle harness] gap report → ${reportPath}`);
}

// ─── Threshold-gate assertions ───────────────────────────────────────────────

describe.skipIf(!BUNDLES_AVAILABLE)('Lifecycle harness — threshold gates', () => {
  it('runs against both adaptor demo bundles', () => {
    expect(runs.length).toBe(2);
    expect(runs.map((r) => r.adaptor).sort()).toEqual(['netsuite', 'odoo']);
  });

  it('Odoo bundle uniform overall ≥ 4.0', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(o.score.uniformOverall, formatScoreDetails('odoo', o.score)).toBeGreaterThanOrEqual(4.0);
  });

  it('Odoo bundle front-half-weighted overall ≥ 7.0 (ratcheted after NS SD Depth Pack)', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(
      o.score.frontHalfWeightedOverall,
      formatScoreDetails('odoo', o.score),
    ).toBeGreaterThanOrEqual(7.0);
  });

  it('Odoo bundle Phase 1 (Kickoff) ≥ 8.0 — Kickoff Pack just shipped, should be near-full', () => {
    const p1 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 1)!;
    expect(
      p1.score,
      `Phase 1 (Kickoff) failed: ${p1.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('Odoo bundle Phase 2 (Discovery) ≥ 8.0', () => {
    const p2 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 2)!;
    expect(
      p2.score,
      `Phase 2 (Discovery) failed: ${p2.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle uniform overall ≥ 4.0', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(
      n.score.uniformOverall,
      formatScoreDetails('netsuite', n.score),
    ).toBeGreaterThanOrEqual(4.0);
  });

  it('NetSuite bundle front-half-weighted overall ≥ 7.0 (ratcheted after NS SD Depth Pack)', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(
      n.score.frontHalfWeightedOverall,
      formatScoreDetails('netsuite', n.score),
    ).toBeGreaterThanOrEqual(7.0);
  });

  it('NetSuite bundle Phase 1 (Kickoff) ≥ 8.0', () => {
    const p1 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 1)!;
    expect(
      p1.score,
      `Phase 1 (Kickoff) failed: ${p1.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle Phase 2 (Discovery) ≥ 8.0', () => {
    const p2 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 2)!;
    expect(
      p2.score,
      `Phase 2 (Discovery) failed: ${p2.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  // Phase 3 (Solution Design) gate — NEW after NS SD Depth Pack.
  // Pre-pack scores: Odoo 10/10, NetSuite 4/10. Post-pack: both 10/10.
  // Ratcheted to ≥ 9.0 to lock in the 4 → 10 jump and prevent silent
  // regressions when future packs touch the schema or generator.
  it('Odoo bundle Phase 3 (Solution Design) ≥ 9.0', () => {
    const p3 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 3)!;
    expect(
      p3.score,
      `Phase 3 (Solution Design) failed: ${p3.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  it('NetSuite bundle Phase 3 (Solution Design) ≥ 9.0 — locks in NS SD Depth Pack jump from 4/10', () => {
    const p3 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 3)!;
    expect(
      p3.score,
      `Phase 3 (Solution Design) failed: ${p3.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Phase 4 (Build) gates — NEW after SDF Custom Records pack + harness
  // extension. Odoo: 5 prose checks, score holds at the existing ≥ 8.0
  // floor (the 4 SDF checks SKIP on Odoo and don't move the denominator).
  // NetSuite: 5 prose checks + 4 SDF checks (manifest, deploy, ≥1
  // customrecord_*.xml emitted, every emitted file has the audit-fix-#1
  // root). Pre-extension NS Phase 4 was 8/10 (prose-only); post-extension
  // should land near 9.5+/10. Ratchet to ≥ 9.0 — anything under 9.0
  // means the harness loader didn't see the SDF artefacts (path
  // resolution bug or generator regression).
  it('Odoo bundle Phase 4 (Build) ≥ 8.0', () => {
    const p4 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 4)!;
    expect(
      p4.score,
      `Phase 4 (Build) failed: ${p4.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle Phase 4 (Build) ≥ 9.0 — locks in SDF artefact checks post-real-code generator', () => {
    const p4 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 4)!;
    expect(
      p4.score,
      `Phase 4 (Build) failed: ${p4.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Phase 5 (Test) gates — NEW after Pack T (Test Artifacts). Pre-Pack-T
  // floor was 3/10 on both adaptors (only the UAT plan existed; no test
  // scripts, sign-off matrix, defect log, performance plan, or
  // regression suite). Pack T adds the five remaining artefacts and
  // enriches UAT_Plan with acceptance criteria + linked test scripts.
  // Both adaptors now hit 12/12 of the rubric on the demo bundles.
  // Ratcheted to ≥ 8.0 — anything below 8.0 means a Pack T artefact
  // dropped or the harness loader stopped seeing Test_Scripts/.
  it('Odoo bundle Phase 5 (Test) ≥ 8.0 — locks in Pack T closure (3/10 → 9+/10)', () => {
    const p5 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 5)!;
    expect(
      p5.score,
      `Phase 5 (Test) failed: ${p5.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle Phase 5 (Test) ≥ 8.0 — locks in Pack T closure (3/10 → 9+/10)', () => {
    const p5 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 5)!;
    expect(
      p5.score,
      `Phase 5 (Test) failed: ${p5.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  // Phase 6 (Train) gates — NEW after Pack U (Training Collateral).
  // Pre-Pack-U: Odoo 5/10 (only Training_Manual + 2 sections passed —
  // schema-driven Odoo branch didn't carry "Quick Reference" / per-role
  // headings). NS 10/10 (broader hand-tuned content). Pack U adds 7
  // new artefact checks that fire on BOTH adaptors. Both adaptors now
  // hit 11/11 of the rubric on the demo bundles. Ratcheted to ≥ 9.0
  // — anything below 9.0 means a Pack U artefact dropped or the
  // harness loader stopped seeing Documentation/Training/.
  it('Odoo bundle Phase 6 (Train) ≥ 9.0 — locks in Pack U closure (5/10 → 9+/10)', () => {
    const p6 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 6)!;
    expect(
      p6.score,
      `Phase 6 (Train) failed: ${p6.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  it('NetSuite bundle Phase 6 (Train) ≥ 9.0 — locks in Pack U closure', () => {
    const p6 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 6)!;
    expect(
      p6.score,
      `Phase 6 (Train) failed: ${p6.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Phase 7 (Cutover) gates — NEW after Pack V (Cutover Runbook).
  // Pre-Pack-V floor: Odoo 2.5/10 (only Rollback/Smoke keywords matched),
  // NetSuite 0/10 (no Cutover_Runbook). Pack V emits 7 dedicated
  // artefacts → 8 fresh checks; both adaptors now hit 8/8. Ratcheted
  // to ≥ 9.0 — anything below means a Pack V artefact dropped or the
  // harness loader stopped seeing Documentation/Cutover/.
  it('Odoo bundle Phase 7 (Cutover) ≥ 9.0 — locks in Pack V closure (2.5/10 → 9+/10)', () => {
    const p7 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 7)!;
    expect(
      p7.score,
      `Phase 7 (Cutover) failed: ${p7.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  it('NetSuite bundle Phase 7 (Cutover) ≥ 9.0 — locks in Pack V closure (0/10 → 9+/10)', () => {
    const p7 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 7)!;
    expect(
      p7.score,
      `Phase 7 (Cutover) failed: ${p7.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Phase 8 (Hypercare) gates — NEW after Pack X (Hypercare Program).
  // Pre-Pack-X floor: 0/10 on BOTH adaptors (placeholder rubric only;
  // no Hypercare_Plan generated). Pack X emits 7 dedicated artefacts
  // → 10 fresh checks; both adaptors hit 10/10. Ratcheted to ≥ 9.0.
  it('Odoo bundle Phase 8 (Hypercare) ≥ 9.0 — locks in Pack X closure (0/10 → 10/10)', () => {
    const p8 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 8)!;
    expect(
      p8.score,
      `Phase 8 (Hypercare) failed: ${p8.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  it('NetSuite bundle Phase 8 (Hypercare) ≥ 9.0 — locks in Pack X closure (0/10 → 10/10)', () => {
    const p8 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 8)!;
    expect(
      p8.score,
      `Phase 8 (Hypercare) failed: ${p8.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Phase 9 (Stabilize) gates — NEW after Pack Y (Stabilization Roadmap).
  // Pre-Pack-Y floor: 0/10 on BOTH adaptors (placeholder rubric only;
  // no Documentation/Stabilization/ folder existed). Pack Y emits 7
  // dedicated artefacts → 10 fresh checks; both adaptors hit 10/10.
  // Ratcheted to ≥ 9.0. After this lands, EVERY phase floor is closed
  // at ≥ 9.0 — sprint-end snapshot uniform overall ≥ 9.6,
  // front-half-weighted ≥ 9.5.
  it('Odoo bundle Phase 9 (Stabilize) ≥ 9.0 — locks in Pack Y closure (0/10 → 10/10)', () => {
    const p9 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 9)!;
    expect(
      p9.score,
      `Phase 9 (Stabilize) failed: ${p9.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  it('NetSuite bundle Phase 9 (Stabilize) ≥ 9.0 — locks in Pack Y closure (0/10 → 10/10)', () => {
    const p9 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 9)!;
    expect(
      p9.score,
      `Phase 9 (Stabilize) failed: ${p9.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Sprint-end gates: every phase floor closed at ≥ 9.0; uniform
  // overall ≥ 9.6; front-half-weighted ≥ 9.5.
  it('Odoo bundle uniform overall ≥ 9.6 — sprint-end target', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(o.score.uniformOverall).toBeGreaterThanOrEqual(9.6);
  });

  it('NetSuite bundle uniform overall ≥ 9.6 — sprint-end target', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(n.score.uniformOverall).toBeGreaterThanOrEqual(9.6);
  });

  it('Odoo bundle front-half-weighted overall ≥ 9.5 — sprint-end target', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(o.score.frontHalfWeightedOverall).toBeGreaterThanOrEqual(9.5);
  });

  it('NetSuite bundle front-half-weighted overall ≥ 9.5 — sprint-end target', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(n.score.frontHalfWeightedOverall).toBeGreaterThanOrEqual(9.5);
  });
});

function formatScoreDetails(adaptor: AdaptorId, score: BundleScore): string {
  const lines = [`${adaptor} score breakdown:`];
  for (const phase of score.perPhase) {
    const skip = phase.skipped > 0 ? ` skip:${phase.skipped}` : '';
    lines.push(
      `  P${phase.number} ${phase.name}: ${phase.score} (${phase.passed}/${phase.applicable}${skip})`,
    );
  }
  return lines.join('\n');
}
