import { describe, it, expect, beforeAll } from 'vitest';
import path from 'node:path';
import fs from 'node:fs/promises';
import {
  scoreBundle,
  type BundleScore,
  LIFECYCLE_PHASES,
} from './checklist.js';
import {
  loadLatestBundle,
  NSIX_ROOT,
  type AdaptorId,
  type BundleSnapshot,
} from './_helpers.js';

/**
 * Lifecycle validation harness — automated 9-phase coverage scoring of
 * the latest demo bundle for each adaptor. Runs in CI on every generator
 * change so future content packs can't silently lower coverage.
 *
 * Scores both adaptors against the same rubric. Asserts:
 *   - Uniform overall ≥ 4.0 (post-Kickoff baseline)
 *   - Front-half-weighted overall ≥ 7.0 (post-NS SD Depth Pack baseline)
 *   - Phase 1 (Kickoff) ≥ 8.0
 *   - Phase 2 (Discovery) ≥ 8.0
 *   - Phase 3 (Solution Design) ≥ 9.0 (post-NS SD Depth Pack)
 *   - Phase 4 (Build) — Odoo ≥ 8.0, NetSuite ≥ 9.0 (post-SDF Custom
 *     Records pack; NS gets the new SDF artefact checks, Odoo SKIPs them)
 *
 * Writes a markdown gap report to NSIX/LIFECYCLE_SCORE_<ISO>.md after
 * every run with per-phase breakdowns and per-adaptor failed-check lists.
 *
 * Bundle dependency: this test reads the most-recent bundles produced
 * by generate-{odoo,netsuite}-demo-bundle.ts. The harness does NOT
 * regenerate bundles — that's the developer's responsibility before
 * running tests, or a CI step. The test fails with a clear error
 * pointing at the right driver script if bundles are missing.
 *
 * Snapshot shape: post-extension, the loader returns
 * { docs, buildArtefacts, adaptor } so the rubric can branch on
 * adaptor identity (e.g. SDF checks SKIP on Odoo) and read deployable
 * artefacts (e.g. SDF/Objects/customrecord_*.xml) separately from prose.
 */

interface AdaptorRun {
  adaptor: AdaptorId;
  bundlePath: string;
  snap: BundleSnapshot;
  score: BundleScore;
}

let runs: AdaptorRun[] = [];

beforeAll(async () => {
  const adaptors: AdaptorId[] = ['odoo', 'netsuite'];
  runs = [];
  for (const adaptor of adaptors) {
    const snap = await loadLatestBundle(adaptor);
    const score = scoreBundle(snap);
    runs.push({ adaptor, bundlePath: snap.bundlePath, snap, score });
  }
  await writeGapReport(runs);
});

async function writeGapReport(runs: AdaptorRun[]): Promise<void> {
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const reportPath = path.join(NSIX_ROOT, `LIFECYCLE_SCORE_${ts}.md`);

  const totalChecks = LIFECYCLE_PHASES.reduce((sum, p) => sum + p.checks.length, 0);

  let md = `# ERPLaunch Lifecycle Score — ${new Date().toISOString().slice(0, 10)}\n\n`;
  md += `Generated by \`apps/api/tests/lifecycle/lifecycleScore.test.ts\`. `;
  md += `Scores both demo bundles (Odoo + NetSuite) against a 9-phase rubric, `;
  md += `${totalChecks} binary checks total.\n\n`;
  md += `**Scoring**: phase_score = passed / (passed + failed) × 10 — SKIP'd checks excluded from the denominator. `;
  md += `Uniform = mean of 9 phases. Front-half-weighted = phases 1–4 weighted ×2, phases 5–9 weighted ×1. `;
  md += `When every check in a phase SKIPs, score defaults to 10 (vacuous-truth contract).\n\n`;
  md += `---\n\n`;

  for (const run of runs) {
    const adaptorLabel = run.adaptor === 'odoo' ? 'Odoo' : 'NetSuite';
    md += `## ${adaptorLabel}\n\n`;
    md += `**Bundle**: \`${path.relative(NSIX_ROOT, run.bundlePath)}\`\n\n`;
    md += `**Uniform overall**: ${run.score.uniformOverall} / 10  |  `;
    md += `**Front-half-weighted overall**: ${run.score.frontHalfWeightedOverall} / 10\n\n`;
    md += `| Phase | Score | Passed/Applicable | Skipped | Failed checks |\n`;
    md += `|---|---:|---:|---:|---|\n`;
    for (const phase of run.score.perPhase) {
      const failed = phase.failedCheckIds.length === 0
        ? '_(all passing)_'
        : phase.failedCheckIds.map((id) => `\`${id}\``).join(', ');
      const skippedCol = phase.skipped === 0
        ? '0'
        : `${phase.skipped} (${phase.skippedCheckIds.map((id) => `\`${id}\``).join(', ')})`;
      md += `| ${phase.number}. ${phase.name} | ${phase.score} | ${phase.passed}/${phase.applicable} | ${skippedCol} | ${failed} |\n`;
    }
    md += `\n`;
  }

  // ── Cross-adaptor gap summary ──
  md += `## Gap summary (across both adaptors)\n\n`;
  const failuresByCheck = new Map<string, { description: string; adaptors: Set<AdaptorId> }>();
  for (const run of runs) {
    for (const phase of run.score.perPhase) {
      for (let i = 0; i < phase.failedCheckIds.length; i++) {
        const id = phase.failedCheckIds[i];
        const desc = phase.failedCheckDescriptions[i];
        if (!failuresByCheck.has(id)) {
          failuresByCheck.set(id, { description: desc, adaptors: new Set() });
        }
        failuresByCheck.get(id)!.adaptors.add(run.adaptor);
      }
    }
  }
  if (failuresByCheck.size === 0) {
    md += `_No failed checks. All ${totalChecks} rubric items either pass or SKIP on both adaptors._\n\n`;
  } else {
    // Sort by phase id (the prefix p1/p2/... before the dot).
    const sorted = [...failuresByCheck.entries()].sort(([a], [b]) => a.localeCompare(b));
    for (const [id, { description, adaptors }] of sorted) {
      const adaptorList = [...adaptors].sort().join(' + ');
      md += `- \`${id}\` — ${description}  _(failing on: **${adaptorList}**)_\n`;
    }
    md += `\n`;
  }

  // ── Skipped checks summary ──
  md += `## Skipped checks (adaptor-conditional)\n\n`;
  const skipsByCheck = new Map<string, Set<AdaptorId>>();
  for (const run of runs) {
    for (const phase of run.score.perPhase) {
      for (const id of phase.skippedCheckIds) {
        if (!skipsByCheck.has(id)) skipsByCheck.set(id, new Set());
        skipsByCheck.get(id)!.add(run.adaptor);
      }
    }
  }
  if (skipsByCheck.size === 0) {
    md += `_No checks SKIP'd on either adaptor._\n\n`;
  } else {
    const sortedSkips = [...skipsByCheck.entries()].sort(([a], [b]) => a.localeCompare(b));
    for (const [id, adaptors] of sortedSkips) {
      const adaptorList = [...adaptors].sort().join(' + ');
      md += `- \`${id}\` — _(skipped on: **${adaptorList}**)_\n`;
    }
    md += `\n`;
  }

  // ── Threshold-gate table ──
  md += `## Threshold gates (assertion targets)\n\n`;
  md += `| Gate | Threshold | Odoo | NetSuite |\n`;
  md += `|---|---|---:|---:|\n`;
  const o = runs.find((r) => r.adaptor === 'odoo')!.score;
  const n = runs.find((r) => r.adaptor === 'netsuite')!.score;
  md += `| Uniform overall | ≥ 4.0 | ${o.uniformOverall} | ${n.uniformOverall} |\n`;
  md += `| Front-half-weighted overall | ≥ 7.0 | ${o.frontHalfWeightedOverall} | ${n.frontHalfWeightedOverall} |\n`;
  const oP1 = o.perPhase.find((p) => p.number === 1)!;
  const nP1 = n.perPhase.find((p) => p.number === 1)!;
  const oP2 = o.perPhase.find((p) => p.number === 2)!;
  const nP2 = n.perPhase.find((p) => p.number === 2)!;
  const oP3 = o.perPhase.find((p) => p.number === 3)!;
  const nP3 = n.perPhase.find((p) => p.number === 3)!;
  const oP4 = o.perPhase.find((p) => p.number === 4)!;
  const nP4 = n.perPhase.find((p) => p.number === 4)!;
  md += `| Phase 1 (Kickoff) | ≥ 8.0 | ${oP1.score} | ${nP1.score} |\n`;
  md += `| Phase 2 (Discovery) | ≥ 8.0 | ${oP2.score} | ${nP2.score} |\n`;
  md += `| Phase 3 (Solution Design) | ≥ 9.0 | ${oP3.score} | ${nP3.score} |\n`;
  md += `| Phase 4 (Build) — Odoo ≥ 8.0, NetSuite ≥ 9.0 | adaptor-specific | ${oP4.score} | ${nP4.score} |\n`;
  md += `\n`;

  await fs.writeFile(reportPath, md, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[lifecycle harness] gap report → ${reportPath}`);
}

// ─── Threshold-gate assertions ───────────────────────────────────────────────

describe('Lifecycle harness — threshold gates', () => {
  it('runs against both adaptor demo bundles', () => {
    expect(runs.length).toBe(2);
    expect(runs.map((r) => r.adaptor).sort()).toEqual(['netsuite', 'odoo']);
  });

  it('Odoo bundle uniform overall ≥ 4.0', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(o.score.uniformOverall, formatScoreDetails('odoo', o.score)).toBeGreaterThanOrEqual(4.0);
  });

  it('Odoo bundle front-half-weighted overall ≥ 7.0 (ratcheted after NS SD Depth Pack)', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(
      o.score.frontHalfWeightedOverall,
      formatScoreDetails('odoo', o.score),
    ).toBeGreaterThanOrEqual(7.0);
  });

  it('Odoo bundle Phase 1 (Kickoff) ≥ 8.0 — Kickoff Pack just shipped, should be near-full', () => {
    const p1 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 1)!;
    expect(
      p1.score,
      `Phase 1 (Kickoff) failed: ${p1.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('Odoo bundle Phase 2 (Discovery) ≥ 8.0', () => {
    const p2 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 2)!;
    expect(
      p2.score,
      `Phase 2 (Discovery) failed: ${p2.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle uniform overall ≥ 4.0', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(
      n.score.uniformOverall,
      formatScoreDetails('netsuite', n.score),
    ).toBeGreaterThanOrEqual(4.0);
  });

  it('NetSuite bundle front-half-weighted overall ≥ 7.0 (ratcheted after NS SD Depth Pack)', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(
      n.score.frontHalfWeightedOverall,
      formatScoreDetails('netsuite', n.score),
    ).toBeGreaterThanOrEqual(7.0);
  });

  it('NetSuite bundle Phase 1 (Kickoff) ≥ 8.0', () => {
    const p1 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 1)!;
    expect(
      p1.score,
      `Phase 1 (Kickoff) failed: ${p1.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle Phase 2 (Discovery) ≥ 8.0', () => {
    const p2 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 2)!;
    expect(
      p2.score,
      `Phase 2 (Discovery) failed: ${p2.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  // Phase 3 (Solution Design) gate — NEW after NS SD Depth Pack.
  // Pre-pack scores: Odoo 10/10, NetSuite 4/10. Post-pack: both 10/10.
  // Ratcheted to ≥ 9.0 to lock in the 4 → 10 jump and prevent silent
  // regressions when future packs touch the schema or generator.
  it('Odoo bundle Phase 3 (Solution Design) ≥ 9.0', () => {
    const p3 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 3)!;
    expect(
      p3.score,
      `Phase 3 (Solution Design) failed: ${p3.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  it('NetSuite bundle Phase 3 (Solution Design) ≥ 9.0 — locks in NS SD Depth Pack jump from 4/10', () => {
    const p3 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 3)!;
    expect(
      p3.score,
      `Phase 3 (Solution Design) failed: ${p3.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });

  // Phase 4 (Build) gates — NEW after SDF Custom Records pack + harness
  // extension. Odoo: 5 prose checks, score holds at the existing ≥ 8.0
  // floor (the 4 SDF checks SKIP on Odoo and don't move the denominator).
  // NetSuite: 5 prose checks + 4 SDF checks (manifest, deploy, ≥1
  // customrecord_*.xml emitted, every emitted file has the audit-fix-#1
  // root). Pre-extension NS Phase 4 was 8/10 (prose-only); post-extension
  // should land near 9.5+/10. Ratchet to ≥ 9.0 — anything under 9.0
  // means the harness loader didn't see the SDF artefacts (path
  // resolution bug or generator regression).
  it('Odoo bundle Phase 4 (Build) ≥ 8.0', () => {
    const p4 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 4)!;
    expect(
      p4.score,
      `Phase 4 (Build) failed: ${p4.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle Phase 4 (Build) ≥ 9.0 — locks in SDF artefact checks post-real-code generator', () => {
    const p4 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 4)!;
    expect(
      p4.score,
      `Phase 4 (Build) failed: ${p4.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(9.0);
  });
});

function formatScoreDetails(adaptor: AdaptorId, score: BundleScore): string {
  const lines = [`${adaptor} score breakdown:`];
  for (const phase of score.perPhase) {
    const skip = phase.skipped > 0 ? ` skip:${phase.skipped}` : '';
    lines.push(
      `  P${phase.number} ${phase.name}: ${phase.score} (${phase.passed}/${phase.applicable}${skip})`,
    );
  }
  return lines.join('\n');
}
