import { describe, it, expect, beforeAll } from 'vitest';
import path from 'node:path';
import fs from 'node:fs/promises';
import {
  scoreBundle,
  type BundleScore,
  LIFECYCLE_PHASES,
} from './checklist.js';
import { loadLatestBundle, NSIX_ROOT, type AdaptorId } from './_helpers.js';

/**
 * Lifecycle validation harness — automated 9-phase coverage scoring of
 * the latest demo bundle for each adaptor. Runs in CI on every generator
 * change so future content packs can't silently lower coverage.
 *
 * Scores both adaptors against the same rubric. Asserts:
 *   - Uniform overall ≥ 4.0 (post-Kickoff baseline; was 3.0 before)
 *   - Front-half-weighted overall ≥ 6.0 (post-Kickoff baseline; was 5.5)
 *   - Phase 1 (Kickoff) ≥ 8.0 (just shipped; should be near-full)
 *   - Phase 2 (Discovery) ≥ 8.0 (already at 8/10 from prior packs)
 *
 * Writes a markdown gap report to NSIX/LIFECYCLE_SCORE_<ISO>.md after
 * every run with per-phase breakdowns and per-adaptor failed-check lists.
 *
 * Bundle dependency: this test reads the most-recent bundles produced
 * by generate-{odoo,netsuite}-demo-bundle.ts. The harness does NOT
 * regenerate bundles — that's the developer's responsibility before
 * running tests, or a CI step. The test fails with a clear error
 * pointing at the right driver script if bundles are missing.
 */

interface AdaptorRun {
  adaptor: AdaptorId;
  bundlePath: string;
  files: ReadonlyMap<string, string>;
  score: BundleScore;
}

let runs: AdaptorRun[] = [];

beforeAll(async () => {
  const adaptors: AdaptorId[] = ['odoo', 'netsuite'];
  runs = [];
  for (const adaptor of adaptors) {
    const { bundlePath, files } = await loadLatestBundle(adaptor);
    const score = scoreBundle(files);
    runs.push({ adaptor, bundlePath, files, score });
  }
  await writeGapReport(runs);
});

async function writeGapReport(runs: AdaptorRun[]): Promise<void> {
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const reportPath = path.join(NSIX_ROOT, `LIFECYCLE_SCORE_${ts}.md`);

  let md = `# ERPLaunch Lifecycle Score — ${new Date().toISOString().slice(0, 10)}\n\n`;
  md += `Generated by \`apps/api/tests/lifecycle/lifecycleScore.test.ts\`. `;
  md += `Scores both demo bundles (Odoo + NetSuite) against a 9-phase rubric, `;
  md += `${LIFECYCLE_PHASES.reduce((sum, p) => sum + p.checks.length, 0)} binary checks total.\n\n`;
  md += `**Scoring**: phase_score = (passed / total) × 10. `;
  md += `Uniform = mean of 9 phases. Front-half-weighted = phases 1–4 weighted ×2, phases 5–9 weighted ×1.\n\n`;
  md += `---\n\n`;

  for (const run of runs) {
    const adaptorLabel = run.adaptor === 'odoo' ? 'Odoo' : 'NetSuite';
    md += `## ${adaptorLabel}\n\n`;
    md += `**Bundle**: \`${path.relative(NSIX_ROOT, run.bundlePath)}\`\n\n`;
    md += `**Uniform overall**: ${run.score.uniformOverall} / 10  |  `;
    md += `**Front-half-weighted overall**: ${run.score.frontHalfWeightedOverall} / 10\n\n`;
    md += `| Phase | Score | Passed/Total | Failed checks |\n`;
    md += `|---|---:|---:|---|\n`;
    for (const phase of run.score.perPhase) {
      const failed = phase.failedCheckIds.length === 0
        ? '_(all passing)_'
        : phase.failedCheckIds.map((id) => `\`${id}\``).join(', ');
      md += `| ${phase.number}. ${phase.name} | ${phase.score} | ${phase.passed}/${phase.total} | ${failed} |\n`;
    }
    md += `\n`;
  }

  // ── Cross-adaptor gap summary ──
  md += `## Gap summary (across both adaptors)\n\n`;
  const failuresByCheck = new Map<string, { description: string; adaptors: Set<AdaptorId> }>();
  for (const run of runs) {
    for (const phase of run.score.perPhase) {
      for (let i = 0; i < phase.failedCheckIds.length; i++) {
        const id = phase.failedCheckIds[i];
        const desc = phase.failedCheckDescriptions[i];
        if (!failuresByCheck.has(id)) {
          failuresByCheck.set(id, { description: desc, adaptors: new Set() });
        }
        failuresByCheck.get(id)!.adaptors.add(run.adaptor);
      }
    }
  }
  if (failuresByCheck.size === 0) {
    md += `_No failed checks. All ${LIFECYCLE_PHASES.reduce((sum, p) => sum + p.checks.length, 0)} ` +
      `rubric items pass on both adaptors._\n\n`;
  } else {
    // Sort by phase id (the prefix p1/p2/... before the dot).
    const sorted = [...failuresByCheck.entries()].sort(([a], [b]) => a.localeCompare(b));
    for (const [id, { description, adaptors }] of sorted) {
      const adaptorList = [...adaptors].sort().join(' + ');
      md += `- \`${id}\` — ${description}  _(failing on: **${adaptorList}**)_\n`;
    }
    md += `\n`;
  }

  // ── Front-half-weighted change tracking ──
  md += `## Threshold gates (assertion targets)\n\n`;
  md += `| Gate | Threshold | Odoo | NetSuite |\n`;
  md += `|---|---:|---:|---:|\n`;
  const o = runs.find((r) => r.adaptor === 'odoo')!.score;
  const n = runs.find((r) => r.adaptor === 'netsuite')!.score;
  md += `| Uniform overall | ≥ 4.0 | ${o.uniformOverall} | ${n.uniformOverall} |\n`;
  md += `| Front-half-weighted overall | ≥ 6.0 | ${o.frontHalfWeightedOverall} | ${n.frontHalfWeightedOverall} |\n`;
  const oP1 = o.perPhase.find((p) => p.number === 1)!;
  const nP1 = n.perPhase.find((p) => p.number === 1)!;
  const oP2 = o.perPhase.find((p) => p.number === 2)!;
  const nP2 = n.perPhase.find((p) => p.number === 2)!;
  md += `| Phase 1 (Kickoff) | ≥ 8.0 | ${oP1.score} | ${nP1.score} |\n`;
  md += `| Phase 2 (Discovery) | ≥ 8.0 | ${oP2.score} | ${nP2.score} |\n`;
  md += `\n`;

  await fs.writeFile(reportPath, md, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[lifecycle harness] gap report → ${reportPath}`);
}

// ─── Threshold-gate assertions ───────────────────────────────────────────────

describe('Lifecycle harness — threshold gates', () => {
  it('runs against both adaptor demo bundles', () => {
    expect(runs.length).toBe(2);
    expect(runs.map((r) => r.adaptor).sort()).toEqual(['netsuite', 'odoo']);
  });

  it('Odoo bundle uniform overall ≥ 4.0', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(o.score.uniformOverall, formatScoreDetails('odoo', o.score)).toBeGreaterThanOrEqual(4.0);
  });

  it('Odoo bundle front-half-weighted overall ≥ 6.0', () => {
    const o = runs.find((r) => r.adaptor === 'odoo')!;
    expect(
      o.score.frontHalfWeightedOverall,
      formatScoreDetails('odoo', o.score),
    ).toBeGreaterThanOrEqual(6.0);
  });

  it('Odoo bundle Phase 1 (Kickoff) ≥ 8.0 — Kickoff Pack just shipped, should be near-full', () => {
    const p1 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 1)!;
    expect(
      p1.score,
      `Phase 1 (Kickoff) failed: ${p1.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('Odoo bundle Phase 2 (Discovery) ≥ 8.0', () => {
    const p2 = runs.find((r) => r.adaptor === 'odoo')!.score.perPhase.find((p) => p.number === 2)!;
    expect(
      p2.score,
      `Phase 2 (Discovery) failed: ${p2.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle uniform overall ≥ 4.0', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(
      n.score.uniformOverall,
      formatScoreDetails('netsuite', n.score),
    ).toBeGreaterThanOrEqual(4.0);
  });

  it('NetSuite bundle front-half-weighted overall ≥ 6.0', () => {
    const n = runs.find((r) => r.adaptor === 'netsuite')!;
    expect(
      n.score.frontHalfWeightedOverall,
      formatScoreDetails('netsuite', n.score),
    ).toBeGreaterThanOrEqual(6.0);
  });

  it('NetSuite bundle Phase 1 (Kickoff) ≥ 8.0', () => {
    const p1 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 1)!;
    expect(
      p1.score,
      `Phase 1 (Kickoff) failed: ${p1.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });

  it('NetSuite bundle Phase 2 (Discovery) ≥ 8.0', () => {
    const p2 = runs.find((r) => r.adaptor === 'netsuite')!.score.perPhase.find((p) => p.number === 2)!;
    expect(
      p2.score,
      `Phase 2 (Discovery) failed: ${p2.failedCheckDescriptions.join('; ')}`,
    ).toBeGreaterThanOrEqual(8.0);
  });
});

function formatScoreDetails(adaptor: AdaptorId, score: BundleScore): string {
  const lines = [`${adaptor} score breakdown:`];
  for (const phase of score.perPhase) {
    lines.push(`  P${phase.number} ${phase.name}: ${phase.score} (${phase.passed}/${phase.total})`);
  }
  return lines.join('\n');
}
