import { describe, it, expect } from 'vitest';
import {
  generateBRD,
  generateBRDHtml,
  type BRDData,
  type AdaptorContext,
} from '../../../src/services/generators/brdGenerator.js';

/**
 * BRD adaptor-awareness tests (Phase 1 of generators-are-adaptor-aware).
 *
 * Each describe block constructs a BRDData with a NetSuite or Odoo adaptor
 * context and asserts the prose flexes accordingly. The NetSuite branch
 * preserves the existing voice; the Odoo branch is the new path the
 * cross-platform fix has to deliver.
 *
 * Anti-bleed assertions on the Odoo branch:
 *   - no "SuiteScript" / "SDF" / "subsidiary" / "OneWorld" / "NetSuite"
 *   - no "Ofoq NetSuite Accelerator" stale byline
 * These are the strings an Odoo client would catch in the first paragraph
 * if the generator were still hardcoded for NetSuite.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<BRDData> = {}): BRDData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    license: { edition: 'MID_MARKET', modules: [] },
    answers: {},
    ...overrides,
  };
}

describe('generateBRD — NetSuite adaptor (preserves existing voice)', () => {
  const md = generateBRD(baseData(NETSUITE_CTX));

  it('describes the document as a NetSuite implementation', () => {
    expect(md).toContain('NetSuite implementation');
  });

  it('renders the NetSuite-prefixed edition label', () => {
    expect(md).toContain('**Edition:** NetSuite Mid-Market');
  });

  it('disclaimer references a certified NetSuite consultant', () => {
    expect(md).toMatch(/certified\s+NetSuite\s+consultant/);
  });

  it('next-steps mentions the SDF deployment package', () => {
    expect(md).toContain('SDF deployment package');
  });

  it('uses the ERPLaunch byline (no stale Ofoq NetSuite Accelerator string)', () => {
    expect(md).toContain('ERPLaunch');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('HTML wrapper carries the same NetSuite voice + ERPLaunch footer', () => {
    const html = generateBRDHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('NetSuite implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateBRD — Odoo adaptor (new path)', () => {
  const md = generateBRD(baseData(ODOO_CTX));

  it('describes the document as an Odoo implementation', () => {
    expect(md).toContain('Odoo implementation');
  });

  it('renders the bare edition label without an Odoo-prefix the adaptor did not provide', () => {
    expect(md).toContain('**Edition:** Enterprise');
    // Specifically must not stamp the wrong platform name onto the edition.
    expect(md).not.toContain('NetSuite Enterprise');
  });

  it('disclaimer references a certified Odoo consultant', () => {
    expect(md).toMatch(/certified\s+Odoo\s+consultant/);
  });

  it('next-steps phrasing is the Odoo configuration-package voice, not the SDF one', () => {
    expect(md).toContain('configuration package');
    expect(md).not.toContain('SDF deployment package');
  });

  it('contains no NetSuite-specific terminology', () => {
    // These would be caught in the first paragraph by an Odoo-savvy reader.
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `BRD must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });

  it('uses the ERPLaunch byline (no stale Ofoq NetSuite Accelerator string)', () => {
    expect(md).toContain('ERPLaunch');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('HTML wrapper carries the Odoo voice + ERPLaunch footer + no NetSuite leakage', () => {
    const html = generateBRDHtml(baseData(ODOO_CTX));
    expect(html).toContain('Odoo implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
    for (const banned of ['SuiteScript', 'SDF', 'OneWorld', 'NetSuite']) {
      expect(html, `BRD HTML must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

// ─── Regression class: rendered prose contains wizard-answer content ─────────
//
// Previously only the cover/license/footer were asserted; the workstream
// loop's hardcoded r2r/p2p/o2c/mfg/rtn list silently produced an empty
// Workstream Requirements section for every Odoo engagement. These tests
// pin that the schema-driven walk now flows wizard answers into the
// rendered markdown.

describe('generateBRD — workstream loop reads from adaptor.flows (regression class)', () => {
  // Minimal Odoo-shaped adaptor schema spanning Foundation + Tax + a
  // legacy R2R section, mirroring the live seed-odoo answer namespace
  // ('odoo.foundation.X', 'odoo.tax.X', 'odoo.company.X').
  const ODOO_FLOWS = [
    {
      id: 'FOUNDATION',
      label: 'Project Foundation',
      description: 'Deployment, edition, geography, entity structure.',
      sections: [
        {
          id: 'deployment',
          label: 'Deployment & Licensing',
          order: 1,
          questions: [
            {
              id: 'odoo.foundation.deploymentMode',
              label: 'Hosting & deployment mode',
              inputType: 'SINGLE_SELECT' as const,
              options: [
                { value: 'ONLINE',     label: 'Odoo Online' },
                { value: 'ODOOSH',     label: 'Odoo.sh' },
                { value: 'SELFHOSTED', label: 'Self-hosted' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'TAX',
      label: 'Tax Engine',
      description: 'Tax behavior, defaults, fiscal positions.',
      sections: [
        {
          id: 'behavior',
          label: 'Default Tax Behavior',
          order: 1,
          questions: [
            {
              id: 'odoo.tax.defaultSalesTax',
              label: 'Default Sales Tax (rate name + percent)',
              inputType: 'TEXT' as const,
            },
          ],
        },
      ],
    },
  ];

  const ODOO_CTX_WITH_FLOWS: AdaptorContext = {
    ...ODOO_CTX,
    flows: ODOO_FLOWS,
  };

  it('renders the Project Foundation flow heading + question label + answer when the Odoo schema is present and answers are populated', () => {
    const md = generateBRD(baseData(ODOO_CTX_WITH_FLOWS, {
      answers: {
        'odoo.foundation.deploymentMode': 'ODOOSH',
        'odoo.tax.defaultSalesTax': 'VAT 5%',
      },
    }));
    expect(md).toContain('Project Foundation');
    expect(md).toContain('Hosting & deployment mode');
    // SINGLE_SELECT answers render the option label, not the raw value.
    expect(md).toContain('Odoo.sh');
  });

  it('renders the Tax Engine flow heading + question label + answer', () => {
    const md = generateBRD(baseData(ODOO_CTX_WITH_FLOWS, {
      answers: {
        'odoo.foundation.deploymentMode': 'ODOOSH',
        'odoo.tax.defaultSalesTax': 'VAT 5%',
      },
    }));
    expect(md).toContain('Tax Engine');
    expect(md).toContain('Default Sales Tax');
    expect(md).toContain('VAT 5%');
  });

  it('skips a flow entirely when none of its questions are answered', () => {
    // Only Foundation answered; Tax should not produce a heading.
    const md = generateBRD(baseData(ODOO_CTX_WITH_FLOWS, {
      answers: { 'odoo.foundation.deploymentMode': 'ODOOSH' },
    }));
    expect(md).toContain('Project Foundation');
    expect(md).not.toContain('Tax Engine');
  });

  it('NetSuite flow labels still render (regression guard for the existing branch)', () => {
    // Construct a minimal NetSuite-style schema where the question.id
    // carries the lowercased flow prefix, mirroring the real adaptor.
    const NS_FLOWS = [
      {
        id: 'R2R',
        label: 'Record-to-Report',
        description: 'GL, periods, reporting.',
        sections: [
          {
            id: 'entities',
            label: 'Entities',
            order: 1,
            questions: [
              {
                id: 'r2r.entities.multiEntity',
                label: 'Multi-entity / OneWorld',
                inputType: 'BOOLEAN' as const,
              },
            ],
          },
        ],
      },
    ];
    const md = generateBRD(baseData({ ...NETSUITE_CTX, flows: NS_FLOWS }, {
      answers: { 'r2r.entities.multiEntity': true },
    }));
    expect(md).toContain('Record-to-Report');
    expect(md).toContain('Multi-entity');
    // BOOLEAN true renders as "Yes" via formatAnswer.
    expect(md).toMatch(/Yes/);
  });
});

describe('generateBRD — custom adaptor (fall-through default)', () => {
  // Custom adaptors get a Capitalize(adaptorId) name resolved upstream in
  // generation.ts; the generator just consumes whatever the context says.
  // This proves no path quietly falls back to NetSuite phrasing.
  const CUSTOM_CTX: AdaptorContext = {
    id: 'custom:acme-erp',
    name: 'Acme ERP',
    editionLabel: 'Standard',
    consultantQualifier: 'Acme ERP',
    nextStepLanguage:
      'the Acme ERP build phase using the configuration package generated by ERPLaunch',
  };

  it('renders Acme ERP-flavored prose with no NetSuite leak', () => {
    const md = generateBRD(baseData(CUSTOM_CTX));
    expect(md).toContain('Acme ERP implementation');
    expect(md).toContain('certified Acme ERP consultant');
    expect(md).not.toContain('NetSuite');
    expect(md).not.toContain('SuiteScript');
    expect(md).not.toContain('SDF');
  });
});
