import { describe, it, expect } from 'vitest';
import {
  generateKickoff,
  generateKickoffHtml,
  type KickoffData,
  type KickoffMember,
} from '../../../src/services/generators/kickoffGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * Project Kickoff generator tests — universal pack (runs on every adaptor).
 *
 * Asserts:
 *   - All 6 subsections render (Project Charter, Stakeholder Map, RACI,
 *     Governance, Communication, Agenda) + Sign-off
 *   - RACI table populates with seed-data names when members are passed
 *   - Stakeholder map placeholders appear when members list is empty
 *   - Wizard answers (sponsor / business case / success criteria etc.)
 *     render verbatim from kickoff.* keys
 *   - Adaptor-aware prose: NetSuite kickoff banlist (no Odoo terms);
 *     Odoo kickoff banlist (no NetSuite terms)
 *   - HTML wrapper renders with the right title
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite OneWorld',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const SEED_MEMBERS: KickoffMember[] = [
  { name: 'Helena Reyes', role: 'Project Sponsor / CFO', team: 'CLIENT', email: 'helena@atlas.com' },
  { name: 'David Chen', role: 'Project Manager / VP Finance', team: 'CLIENT', email: 'david@atlas.com' },
  { name: 'Sophie Müller', role: 'Workstream Lead — EU subsidiaries', team: 'CLIENT' },
  { name: 'Hesham Aglan', role: 'Consultant Project Manager', team: 'CONSULTANT', email: 'hesham@erplaunch.io' },
];

const SEED_ANSWERS: Record<string, unknown> = {
  'kickoff.mandate.sponsor': 'Helena Reyes (CFO, Atlas Industries Group)',
  'kickoff.mandate.businessCase': 'Consolidate 4 group subsidiaries onto a single tenant.',
  'kickoff.mandate.successCriteria': 'Close in 5 days\nSingle source of truth\nEliminate manual entries',
  'kickoff.mandate.targetGoLiveDate': '2026-11-15',
  'kickoff.governance.steeringCadence': 'BIWEEKLY',
  'kickoff.governance.workingGroupCadence': 'WEEKLY',
  'kickoff.governance.decisionThresholds': '<$25k: PM\n$25k-$100k: Steering\n>$100k: Sponsor + Steering',
  'kickoff.governance.escalationPath': 'Hesham Aglan → Steering → Helena Reyes',
  'kickoff.communication.statusReportCadence': 'WEEKLY',
  'kickoff.communication.statusReportAudience': 'Helena Reyes — Sponsor\nDavid Chen — Client PM',
  'kickoff.communication.issueReportingChannel': 'SHARED_DOC',
  'kickoff.communication.stakeholderNotes':
    'Robert Atlas (CEO) — quarterly read-out only\nMarcus Webb (Head of IT) — must be informed',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<KickoffData> = {}): KickoffData {
  return {
    clientName: 'Atlas Industries Group',
    adaptor,
    answers: SEED_ANSWERS,
    members: SEED_MEMBERS,
    ...overrides,
  };
}

describe('generateKickoff — structure (all 6 subsections render)', () => {
  const md = generateKickoff(baseData(NETSUITE_CTX));

  it('renders the cover header with client + adaptor name', () => {
    expect(md).toContain('# Project Kickoff');
    expect(md).toContain('Atlas Industries Group');
    expect(md).toContain('NetSuite implementation');
  });

  it('section 1 — Project Charter renders all 5 charter fields', () => {
    expect(md).toContain('## 1. Project Charter');
    expect(md).toContain('Helena Reyes (CFO, Atlas Industries Group)');
    expect(md).toContain('Consolidate 4 group subsidiaries');
    expect(md).toContain('Close in 5 days');
    expect(md).toContain('2026-11-15');
    expect(md).toContain('NetSuite OneWorld'); // editionLabel
  });

  it('section 2 — Stakeholder Map renders the members table', () => {
    expect(md).toContain('## 2. Stakeholder Map');
    expect(md).toContain('| Helena Reyes |');
    expect(md).toContain('| David Chen |');
    expect(md).toContain('| Sophie Müller |');
    expect(md).toContain('| Hesham Aglan |');
    // CLIENT/CONSULTANT side rendered as Client/Consultant
    expect(md).toContain('| Client |');
    expect(md).toContain('| Consultant |');
  });

  it('section 2 — Stakeholder Map renders stakeholder notes (Q3.4)', () => {
    expect(md).toContain('Robert Atlas (CEO)');
    expect(md).toContain('Marcus Webb (Head of IT)');
  });

  it('section 3 — RACI Matrix renders standard activities + auto-fills names', () => {
    expect(md).toContain('## 3. RACI Matrix');
    expect(md).toContain('| Discovery interviews |');
    expect(md).toContain('| Solution design |');
    expect(md).toContain('| Configuration build |');
    expect(md).toContain('| Data migration |');
    expect(md).toContain('| User Acceptance Testing |');
    expect(md).toContain('| Training |');
    expect(md).toContain('| Cutover |');
    expect(md).toContain('| Hypercare |');
    // Auto-fill: consultant PM (Hesham Aglan) appears in Responsible cells
    expect(md).toContain('Hesham Aglan (Consultant Project Manager)');
  });

  it('section 4 — Governance Plan renders steering cadence + escalation path', () => {
    expect(md).toContain('## 4. Governance Plan');
    expect(md).toContain('Bi-weekly'); // steeringCadence option label
    expect(md).toContain('Hesham Aglan → Steering → Helena Reyes');
    expect(md).toContain('<$25k: PM');
  });

  it('section 5 — Communication Plan renders status cadence + audience + channel', () => {
    expect(md).toContain('## 5. Communication Plan');
    expect(md).toContain('Weekly'); // statusReportCadence option label
    expect(md).toContain('Helena Reyes — Sponsor');
    expect(md).toContain('David Chen — Client PM');
    // SHARED_DOC option label
    expect(md).toContain('Shared issue log');
  });

  it('section 6 — Suggested Kickoff Meeting Agenda renders 90-minute schedule', () => {
    expect(md).toContain('## 6. Suggested Kickoff Meeting Agenda');
    expect(md).toContain('0:00–0:10');
    expect(md).toContain('Welcome + introductions');
    expect(md).toContain('1:20–1:30');
    expect(md).toContain('Open Q&A');
  });

  it('renders a Sign-off block for sponsor + client PM + consultant PM', () => {
    expect(md).toContain('## Sign-off');
    // Names auto-filled from members list
    expect(md).toContain('| Project Sponsor (Client) | Helena Reyes |');
    expect(md).toContain('| Client Project Manager | David Chen |');
    expect(md).toContain('| Consultant Project Manager | Hesham Aglan |');
  });
});

describe('generateKickoff — adaptor-aware prose (NetSuite)', () => {
  const md = generateKickoff(baseData(NETSUITE_CTX));

  it('describes the document as a NetSuite implementation', () => {
    expect(md).toContain('NetSuite implementation');
    expect(md).toContain('certified NetSuite consultant');
  });

  it('contains no Odoo-specific terminology (banlist)', () => {
    for (const banned of ['Odoo', 'odoo.sh', 'Community']) {
      expect(md, `NetSuite kickoff must not contain "${banned}"`).not.toContain(banned);
    }
  });
});

describe('generateKickoff — adaptor-aware prose (Odoo)', () => {
  const md = generateKickoff(baseData(ODOO_CTX));

  it('describes the document as an Odoo implementation', () => {
    expect(md).toContain('Odoo implementation');
    expect(md).toContain('certified Odoo consultant');
  });

  it('contains no NetSuite-specific terminology (banlist)', () => {
    for (const banned of ['NetSuite', 'SuiteScript', 'SDF', 'OneWorld', 'subsidiary']) {
      expect(md, `Odoo kickoff must not contain "${banned}"`).not.toContain(banned);
    }
  });
});

describe('generateKickoff — graceful degradation when members list is empty', () => {
  const md = generateKickoff(baseData(NETSUITE_CTX, { members: [] }));

  it('renders a placeholder Stakeholder Map (sponsor / client PM / consultant PM)', () => {
    expect(md).toContain('## 2. Stakeholder Map');
    expect(md).toContain('_[ASSIGN — sponsor]_');
    expect(md).toContain('_[ASSIGN — client PM]_');
    expect(md).toContain('_[ASSIGN — consultant PM]_');
  });

  it('renders RACI placeholders for all roles', () => {
    expect(md).toContain('_ASSIGN — consultant PM_');
    expect(md).toContain('_ASSIGN — client PM_');
    expect(md).toContain('_ASSIGN — sponsor_');
  });

  it('still renders the Sign-off block (with placeholder names)', () => {
    expect(md).toContain('## Sign-off');
    expect(md).toContain('| Project Sponsor (Client) | _[ASSIGN]_ |');
  });
});

describe('generateKickoff — graceful degradation when answers are missing', () => {
  const md = generateKickoff(baseData(NETSUITE_CTX, { answers: {} }));

  it('renders Project Charter with [ASSIGN] placeholders for empty fields', () => {
    expect(md).toContain('## 1. Project Charter');
    expect(md).toContain('_[ASSIGN]_');
  });

  it('still renders all 6 subsections + Sign-off', () => {
    expect(md).toContain('## 1. Project Charter');
    expect(md).toContain('## 2. Stakeholder Map');
    expect(md).toContain('## 3. RACI Matrix');
    expect(md).toContain('## 4. Governance Plan');
    expect(md).toContain('## 5. Communication Plan');
    expect(md).toContain('## 6. Suggested Kickoff Meeting Agenda');
    expect(md).toContain('## Sign-off');
  });
});

describe('generateKickoffHtml — wrapper', () => {
  it('renders an HTML document with the right title', () => {
    const html = generateKickoffHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('Project Kickoff — Atlas Industries Group');
    expect(html).toContain('Generated by ERPLaunch · Project Kickoff for Atlas Industries Group (NetSuite)');
  });

  it('Odoo HTML wrapper has Odoo footer attribution', () => {
    const html = generateKickoffHtml(baseData(ODOO_CTX));
    expect(html).toContain('Generated by ERPLaunch · Project Kickoff for Atlas Industries Group (Odoo)');
    expect(html).not.toContain('NetSuite');
  });
});
