import { describe, it, expect } from 'vitest';
import {
  generateOdooConfigurationPlan,
  generateOdooConfigurationPlanHtml,
  type OdooConfigurationPlanData,
} from '../../../src/services/generators/odooConfigurationPlanGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * Phase 4 — Odoo / non-NetSuite configuration plan tests.
 *
 * This generator is the non-NetSuite build artefact. The orchestrator
 * calls SDF + SuiteScript only when adaptorId === 'netsuite'; everything
 * else gets THIS document instead. So there is intentionally NO NetSuite
 * test branch — the generator should fail / refuse if called with a
 * NetSuite adaptor (gated upstream).
 *
 * Two branches we DO cover:
 *   - Odoo (typical engagement)
 *   - custom:* (firm-authored adaptor)
 *
 * Odoo content the test contract enforces:
 *   - Module install plan: license.modules verbatim PLUS l10n_<country>
 *     auto-prepended based on the country / currency answer
 *   - Studio reminder: when ENTERPRISE_STUDIO is in modules, a section
 *     warns that Studio customizations need to be exported as XML data
 *     files for the deploy package
 *   - Fiscal year setup: pulled from `odoo.company.fiscalYearStart`
 *   - Multi-company: when `odoo.company.multiCompany === true`, the
 *     setup checklist is rendered (one company per legal entity, etc.)
 *
 * Cross-platform banlist: the generator must NEVER emit "NetSuite",
 * "SuiteScript", "SDF", "subsidiary", "OneWorld" — even on the custom:*
 * branch. Same gate as the other 5 generators.
 */

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

const FULL_ODOO_DATA: OdooConfigurationPlanData = {
  clientName: 'Sahel Logistics Ltd.',
  adaptor: ODOO_CTX,
  license: {
    edition: 'ENTERPRISE',
    modules: [
      'BASE_ACCOUNTING', 'BASE_SALES', 'BASE_PURCHASE', 'BASE_INVENTORY',
      'ENTERPRISE_ACCOUNTING', 'ENTERPRISE_STUDIO', 'ENTERPRISE_DOCUMENTS',
      'MRP', 'QUALITY', 'CRM', 'PROJECT', 'TIMESHEETS',
    ],
  },
  answers: {
    'odoo.company.multiCompany': true,
    'odoo.company.currency': 'AED',
    'odoo.company.fiscalYearStart': '01-01',
    'odoo.coa.template': 'LOCALIZATION',
    'odoo.coa.analyticAccounting': true,
  },
};

describe('generateOdooConfigurationPlan — Odoo full demo answer set', () => {
  const md = generateOdooConfigurationPlan(FULL_ODOO_DATA);

  it('uses the Odoo title + ERPLaunch byline', () => {
    expect(md).toContain('# Odoo Configuration Plan');
    expect(md).toMatch(/\*\*Prepared by:\*\*\s+ERPLaunch/);
  });

  it('renders a Module Install Plan section listing every license module', () => {
    // Section headings carry numbering ("## 2. Module Install Plan") so
    // the regex tolerates an optional "<digit(s)>. " prefix.
    expect(md).toMatch(/##\s+(\d+\.\s+)?Module Install Plan/);
    for (const mod of FULL_ODOO_DATA.license.modules) {
      expect(md, `Module Install Plan must list ${mod}`).toContain(mod);
    }
  });

  it('auto-prepends an l10n_<country> module derived from the currency answer', () => {
    // AED → UAE. Odoo's localization module is l10n_ae.
    expect(md).toContain('l10n_ae');
  });

  it('renders the Studio export reminder when ENTERPRISE_STUDIO is in modules', () => {
    expect(md).toMatch(/Studio.*XML/i);
    // Be specific: the reminder is about exporting customizations as
    // XML data files for the deploy package, not just any Studio mention.
    expect(md).toMatch(/export.*XML/i);
  });

  it('renders a Fiscal Year setup section with the configured month-day', () => {
    expect(md).toMatch(/##\s+(\d+\.\s+)?Fiscal Year/);
    expect(md).toContain('01-01');
  });

  it('renders the Multi-Company setup checklist when multiCompany is true', () => {
    expect(md).toMatch(/##\s+(\d+\.\s+)?Multi-?Company/i);
    expect(md).toMatch(/one company per legal entity/i);
    expect(md).toMatch(/intercompany/i);
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `Configuration Plan must not contain "${banned}"`).not.toContain(banned);
    }
  });

  it('HTML wrapper carries Odoo Configuration Plan title + ERPLaunch footer + no banned terms', () => {
    const html = generateOdooConfigurationPlanHtml(FULL_ODOO_DATA);
    expect(html).toContain('Odoo Configuration Plan');
    expect(html).toContain('Generated by ERPLaunch');
    for (const banned of ['SuiteScript', 'SDF', 'OneWorld', 'NetSuite']) {
      expect(html, `Configuration Plan HTML must not contain "${banned}"`).not.toContain(banned);
    }
  });
});

describe('generateOdooConfigurationPlan — branch logic', () => {
  it('skips the Studio reminder when ENTERPRISE_STUDIO is NOT in modules', () => {
    const md = generateOdooConfigurationPlan({
      ...FULL_ODOO_DATA,
      license: { edition: 'COMMUNITY', modules: ['BASE_ACCOUNTING', 'BASE_SALES'] },
    });
    expect(md).not.toMatch(/Studio/i);
  });

  it('skips the Multi-Company section when multiCompany is false', () => {
    const md = generateOdooConfigurationPlan({
      ...FULL_ODOO_DATA,
      answers: { ...FULL_ODOO_DATA.answers, 'odoo.company.multiCompany': false },
    });
    expect(md).not.toMatch(/##\s+(\d+\.\s+)?Multi-?Company/i);
  });

  it('falls back to a sensible message when fiscal year start is not configured', () => {
    const md = generateOdooConfigurationPlan({
      ...FULL_ODOO_DATA,
      answers: { 'odoo.company.multiCompany': false, 'odoo.company.currency': 'AED' },
    });
    expect(md).toMatch(/##\s+(\d+\.\s+)?Fiscal Year/);
    // No specific date should leak; instead a "to be configured" note.
    expect(md).toMatch(/to be configured|not yet configured|not specified/i);
  });

  it('maps common currencies to the right l10n_<country> module', () => {
    const cases: Array<[string, string]> = [
      ['AED', 'l10n_ae'],
      ['USD', 'l10n_us'],
      ['GBP', 'l10n_uk'],
      ['EUR', 'l10n_generic_coa'],  // EUR is multi-country; use the generic CoA
      ['EGP', 'l10n_eg'],
      ['SAR', 'l10n_sa'],
    ];
    for (const [currency, expectedModule] of cases) {
      const md = generateOdooConfigurationPlan({
        ...FULL_ODOO_DATA,
        answers: { ...FULL_ODOO_DATA.answers, 'odoo.company.currency': currency },
      });
      expect(md, `${currency} should map to ${expectedModule}`).toContain(expectedModule);
    }
  });

  it('emits a placeholder localization line when currency is missing', () => {
    const md = generateOdooConfigurationPlan({
      ...FULL_ODOO_DATA,
      answers: { 'odoo.company.multiCompany': false, 'odoo.company.fiscalYearStart': '01-01' },
    });
    // No currency → no specific l10n_<country> module, but the section
    // should still surface so the consultant knows to pick one.
    expect(md).toMatch(/localization|l10n/i);
  });
});

describe('generateOdooConfigurationPlan — custom adaptor (fall-through)', () => {
  it('renders Acme ERP-flavored shell with no NetSuite leak', () => {
    const md = generateOdooConfigurationPlan({
      ...FULL_ODOO_DATA,
      adaptor: CUSTOM_CTX,
    });
    expect(md).toContain('# Acme ERP Configuration Plan');
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `Configuration Plan (custom adaptor) must not contain "${banned}"`).not.toContain(banned);
    }
  });
});
