import { describe, it, expect } from 'vitest';
import {
  generateImplementationPlanHtml,
  type ImplementationPlanData,
} from '../../../src/services/generators/planGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * Implementation plan adaptor-awareness tests (Phase 4 of generators-are-
 * adaptor-aware).
 *
 * The plan structure is platform-neutral — phases, milestones, roles,
 * risks, assumptions — so the refactor is mostly substitution: every
 * "NetSuite Admin / NetSuite Administrator / NetSuite Configuration /
 * NetSuite Implementation / NetSuite account" reference flexes via
 * adaptor.name. No gating needed.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<ImplementationPlanData> = {}): ImplementationPlanData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    license: { edition: 'MID_MARKET', modules: ['ADVANCED_REVENUE'] },
    answers: {
      'r2r.bankTransactions.hasOpeningBalances': true,
    },
    conflicts: [],
    ...overrides,
  };
}

describe('generateImplementationPlanHtml — NetSuite adaptor (preserves existing voice)', () => {
  const html = generateImplementationPlanHtml(baseData(NETSUITE_CTX));

  it('header badge reads NetSuite Implementation', () => {
    expect(html).toContain('NetSuite Implementation');
  });

  it('Phase 2 row reads "NetSuite Configuration" with NetSuite Admin owner', () => {
    expect(html).toContain('NetSuite Configuration');
    expect(html).toContain('NetSuite Admin');
  });

  it('Resource Plan lists a NetSuite Administrator', () => {
    expect(html).toContain('NetSuite Administrator');
  });

  it('Standard Assumptions mention provisioning the NetSuite account', () => {
    expect(html).toContain('NetSuite account will be provisioned');
  });

  it('Edition cell shows the NetSuite-prefixed edition label', () => {
    expect(html).toContain('NetSuite Mid-Market');
  });

  it('Footer reads ERPLaunch (no stale Ofoq NetSuite Accelerator)', () => {
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateImplementationPlanHtml — Odoo adaptor (new path)', () => {
  const html = generateImplementationPlanHtml(baseData(ODOO_CTX));

  it('header badge reads Odoo Implementation', () => {
    expect(html).toContain('Odoo Implementation');
  });

  it('Phase 2 row reads "Odoo Configuration" with Odoo Admin owner', () => {
    expect(html).toContain('Odoo Configuration');
    expect(html).toContain('Odoo Admin');
  });

  it('Resource Plan lists an Odoo Administrator', () => {
    expect(html).toContain('Odoo Administrator');
  });

  it('Standard Assumptions mention provisioning the Odoo account', () => {
    expect(html).toContain('Odoo account will be provisioned');
  });

  it('Edition cell shows the bare Odoo edition label', () => {
    expect(html).toContain('Enterprise');
    expect(html).not.toContain('NetSuite Enterprise');
  });

  it('Footer reads ERPLaunch (no stale Ofoq NetSuite Accelerator)', () => {
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(html, `Implementation Plan must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

// ─── Regression class: rendered prose contains wizard-answer content ─────────
describe('generateImplementationPlanHtml — Workstreams in Scope reads from adaptor.flows', () => {
  const ODOO_FLOWS = [
    {
      id: 'FOUNDATION',
      label: 'Project Foundation',
      description: 'Deployment, edition, geography.',
      sections: [
        {
          id: 'deployment',
          label: 'Deployment & Licensing',
          order: 1,
          questions: [
            { id: 'odoo.foundation.deploymentMode', label: 'Hosting & deployment mode', inputType: 'SINGLE_SELECT' as const,
              options: [{ value: 'ODOOSH', label: 'Odoo.sh' }] },
            { id: 'odoo.foundation.multiCompany', label: 'Multi-company in scope', inputType: 'BOOLEAN' as const },
            { id: 'odoo.foundation.multiCurrency', label: 'Multi-currency operations', inputType: 'BOOLEAN' as const },
          ],
        },
      ],
    },
    {
      id: 'TAX',
      label: 'Tax Engine',
      description: 'Tax behavior, defaults, fiscal positions.',
      sections: [
        {
          id: 'behavior',
          label: 'Default Tax Behavior',
          order: 1,
          questions: [
            { id: 'odoo.tax.defaultSalesTax', label: 'Default Sales Tax', inputType: 'TEXT' as const },
          ],
        },
      ],
    },
  ];

  it('Odoo plan renders Workstreams in Scope listing Project Foundation + Tax Engine', () => {
    const html = generateImplementationPlanHtml(baseData(
      { ...ODOO_CTX, flows: ODOO_FLOWS },
      {
        answers: {
          'odoo.foundation.deploymentMode': 'ODOOSH',
          'odoo.foundation.multiCompany': true,
          'odoo.foundation.multiCurrency': true,
          'odoo.tax.defaultSalesTax': 'VAT 5%',
        },
      },
    ));
    expect(html).toContain('Workstreams in Scope');
    expect(html).toContain('Project Foundation');
    expect(html).toContain('Tax Engine');
  });

  it('Odoo plan turns on Phase 4 Integration Setup when multiCurrency=true (schema-aware match)', () => {
    const html = generateImplementationPlanHtml(baseData(
      { ...ODOO_CTX, flows: ODOO_FLOWS },
      {
        answers: {
          'odoo.foundation.multiCurrency': true,
          'odoo.tax.defaultSalesTax': 'VAT 5%',
        },
      },
    ));
    expect(html).toContain('Integration Setup');
    expect(html).toContain('Integration Developer');
  });

  it('NetSuite plan still detects Data Migration via the legacy hardcoded key (regression guard)', () => {
    const html = generateImplementationPlanHtml(baseData(NETSUITE_CTX, {
      answers: { 'r2r.bankTransactions.hasOpeningBalances': true },
    }));
    expect(html).toContain('Data Migration');
  });
});

// ─── Cutover Plan section (closes p4.cutover-references-in-plan harness gap) ─
describe('generateImplementationPlanHtml — Cutover Plan section', () => {
  it('NetSuite plan always includes a "Cutover Plan" heading (TBD when no migration answers)', () => {
    const html = generateImplementationPlanHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('Cutover Plan');
    expect(html).toContain('the NetSuite cutover');
    // No migration answers → all values default to TBD
    expect(html).toContain('TBD');
  });

  it('Odoo plan always includes a "Cutover Plan" heading even with no migration answers', () => {
    const html = generateImplementationPlanHtml(baseData(ODOO_CTX, { answers: {} }));
    expect(html).toContain('Cutover Plan');
    expect(html).toContain('the Odoo cutover');
  });

  it('Odoo plan reads cutoverStyle / preFreezeDays / cutoverWindowHours from Pack 7 migration answers', () => {
    const html = generateImplementationPlanHtml(baseData(ODOO_CTX, {
      answers: {
        'odoo.migration.cutoverStyle': 'BIG_BANG',
        'odoo.migration.preFreezeDays': 3,
        'odoo.migration.cutoverWindowHours': 36,
      },
    }));
    expect(html).toContain('Cutover Plan');
    expect(html).toContain('Big bang');
    expect(html).toContain('3 day(s)');
    expect(html).toContain('36 hour(s)');
  });

  it('Odoo plan surfaces parallelRunDays only when cutoverStyle = PARALLEL_RUN', () => {
    const parallel = generateImplementationPlanHtml(baseData(ODOO_CTX, {
      answers: {
        'odoo.migration.cutoverStyle': 'PARALLEL_RUN',
        'odoo.migration.parallelRunDays': 14,
        'odoo.migration.preFreezeDays': 1,
        'odoo.migration.cutoverWindowHours': 8,
      },
    }));
    expect(parallel).toContain('Parallel run');
    expect(parallel).toContain('Parallel-run duration');
    expect(parallel).toContain('14 day(s)');

    // BIG_BANG should NOT render the parallel-run row
    const bigBang = generateImplementationPlanHtml(baseData(ODOO_CTX, {
      answers: { 'odoo.migration.cutoverStyle': 'BIG_BANG' },
    }));
    expect(bigBang).not.toContain('Parallel-run duration');
  });

  it('Custom adaptor cutover prose flexes via adaptor.name', () => {
    const html = generateImplementationPlanHtml(baseData(CUSTOM_CTX));
    expect(html).toContain('Cutover Plan');
    expect(html).toContain('the Acme ERP cutover');
    expect(html).not.toContain('the NetSuite cutover');
    expect(html).not.toContain('the Odoo cutover');
  });

  it('Cutover dependencies row reflects open risk count when conflicts present', () => {
    const html = generateImplementationPlanHtml(baseData(NETSUITE_CTX, {
      conflicts: [
        { severity: 'BLOCK', message: 'Missing GL', resolution: 'Define GL' },
        { severity: 'WARN', message: 'No multi-currency', resolution: 'Add MC' },
      ],
    }));
    expect(html).toMatch(/2 open risk\(s\) tracked/);
  });
});

describe('generateImplementationPlanHtml — custom adaptor (fall-through default)', () => {
  it('renders Acme ERP-flavored prose with no NetSuite leak', () => {
    const html = generateImplementationPlanHtml(baseData(CUSTOM_CTX));
    expect(html).toContain('Acme ERP Implementation');
    expect(html).toContain('Acme ERP Configuration');
    expect(html).toContain('Acme ERP Administrator');
    expect(html).not.toContain('NetSuite');
    expect(html).not.toContain('SuiteScript');
    expect(html).not.toContain('SDF');
  });
});
