import { describe, it, expect } from 'vitest';
import {
  generateImplementationPlanHtml,
  type ImplementationPlanData,
} from '../../../src/services/generators/planGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * Implementation plan adaptor-awareness tests (Phase 4 of generators-are-
 * adaptor-aware).
 *
 * The plan structure is platform-neutral — phases, milestones, roles,
 * risks, assumptions — so the refactor is mostly substitution: every
 * "NetSuite Admin / NetSuite Administrator / NetSuite Configuration /
 * NetSuite Implementation / NetSuite account" reference flexes via
 * adaptor.name. No gating needed.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<ImplementationPlanData> = {}): ImplementationPlanData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    license: { edition: 'MID_MARKET', modules: ['ADVANCED_REVENUE'] },
    answers: {
      'r2r.bankTransactions.hasOpeningBalances': true,
    },
    conflicts: [],
    ...overrides,
  };
}

describe('generateImplementationPlanHtml — NetSuite adaptor (preserves existing voice)', () => {
  const html = generateImplementationPlanHtml(baseData(NETSUITE_CTX));

  it('header badge reads NetSuite Implementation', () => {
    expect(html).toContain('NetSuite Implementation');
  });

  it('Phase 2 row reads "NetSuite Configuration" with NetSuite Admin owner', () => {
    expect(html).toContain('NetSuite Configuration');
    expect(html).toContain('NetSuite Admin');
  });

  it('Resource Plan lists a NetSuite Administrator', () => {
    expect(html).toContain('NetSuite Administrator');
  });

  it('Standard Assumptions mention provisioning the NetSuite account', () => {
    expect(html).toContain('NetSuite account will be provisioned');
  });

  it('Edition cell shows the NetSuite-prefixed edition label', () => {
    expect(html).toContain('NetSuite Mid-Market');
  });

  it('Footer reads ERPLaunch (no stale Ofoq NetSuite Accelerator)', () => {
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateImplementationPlanHtml — Odoo adaptor (new path)', () => {
  const html = generateImplementationPlanHtml(baseData(ODOO_CTX));

  it('header badge reads Odoo Implementation', () => {
    expect(html).toContain('Odoo Implementation');
  });

  it('Phase 2 row reads "Odoo Configuration" with Odoo Admin owner', () => {
    expect(html).toContain('Odoo Configuration');
    expect(html).toContain('Odoo Admin');
  });

  it('Resource Plan lists an Odoo Administrator', () => {
    expect(html).toContain('Odoo Administrator');
  });

  it('Standard Assumptions mention provisioning the Odoo account', () => {
    expect(html).toContain('Odoo account will be provisioned');
  });

  it('Edition cell shows the bare Odoo edition label', () => {
    expect(html).toContain('Enterprise');
    expect(html).not.toContain('NetSuite Enterprise');
  });

  it('Footer reads ERPLaunch (no stale Ofoq NetSuite Accelerator)', () => {
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(html, `Implementation Plan must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

describe('generateImplementationPlanHtml — custom adaptor (fall-through default)', () => {
  it('renders Acme ERP-flavored prose with no NetSuite leak', () => {
    const html = generateImplementationPlanHtml(baseData(CUSTOM_CTX));
    expect(html).toContain('Acme ERP Implementation');
    expect(html).toContain('Acme ERP Configuration');
    expect(html).toContain('Acme ERP Administrator');
    expect(html).not.toContain('NetSuite');
    expect(html).not.toContain('SuiteScript');
    expect(html).not.toContain('SDF');
  });
});
