import { describe, it, expect } from 'vitest';
import { generateScripts } from '../../../src/services/generators/scriptGenerator.js';
import { generateSolutionDoc } from '../../../src/services/generators/solutionDocGenerator.js';

/**
 * Phase 6 — workflow XML dropped; approval flow described in Solution Design
 * prose instead. Oracle guidance is explicit: hand-writing workflow XML
 * uses a SOAP webservices namespace that SDF rejects, plus a
 * <sendemailaction> shape Oracle warns against. Author workflows in the
 * NetSuite UI and export them via SDF — don't write them from scratch.
 */

/**
 * Phase 7 — every generated .js file starts with a prominent banner that
 * warns the deploying developer these files are scaffolding only. The
 * banner text is pinned byte-for-byte: any edit must land in this test
 * plus the generator, which is the signal we want for a regression.
 */
const STARTER_BANNER = `/**
 * ⚠ STARTER SCAFFOLDING — NOT A WORKING IMPLEMENTATION
 * The handler bodies below are intentionally empty. A NetSuite
 * developer must implement the logic before this file is deployed.
 */`;

describe('scriptGenerator: Fix #7 — STARTER SCAFFOLDING banner on every generated .js', () => {
  it('prepends the banner to every .js file in the bundle', () => {
    const files = generateScripts({
      clientName: 'Aurora Foods',
      modules: [],
      answers: {
        'p2p.purchasing.poApprovalRequired': true,
        'p2p.bills.billApprovalRequired': true,
        'o2c.salesOrders.soApprovalRequired': true,
        'r2r.currencies.isMultiCurrency': true,
      },
    });
    const jsFiles = Object.entries(files).filter(([k]) => k.endsWith('.js'));
    expect(jsFiles.length, 'expected at least one .js file in the scaffold bundle').toBeGreaterThan(0);
    for (const [name, body] of jsFiles) {
      expect(body.startsWith(STARTER_BANNER), `${name} does not start with the STARTER SCAFFOLDING banner`).toBe(true);
    }
  });

  it('banner appears exactly once per file (no double-prepend)', () => {
    const files = generateScripts({ clientName: 'Aurora Foods', modules: [], answers: {} });
    for (const [name, body] of Object.entries(files)) {
      if (!name.endsWith('.js')) continue;
      const occurrences = body.split('STARTER SCAFFOLDING').length - 1;
      expect(occurrences, `${name} has the banner marker ${occurrences} times, expected 1`).toBe(1);
    }
  });
});

describe('scriptGenerator: Fix #6 — no hand-written workflow XML is emitted', () => {
  it('never emits NSIX_WF_ApprovalChain.xml even when bill + PO approval triggers fire', () => {
    const files = generateScripts({
      clientName: 'Aurora Foods',
      modules: [],
      answers: {
        'p2p.bills.billApprovalRequired': true,
        'p2p.purchasing.poApprovalRequired': true,
      },
    });
    // Any .xml file in the script bundle was always the workflow file —
    // the script bundle should be pure .js going forward.
    const xmlFiles = Object.keys(files).filter((k) => /\.xml$/i.test(k));
    expect(xmlFiles, 'script generator should emit no XML files').toEqual([]);
    expect(files['NSIX_WF_ApprovalChain.xml']).toBeUndefined();
  });
});

describe('solutionDocGenerator: Fix #6 — approval workflow described in prose', () => {
  // Phase 21+ — solutionDoc is adaptor-aware. The Approval Workflows block is
  // NetSuite-specific (it talks about UI authoring + suitecloud export), so
  // every test in this describe pins the adaptor to NetSuite to preserve
  // the existing assertion semantics.
  const NETSUITE_CTX = {
    id: 'netsuite',
    name: 'NetSuite',
    editionLabel: 'NetSuite Starter',
    consultantQualifier: 'NetSuite',
    nextStepLanguage:
      'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
  };

  it('adds an Approval Workflows section when PO approval is required', () => {
    const doc = generateSolutionDoc({
      clientName: 'Aurora Foods',
      adaptor: NETSUITE_CTX,
      license: { edition: 'STARTER', modules: [] },
      answers: { 'p2p.purchasing.poApprovalRequired': true },
      conflicts: [],
    });
    // The heading surfaces the topic; the body explains why the
    // consultant must build this in the UI rather than shipping XML.
    // Heading may carry section numbering like "4.3" between ### and the title.
    expect(doc).toMatch(/##+\s+(\d+\.\d+\s+)?Approval Workflows/);
    expect(doc).toMatch(/NetSuite UI|author(ed)? in the UI/i);
    expect(doc).toMatch(/PO approval|purchase order/i);
  });

  it('adds the section when bill approval is required even if PO approval is off', () => {
    const doc = generateSolutionDoc({
      clientName: 'Aurora Foods',
      adaptor: NETSUITE_CTX,
      license: { edition: 'STARTER', modules: [] },
      answers: { 'p2p.bills.billApprovalRequired': true },
      conflicts: [],
    });
    // Heading may carry section numbering like "4.3" between ### and the title.
    expect(doc).toMatch(/##+\s+(\d+\.\d+\s+)?Approval Workflows/);
    expect(doc).toMatch(/bill approval|vendor bill/i);
  });

  it('omits the Approval Workflows section entirely when no approval triggers fire', () => {
    const doc = generateSolutionDoc({
      clientName: 'Aurora Foods',
      adaptor: NETSUITE_CTX,
      license: { edition: 'STARTER', modules: [] },
      answers: {},
      conflicts: [],
    });
    expect(doc).not.toMatch(/##+\s+(\d+\.\d+\s+)?Approval Workflows/);
  });
});
