import { describe, it, expect } from 'vitest';
import { generateWorkflowActionScripts } from '../../../src/services/generators/sdfWorkflowActionScriptGenerator.js';

/**
 * Pack W — Workflow Action Script generator tests.
 *
 * Pack contract:
 *   1. Per in-scope amount-tiered approval (PO/JE/VB), emit one
 *      SuiteScripts/NSIX_WFA_<TYPE>_Approval.js with @NScriptType
 *      WorkflowActionScript JSDoc + an APPROVAL_TIERS array parsed
 *      from the wizard tiers.
 *   2. Expense + SO approvals do NOT get WFA scripts (Expense uses
 *      standard supervisor chain; SO routing is inline VISUAL_BUILDER).
 *   3. Resolved mode (all tiers parse) → hardcoded array.
 *   4. Fallback mode (≥1 line fails OR empty answer) → TODO placeholder
 *      with verbatim wizard answer in a comment block.
 */

function assertParsesAsJs(script: string): void {
  // SuiteScript uses AMD's `define`; stub it so V8's parser can run
  // through the body without ReferenceError.
  const stubbed = `var define = function(){}; ${script}`;
  new Function(stubbed);
}

const BASE_INPUT = {
  firmName: 'NSIX',
  clientName: 'Atlas Industries Group',
};

// ─── Empty / scope-off ──────────────────────────────────────────────────────

describe('generateWorkflowActionScripts — empty / scope-off', () => {
  it('emits nothing when no approval scope flags are true', () => {
    const out = generateWorkflowActionScripts({ ...BASE_INPUT, answers: {} });
    expect(out.files).toEqual({});
    expect(out.emitted).toEqual([]);
  });

  it('does NOT emit a WFA script for Expense or SO (those don\'t need one)', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.expenseApprovalInScope': true,
        'ns.approvals.soApprovalInScope': true,
      },
    });
    expect(out.files).toEqual({});
  });
});

// ─── Per-type emission ──────────────────────────────────────────────────────

describe('generateWorkflowActionScripts — per-type emission', () => {
  it('PO scope true → emits SuiteScripts/NSIX_WFA_PO_Approval.js', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers': '<$5,000: auto-approve\n>$5,000: Manager',
      },
    });
    expect(out.files['SuiteScripts/NSIX_WFA_PO_Approval.js']).toBeDefined();
    expect(out.emitted[0].typeKey).toBe('po');
    expect(out.emitted[0].resolved).toBe(true);
  });

  it('JE scope true → emits SuiteScripts/NSIX_WFA_JE_Approval.js', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: { 'ns.approvals.jeApprovalInScope': true, 'ns.approvals.jeApprovalTiers': '<$10,000: auto-approve' },
    });
    expect(out.files['SuiteScripts/NSIX_WFA_JE_Approval.js']).toBeDefined();
  });

  it('VB scope true → emits SuiteScripts/NSIX_WFA_VB_Approval.js', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: { 'ns.approvals.vbApprovalInScope': true, 'ns.approvals.vbApprovalTiers': '<$5,000: auto-approve' },
    });
    expect(out.files['SuiteScripts/NSIX_WFA_VB_Approval.js']).toBeDefined();
  });

  it('all 3 scopes true → emits 3 scripts', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers': '<$5,000: auto-approve',
        'ns.approvals.jeApprovalInScope': true,
        'ns.approvals.jeApprovalTiers': '<$10,000: auto-approve',
        'ns.approvals.vbApprovalInScope': true,
        'ns.approvals.vbApprovalTiers': '<$5,000: auto-approve',
      },
    });
    expect(out.emitted).toHaveLength(3);
  });
});

// ─── JSDoc shape ────────────────────────────────────────────────────────────

describe('generateWorkflowActionScripts — JSDoc shape', () => {
  it('declares @NApiVersion 2.1 + @NScriptType WorkflowActionScript', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: { 'ns.approvals.poApprovalInScope': true, 'ns.approvals.poApprovalTiers': '<$5,000: auto-approve' },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toContain('@NApiVersion 2.1');
    expect(js).toContain('@NScriptType WorkflowActionScript');
    expect(js).toContain('@NModuleScope SameAccount');
  });

  it('credits firm + client in the header', () => {
    const out = generateWorkflowActionScripts({
      firmName: 'NSIX Implementation Partners',
      clientName: 'Brightside Pharmaceuticals Group',
      answers: { 'ns.approvals.poApprovalInScope': true, 'ns.approvals.poApprovalTiers': '<$5,000: auto-approve' },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toMatch(/Generated by ERPLaunch from NSIX Implementation Partners[^\n]*Brightside Pharmaceuticals Group/);
  });

  it('embeds the verbatim wizard answer in JSDoc', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers':
          '<$5,000: auto-approve\n>$50,000: CFO',
      },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toContain('<$5,000: auto-approve');
    expect(js).toContain('>$50,000: CFO');
  });

  it('script body exports an onAction function that returns the next approver', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: { 'ns.approvals.poApprovalInScope': true, 'ns.approvals.poApprovalTiers': '<$5,000: auto-approve' },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toContain('return { onAction }');
    expect(js).toContain('return tier.approver');
  });
});

// ─── Resolved-mode + fallback-mode ──────────────────────────────────────────

describe('generateWorkflowActionScripts — resolved + fallback', () => {
  it('resolved mode hardcodes the parsed tiers', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers':
          '<$5,000: auto-approve\n$5,000-$50,000: Department Manager\n>$50,000: CFO',
      },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toContain("label: '<$5,000'");
    expect(js).toContain("approver: 'auto'");
    expect(js).toContain("label: '$5,000-$50,000'");
    expect(js).toContain("approver: 'Department Manager'");
    expect(js).toContain("approver: 'CFO'");
    expect(js).not.toContain('TODO: parse failed');
  });

  it('fallback mode triggers when one line is unparseable', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers':
          '<$5,000: auto-approve\nthis is not parseable\n>$50,000: CFO',
      },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toContain('TODO: parse failed');
    expect(js).toContain('this is not parseable');
    expect(out.emitted[0].resolved).toBe(false);
  });

  it('fallback mode triggers when scope is true but tiers answer is empty', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: { 'ns.approvals.poApprovalInScope': true, 'ns.approvals.poApprovalTiers': '' },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).toContain('TODO');
    expect(out.emitted[0].resolved).toBe(false);
  });
});

// ─── JS-validity sanity ─────────────────────────────────────────────────────

describe('generateWorkflowActionScripts — JS validity', () => {
  it('resolved-mode script parses as valid JavaScript', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers':
          '<$5,000: auto-approve\n$5,000-$50,000: Department Manager',
      },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(() => assertParsesAsJs(js)).not.toThrow();
  });

  it('fallback-mode script parses as valid JavaScript', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: {
        'ns.approvals.poApprovalInScope': true,
        'ns.approvals.poApprovalTiers': 'unparseable line',
      },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(() => assertParsesAsJs(js)).not.toThrow();
  });

  it('does NOT carry the audit Fix #7 STARTER SCAFFOLDING banner', () => {
    const out = generateWorkflowActionScripts({
      ...BASE_INPUT,
      answers: { 'ns.approvals.poApprovalInScope': true, 'ns.approvals.poApprovalTiers': '<$5,000: auto-approve' },
    });
    const js = out.files['SuiteScripts/NSIX_WFA_PO_Approval.js'];
    expect(js).not.toContain('STARTER SCAFFOLDING');
    expect(js).not.toMatch(/this file is a scaffolding/i);
  });
});
