import { describe, it, expect } from 'vitest';
import {
  generateSolutionDoc,
  generateSolutionDocHtml,
  type SolutionDocData,
} from '../../../src/services/generators/solutionDocGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * SolutionDoc adaptor-awareness tests (Phase 2 of generators-are-adaptor-aware).
 *
 * Same shape as brdGenerator.test.ts — a NetSuite branch that preserves
 * the existing voice (incl. SDF + SuiteScript + Approval Workflows
 * sections that the platform actually has) and an Odoo branch that
 * proves the new path with the cross-platform banlist.
 *
 * Custom-adaptor branch proves the fall-through default doesn't
 * accidentally render any NetSuite-specific section.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<SolutionDocData> = {}): SolutionDocData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    license: { edition: 'MID_MARKET', modules: ['ADVANCED_REVENUE'] },
    answers: {
      'r2r.entities.multiEntity': true,
      'r2r.currencies.isMultiCurrency': true,
      'p2p.purchasing.poApprovalRequired': true,
    },
    conflicts: [],
    ...overrides,
  };
}

describe('generateSolutionDoc — NetSuite adaptor (preserves existing voice)', () => {
  const md = generateSolutionDoc(baseData(NETSUITE_CTX));

  it('uses the NetSuite-named title', () => {
    expect(md).toContain('# NetSuite Solution Design Document');
  });

  it('Document Control table shows the NetSuite edition label', () => {
    expect(md).toContain('| **License Edition** | NetSuite Mid-Market |');
  });

  it('Project Overview names NetSuite as the platform', () => {
    expect(md).toContain('configuration of NetSuite for **Aurora Foods**');
  });

  it('renders the NetSuite-specific Technical Specifications block (SDF + SuiteScript)', () => {
    expect(md).toContain('### 4.1 Custom Objects (SDF)');
    expect(md).toContain('### 4.2 SuiteScript Customisations');
  });

  it('renders the Approval Workflows block when PO approval is required', () => {
    expect(md).toContain('### 4.3 Approval Workflows');
  });

  it('uses the ERPLaunch byline (no stale Ofoq NetSuite Accelerator string)', () => {
    expect(md).toContain('| **Prepared By** | ERPLaunch |');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
    expect(md).not.toContain('Ofoq Accelerator');
  });

  it('Sign-off table names a NetSuite Project Manager + ERPLaunch Implementation Lead', () => {
    expect(md).toContain('NetSuite Project Manager');
    expect(md).toContain('Implementation Lead (ERPLaunch)');
  });

  it('HTML wrapper carries NetSuite Implementation badge + ERPLaunch footer', () => {
    const html = generateSolutionDocHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('NetSuite Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateSolutionDoc — Odoo adaptor (new path)', () => {
  const md = generateSolutionDoc(baseData(ODOO_CTX));

  it('uses the Odoo-named title', () => {
    expect(md).toContain('# Odoo Solution Design Document');
  });

  it('Document Control table shows the bare Odoo edition label', () => {
    expect(md).toContain('| **License Edition** | Enterprise |');
    expect(md).not.toContain('NetSuite Enterprise');
  });

  it('Project Overview names Odoo as the platform', () => {
    expect(md).toContain('configuration of Odoo for **Aurora Foods**');
  });

  it('does NOT render the NetSuite-specific Technical Specifications block', () => {
    expect(md).not.toContain('Custom Objects (SDF)');
    expect(md).not.toContain('SuiteScript Customisations');
    // Section heading order should still flow — the SDF/SuiteScript
    // section being skipped means Section 5 follows Section 3 directly,
    // OR a platform-neutral placeholder sits in 4. Either is fine; the
    // banlist below is the real contract.
  });

  it('does NOT render the NetSuite UI Approval Workflows block', () => {
    // The current voice references "NetSuite UI", "suitecloud object:import",
    // "SDF bundle". None of those should leak.
    expect(md).not.toContain('NetSuite UI');
    expect(md).not.toContain('suitecloud object:import');
    expect(md).not.toContain('SDF bundle');
  });

  it('Sign-off table names an Odoo Project Manager + ERPLaunch Implementation Lead', () => {
    expect(md).toContain('Odoo Project Manager');
    expect(md).toContain('Implementation Lead (ERPLaunch)');
    expect(md).not.toContain('NetSuite Project Manager');
  });

  it('uses the ERPLaunch byline (no stale Ofoq NetSuite Accelerator string)', () => {
    expect(md).toContain('| **Prepared By** | ERPLaunch |');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `Solution Design must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });

  it('HTML wrapper carries Odoo Implementation badge + ERPLaunch footer + no NetSuite leakage', () => {
    const html = generateSolutionDocHtml(baseData(ODOO_CTX));
    expect(html).toContain('Odoo Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
    for (const banned of ['SuiteScript', 'SDF', 'OneWorld', 'NetSuite']) {
      expect(html, `Solution Design HTML must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

describe('generateSolutionDoc — custom adaptor (fall-through default)', () => {
  const md = generateSolutionDoc(baseData(CUSTOM_CTX));

  it('renders Acme ERP-flavored prose with no NetSuite leak', () => {
    expect(md).toContain('# Acme ERP Solution Design Document');
    expect(md).toContain('configuration of Acme ERP for');
    expect(md).toContain('Acme ERP Project Manager');
    expect(md).not.toContain('NetSuite');
    expect(md).not.toContain('SuiteScript');
    expect(md).not.toContain('SDF');
  });
});
