import { describe, it, expect } from 'vitest';
import {
  generateSolutionDoc,
  generateSolutionDocHtml,
  type SolutionDocData,
} from '../../../src/services/generators/solutionDocGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * SolutionDoc adaptor-awareness tests (Phase 2 of generators-are-adaptor-aware).
 *
 * Same shape as brdGenerator.test.ts — a NetSuite branch that preserves
 * the existing voice (incl. SDF + SuiteScript + Approval Workflows
 * sections that the platform actually has) and an Odoo branch that
 * proves the new path with the cross-platform banlist.
 *
 * Custom-adaptor branch proves the fall-through default doesn't
 * accidentally render any NetSuite-specific section.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<SolutionDocData> = {}): SolutionDocData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    license: { edition: 'MID_MARKET', modules: ['ADVANCED_REVENUE'] },
    answers: {
      'r2r.entities.multiEntity': true,
      'r2r.currencies.isMultiCurrency': true,
      'p2p.purchasing.poApprovalRequired': true,
    },
    conflicts: [],
    ...overrides,
  };
}

describe('generateSolutionDoc — NetSuite adaptor (preserves existing voice)', () => {
  const md = generateSolutionDoc(baseData(NETSUITE_CTX));

  it('uses the NetSuite-named title', () => {
    expect(md).toContain('# NetSuite Solution Design Document');
  });

  it('Document Control table shows the NetSuite edition label', () => {
    expect(md).toContain('| **License Edition** | NetSuite Mid-Market |');
  });

  it('Project Overview names NetSuite as the platform', () => {
    expect(md).toContain('configuration of NetSuite for **Aurora Foods**');
  });

  it('renders the NetSuite-specific Technical Specifications block (SDF + SuiteScript)', () => {
    expect(md).toContain('### 4.1 Custom Objects (SDF)');
    expect(md).toContain('### 4.2 SuiteScript Customisations');
  });

  it('renders the Approval Workflows block when PO approval is required', () => {
    expect(md).toContain('### 4.3 Approval Workflows');
  });

  it('uses the ERPLaunch byline (no stale Ofoq NetSuite Accelerator string)', () => {
    expect(md).toContain('| **Prepared By** | ERPLaunch |');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
    expect(md).not.toContain('Ofoq Accelerator');
  });

  it('Sign-off table names a NetSuite Project Manager + ERPLaunch Implementation Lead', () => {
    expect(md).toContain('NetSuite Project Manager');
    expect(md).toContain('Implementation Lead (ERPLaunch)');
  });

  it('HTML wrapper carries NetSuite Implementation badge + ERPLaunch footer', () => {
    const html = generateSolutionDocHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('NetSuite Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateSolutionDoc — Odoo adaptor (new path)', () => {
  const md = generateSolutionDoc(baseData(ODOO_CTX));

  it('uses the Odoo-named title', () => {
    expect(md).toContain('# Odoo Solution Design Document');
  });

  it('Document Control table shows the bare Odoo edition label', () => {
    expect(md).toContain('| **License Edition** | Enterprise |');
    expect(md).not.toContain('NetSuite Enterprise');
  });

  it('Project Overview names Odoo as the platform', () => {
    expect(md).toContain('configuration of Odoo for **Aurora Foods**');
  });

  it('does NOT render the NetSuite-specific Technical Specifications block', () => {
    expect(md).not.toContain('Custom Objects (SDF)');
    expect(md).not.toContain('SuiteScript Customisations');
    // Section heading order should still flow — the SDF/SuiteScript
    // section being skipped means Section 5 follows Section 3 directly,
    // OR a platform-neutral placeholder sits in 4. Either is fine; the
    // banlist below is the real contract.
  });

  it('does NOT render the NetSuite UI Approval Workflows block', () => {
    // The current voice references "NetSuite UI", "suitecloud object:import",
    // "SDF bundle". None of those should leak.
    expect(md).not.toContain('NetSuite UI');
    expect(md).not.toContain('suitecloud object:import');
    expect(md).not.toContain('SDF bundle');
  });

  it('Sign-off table names an Odoo Project Manager + ERPLaunch Implementation Lead', () => {
    expect(md).toContain('Odoo Project Manager');
    expect(md).toContain('Implementation Lead (ERPLaunch)');
    expect(md).not.toContain('NetSuite Project Manager');
  });

  it('uses the ERPLaunch byline (no stale Ofoq NetSuite Accelerator string)', () => {
    expect(md).toContain('| **Prepared By** | ERPLaunch |');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `Solution Design must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });

  it('HTML wrapper carries Odoo Implementation badge + ERPLaunch footer + no NetSuite leakage', () => {
    const html = generateSolutionDocHtml(baseData(ODOO_CTX));
    expect(html).toContain('Odoo Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
    for (const banned of ['SuiteScript', 'SDF', 'OneWorld', 'NetSuite']) {
      expect(html, `Solution Design HTML must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

// ─── Regression class: rendered prose contains wizard-answer content ─────────
describe('generateSolutionDoc — workstream loop reads from adaptor.flows (regression class)', () => {
  const ODOO_FLOWS = [
    {
      id: 'FOUNDATION',
      label: 'Project Foundation',
      description: 'Deployment, edition, geography, entity structure.',
      sections: [
        {
          id: 'deployment',
          label: 'Deployment & Licensing',
          order: 1,
          questions: [
            {
              id: 'odoo.foundation.deploymentMode',
              label: 'Hosting & deployment mode',
              inputType: 'SINGLE_SELECT' as const,
              options: [
                { value: 'ODOOSH', label: 'Odoo.sh' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'TAX',
      label: 'Tax Engine',
      description: 'Tax behavior, defaults, fiscal positions.',
      sections: [
        {
          id: 'behavior',
          label: 'Default Tax Behavior',
          order: 1,
          questions: [
            {
              id: 'odoo.tax.defaultSalesTax',
              label: 'Default Sales Tax (rate name + percent)',
              inputType: 'TEXT' as const,
            },
          ],
        },
      ],
    },
  ];

  const ODOO_CTX_WITH_FLOWS = { ...ODOO_CTX, flows: ODOO_FLOWS };

  it('Odoo SDD lists Project Foundation + Tax Engine in Scope of Implementation', () => {
    const md = generateSolutionDoc(baseData(ODOO_CTX_WITH_FLOWS, {
      answers: {
        'odoo.foundation.deploymentMode': 'ODOOSH',
        'odoo.tax.defaultSalesTax': 'VAT 5%',
      },
    }));
    expect(md).toContain('Project Foundation');
    expect(md).toContain('Tax Engine');
  });

  it('Odoo SDD Workstream Configuration Design contains question label + answer', () => {
    const md = generateSolutionDoc(baseData(ODOO_CTX_WITH_FLOWS, {
      answers: {
        'odoo.foundation.deploymentMode': 'ODOOSH',
        'odoo.tax.defaultSalesTax': 'VAT 5%',
      },
    }));
    expect(md).toContain('Hosting & deployment mode');
    expect(md).toContain('Odoo.sh');
    expect(md).toContain('Default Sales Tax');
    expect(md).toContain('VAT 5%');
  });

  it('NetSuite SDD still renders the hardcoded R2R / P2P blocks (regression guard)', () => {
    // The existing NetSuite-specific blocks (Bank & Treasury, Period Close,
    // PO/SO/Bill approval tables) live behind the isNetSuite gate and
    // should still render verbatim for NetSuite engagements.
    const md = generateSolutionDoc(baseData(NETSUITE_CTX, {
      answers: {
        'r2r.bankTransactions.bankAccountCount': 4,
        'r2r.fiscalClose.hardClose': true,
        'p2p.purchasing.usePurchaseOrders': true,
        'o2c.customers.creditLimits': true,
      },
    }));
    expect(md).toMatch(/Record to Report \(R2R\)/);
    expect(md).toContain('Bank & Treasury');
    expect(md).toContain('Procure to Pay (P2P)');
    expect(md).toContain('Formal Purchase Orders');
    expect(md).toContain('Order to Cash (O2C)');
    expect(md).toContain('Customer Credit Limits');
  });
});

describe('generateSolutionDoc — custom adaptor (fall-through default)', () => {
  const md = generateSolutionDoc(baseData(CUSTOM_CTX));

  it('renders Acme ERP-flavored prose with no NetSuite leak', () => {
    expect(md).toContain('# Acme ERP Solution Design Document');
    expect(md).toContain('configuration of Acme ERP for');
    expect(md).toContain('Acme ERP Project Manager');
    expect(md).not.toContain('NetSuite');
    expect(md).not.toContain('SuiteScript');
    expect(md).not.toContain('SDF');
  });
});

// ─── Phase 41.1 — Section 5 Roles: drop the duplicate canonical table
// when the engagement has captured Phase 25 structured roles. The old
// behaviour rendered a generic Finance Manager / Procurement Manager /
// Sales Manager table on every doc regardless of what the consultant
// captured, which read identically across clients and competed with
// the structured roles section for "here are the roles" attention.

describe('generateSolutionDoc — Phase 41.1 canonical roles suppression', () => {
  it('renders the canonical Finance Manager / Procurement Manager table when no structured roles exist', () => {
    const md = generateSolutionDoc(baseData(NETSUITE_CTX));
    expect(md).toContain('### 5.1 Canonical Roles (reference)');
    expect(md).toContain('| Finance Manager |');
    expect(md).toContain('| Procurement Manager |');
    expect(md).toContain('| Sales Manager |');
  });

  it('suppresses the canonical table when structured roles are captured', () => {
    const md = generateSolutionDoc(
      baseData(NETSUITE_CTX, {
        answers: {
          'r2r.entities.multiEntity': true,
          'p2p.purchasing.poApprovalRequired': true,
          // Phase 25 structured roles — minimal valid payload.
          'ns.design.standardRolesStructured': JSON.stringify([
            { name: 'AR Clerk', centerOverride: null, restrictionOverride: null, customizationNotes: '' },
          ]),
        },
      }),
    );
    expect(md).not.toContain('### 5.1 Canonical Roles (reference)');
    // The canonical role table rows should be gone (the role names
    // can still appear elsewhere in the doc — e.g. the Approval
    // Workflows section legitimately mentions "Procurement Manager"
    // as the routing target — so we only assert the table-row prefixes
    // here, not the bare role names.
    expect(md).not.toContain('| Finance Manager | R2R, P2P |');
    expect(md).not.toContain('| Procurement Manager | P2P |');
    expect(md).not.toContain('| Sales Manager | O2C |');
    // The structured-roles section takes 5.1.
    expect(md).toContain('### 5.1 Captured Custom Roles (Phase 25 structured editor)');
    expect(md).toContain('| AR Clerk |');
  });

  it('preserves section numbering when both structured roles and templates exist', () => {
    const md = generateSolutionDoc(
      baseData(NETSUITE_CTX, {
        answers: {
          'r2r.entities.multiEntity': true,
          'ns.design.standardRolesStructured': JSON.stringify([
            { name: 'AR Clerk', centerOverride: null, restrictionOverride: null, customizationNotes: '' },
          ]),
          'ns.design.templatesStructured': JSON.stringify([
            { name: 'Invoice Template', kind: 'PDF', preferred: true, sections: ['header', 'lines'], notes: '' },
          ]),
        },
      }),
    );
    // Roles = 5.1, Templates = 5.2 (no gap).
    expect(md).toContain('### 5.1 Captured Custom Roles');
    expect(md).toContain('### 5.2 Custom Templates');
    expect(md).not.toContain('### 5.3 Custom Templates');
  });
});
