import { describe, it, expect } from 'vitest';
import {
  generateTrainingManual,
  generateTrainingManualHtml,
  type TrainingManualData,
} from '../../../src/services/generators/trainingManualGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * Training manual adaptor-awareness tests (Phase 3 of generators-are-
 * adaptor-aware).
 *
 * The detailed step-by-step training modules in this generator are
 * deeply NetSuite-specific (menu paths, transaction names, subsidiary
 * journal entries). For non-NetSuite adaptors we don't try to localise
 * those steps — that's a separate per-adaptor training generator. We
 * gate the NetSuite modules behind adaptor.id === 'netsuite' and emit
 * a platform-neutral placeholder for other adaptors.
 *
 * The cross-platform contract is: shell text (title, byline, footer,
 * intro) flexes per adaptor; module bodies are NetSuite-only for now;
 * banlist enforced for non-NetSuite branch.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<TrainingManualData> = {}): TrainingManualData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    answers: {
      'r2r.entities.multiEntity': true,
      'p2p.purchasing.usePurchaseOrders': true,
      'o2c.salesOrders.requiresApproval': true,
    },
    ...overrides,
  };
}

describe('generateTrainingManual — NetSuite adaptor (preserves existing voice)', () => {
  const md = generateTrainingManual(baseData(NETSUITE_CTX));

  it('uses the NetSuite-named title', () => {
    expect(md).toContain('# NetSuite Training Manual');
  });

  it('byline reads ERPLaunch (no stale Ofoq NetSuite Accelerator)', () => {
    expect(md).toContain('**Prepared by:** ERPLaunch');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('intro mentions NetSuite as the platform', () => {
    expect(md).toMatch(/NetSuite (discovery|design|Sandbox)/);
  });

  it('renders the NetSuite step-by-step modules (Quick Reference + nav paths)', () => {
    expect(md).toContain('| Task | NetSuite Path |');
    expect(md).toContain('Transactions > Financial > Make Journal Entries');
  });

  it('HTML wrapper carries NetSuite Implementation badge + ERPLaunch footer', () => {
    const html = generateTrainingManualHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('NetSuite Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateTrainingManual — Odoo adaptor (new path)', () => {
  const md = generateTrainingManual(baseData(ODOO_CTX));

  it('uses the Odoo-named title', () => {
    expect(md).toContain('# Odoo Training Manual');
  });

  it('byline reads ERPLaunch', () => {
    expect(md).toContain('**Prepared by:** ERPLaunch');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('intro names Odoo as the platform', () => {
    expect(md).toContain('Odoo');
  });

  it('does NOT render the NetSuite step-by-step modules or Quick Reference card', () => {
    expect(md).not.toContain('NetSuite Path');
    expect(md).not.toContain('Transactions > Financial');
    expect(md).not.toContain('Transactions > Sales');
  });

  it('emits a platform-neutral placeholder pointing at Odoo-specific training', () => {
    // The exact wording is flexible; the contract is the document
    // acknowledges that adaptor-specific training lives elsewhere
    // until the per-adaptor training generator lands.
    expect(md).toMatch(/Odoo[\s\S]{0,200}training/i);
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `Training Manual must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });

  it('HTML wrapper carries Odoo Implementation badge + ERPLaunch footer + no NetSuite leakage', () => {
    const html = generateTrainingManualHtml(baseData(ODOO_CTX));
    expect(html).toContain('Odoo Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
    for (const banned of ['SuiteScript', 'SDF', 'OneWorld', 'NetSuite']) {
      expect(html, `Training Manual HTML must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

// ─── Regression class: rendered prose contains wizard-answer content ─────────
describe('generateTrainingManual — non-NetSuite Wizard Configuration Summary walks adaptor.flows', () => {
  const ODOO_FLOWS = [
    {
      id: 'FOUNDATION',
      label: 'Project Foundation',
      description: 'Deployment, edition, geography.',
      sections: [
        {
          id: 'deployment',
          label: 'Deployment & Licensing',
          order: 1,
          questions: [
            {
              id: 'odoo.foundation.deploymentMode',
              label: 'Hosting & deployment mode',
              inputType: 'SINGLE_SELECT' as const,
              options: [{ value: 'ODOOSH', label: 'Odoo.sh' }],
            },
          ],
        },
      ],
    },
    {
      id: 'TAX',
      label: 'Tax Engine',
      description: 'Tax behavior, defaults, fiscal positions.',
      sections: [
        {
          id: 'behavior',
          label: 'Default Tax Behavior',
          order: 1,
          questions: [
            {
              id: 'odoo.tax.defaultSalesTax',
              label: 'Default Sales Tax',
              inputType: 'TEXT' as const,
            },
          ],
        },
      ],
    },
  ];

  it('Odoo training manual contains Project Foundation + Tax Engine + question labels + answer text', () => {
    const md = generateTrainingManual(baseData(
      { ...ODOO_CTX, flows: ODOO_FLOWS },
      {
        answers: {
          'odoo.foundation.deploymentMode': 'ODOOSH',
          'odoo.tax.defaultSalesTax': 'VAT 5%',
        },
      },
    ));
    expect(md).toContain('Wizard Configuration Summary');
    expect(md).toContain('Project Foundation');
    expect(md).toContain('Tax Engine');
    expect(md).toContain('Hosting & deployment mode');
    expect(md).toContain('Odoo.sh');
    expect(md).toContain('Default Sales Tax');
    expect(md).toContain('VAT 5%');
  });

  it('NetSuite training manual still renders the hardcoded Quick Reference Card (regression guard)', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX, {
      answers: {
        'p2p.purchasing.usePurchaseOrders': true,
        'o2c.salesOrders.requiresApproval': true,
      },
    }));
    expect(md).toContain('# NetSuite Training Manual');
    expect(md).toContain('Quick Reference Card');
    expect(md).toContain('Transactions > Purchases > Enter Purchase Orders');
  });
});

describe('generateTrainingManual — custom adaptor (fall-through default)', () => {
  it('renders Acme ERP-flavored shell with no NetSuite leak', () => {
    const md = generateTrainingManual(baseData(CUSTOM_CTX));
    expect(md).toContain('# Acme ERP Training Manual');
    expect(md).not.toContain('NetSuite');
    expect(md).not.toContain('SuiteScript');
    expect(md).not.toContain('SDF');
  });
});

// ─── Pack U — cross-ref index sections ──────────────────────────────────────

describe('generateTrainingManual — Pack U cross-ref index sections', () => {
  it('renders the "Pack U Index — Role-Targeted Starting Points" section', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX));
    expect(md).toContain('## Pack U Index — Role-Targeted Starting Points');
  });

  it('cross-refs per-role training guide path', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX));
    expect(md).toContain('Documentation/Training/<Role_Slug>_Training_Guide.md');
  });

  it('cross-refs Quick_Reference_Cards directory + naming convention', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX));
    expect(md).toContain('Documentation/Training/Quick_Reference_Cards/');
    expect(md).toContain('QRC-<task-slug>.md');
  });

  it('cross-refs Training_Matrix.md + its purpose framing', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX));
    expect(md).toContain('Documentation/Training_Matrix.md');
    expect(md).toContain('Required / View / N/A');
  });

  it('cross-refs Training_Schedule.md + auto-stagger description', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX));
    expect(md).toContain('Documentation/Training_Schedule.md');
    expect(md).toContain('4 weeks pre-go-live');
  });

  it('cross-refs KT_Checklist.md + the BAU transition framing', () => {
    const md = generateTrainingManual(baseData(NETSUITE_CTX));
    expect(md).toContain('Documentation/KT_Checklist.md');
    expect(md).toContain('go-live + 30 days');
  });

  it('Odoo training manual still emits Pack U index section without NetSuite-banlist leak', () => {
    const md = generateTrainingManual(baseData(ODOO_CTX));
    expect(md).toContain('## Pack U Index');
    expect(md).toContain('Documentation/Training/<Role_Slug>_Training_Guide.md');
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `Pack U index must not leak "${banned}" on Odoo`).not.toContain(banned);
    }
  });
});
