import { describe, it, expect } from 'vitest';
import {
  generateUATPlan,
  generateUATPlanHtml,
  type UATData,
} from '../../../src/services/generators/uatGenerator.js';
import type { AdaptorContext } from '../../../src/services/generators/brdGenerator.js';

/**
 * UAT plan adaptor-awareness tests (Phase 5 — final generator of the
 * cross-platform fix).
 *
 * Smallest of the five generators (3 NetSuite refs in source). The test
 * cases inside the UAT plan are derived from wizard answers and are
 * platform-neutral (e.g. "Create a Purchase Order"). Only the shell
 * — byline, intro, "${platform} Implementation" subtitle, footer —
 * needs to flex.
 */

const NETSUITE_CTX: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite Mid-Market',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
};

const ODOO_CTX: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
};

const CUSTOM_CTX: AdaptorContext = {
  id: 'custom:acme-erp',
  name: 'Acme ERP',
  editionLabel: 'Standard',
  consultantQualifier: 'Acme ERP',
  nextStepLanguage:
    'the Acme ERP build phase using the configuration package generated by ERPLaunch',
};

function baseData(adaptor: AdaptorContext, overrides: Partial<UATData> = {}): UATData {
  return {
    clientName: 'Aurora Foods',
    adaptor,
    answers: {
      'p2p.purchasing.usePurchaseOrders': true,
      'r2r.entities.multiEntity': true,
    },
    ...overrides,
  };
}

describe('generateUATPlan — NetSuite adaptor (preserves existing voice)', () => {
  const md = generateUATPlan(baseData(NETSUITE_CTX));

  it('byline reads ERPLaunch (no stale Ofoq NetSuite Accelerator)', () => {
    expect(md).toContain('**Prepared by:** ERPLaunch');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('HTML wrapper subtitle reads "NetSuite Implementation"', () => {
    const html = generateUATPlanHtml(baseData(NETSUITE_CTX));
    expect(html).toContain('NetSuite Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
  });
});

describe('generateUATPlan — Odoo adaptor (new path)', () => {
  const md = generateUATPlan(baseData(ODOO_CTX));

  it('byline reads ERPLaunch', () => {
    expect(md).toContain('**Prepared by:** ERPLaunch');
    expect(md).not.toContain('Ofoq NetSuite Accelerator');
  });

  it('contains no NetSuite-specific terminology', () => {
    for (const banned of ['SuiteScript', 'SDF', 'subsidiary', 'OneWorld', 'NetSuite']) {
      expect(md, `UAT Plan must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });

  it('HTML wrapper subtitle reads "Odoo Implementation" + ERPLaunch footer + no NetSuite leakage', () => {
    const html = generateUATPlanHtml(baseData(ODOO_CTX));
    expect(html).toContain('Odoo Implementation');
    expect(html).toContain('Generated by ERPLaunch');
    expect(html).not.toContain('Ofoq NetSuite Accelerator');
    for (const banned of ['SuiteScript', 'SDF', 'OneWorld', 'NetSuite']) {
      expect(html, `UAT Plan HTML must not contain "${banned}" for an Odoo engagement`).not.toContain(banned);
    }
  });
});

// ─── Regression class: rendered prose contains wizard-answer content ─────────
describe('generateUATPlan — non-NetSuite test cases walk adaptor.flows', () => {
  const ODOO_FLOWS = [
    {
      id: 'FOUNDATION',
      label: 'Project Foundation',
      description: 'Deployment, edition, geography.',
      sections: [
        {
          id: 'deployment',
          label: 'Deployment & Licensing',
          order: 1,
          questions: [
            { id: 'odoo.foundation.deploymentMode', label: 'Hosting & deployment mode', inputType: 'SINGLE_SELECT' as const,
              options: [{ value: 'ODOOSH', label: 'Odoo.sh' }] },
          ],
        },
      ],
    },
    {
      id: 'TAX',
      label: 'Tax Engine',
      description: 'Tax behavior, defaults, fiscal positions.',
      sections: [
        {
          id: 'behavior',
          label: 'Default Tax Behavior',
          order: 1,
          questions: [
            { id: 'odoo.tax.defaultSalesTax', label: 'Default Sales Tax', inputType: 'TEXT' as const },
          ],
        },
      ],
    },
  ];

  it('Odoo UAT plan emits a test case per populated question, with flow label as the Workstream column', () => {
    const md = generateUATPlan(baseData(
      { ...ODOO_CTX, flows: ODOO_FLOWS },
      {
        answers: {
          'odoo.foundation.deploymentMode': 'ODOOSH',
          'odoo.tax.defaultSalesTax': 'VAT 5%',
        },
      },
    ));
    expect(md).toContain('Project Foundation');
    expect(md).toContain('Tax Engine');
    expect(md).toContain('Hosting & deployment mode');
    expect(md).toContain('Default Sales Tax');
    expect(md).toContain('Odoo.sh');
    expect(md).toContain('VAT 5%');
  });

  it('NetSuite UAT plan still emits the hand-tuned scenarios from buildTestCases (regression guard)', () => {
    const md = generateUATPlan(baseData(NETSUITE_CTX, {
      answers: {
        'r2r.entities.multiEntity': true,
        'p2p.purchasing.usePurchaseOrders': true,
      },
    }));
    expect(md).toContain('Create a transaction in a child entity');
    expect(md).toContain('Create and approve a purchase order');
  });
});

describe('generateUATPlan — custom adaptor (fall-through default)', () => {
  it('renders Acme ERP-flavored prose with no NetSuite leak', () => {
    const html = generateUATPlanHtml(baseData(CUSTOM_CTX));
    expect(html).toContain('Acme ERP Implementation');
    expect(html).not.toContain('NetSuite');
    expect(html).not.toContain('SuiteScript');
    expect(html).not.toContain('SDF');
  });
});
