import type { Question } from './types.js';
// Placeholder — import type { Question } from './types.js';

export const mfgQuestions: Question[] = [
  // ── SECTION: productionFlow ───────────────────────────────────────────────
  {
    id: 'mfg.productionFlow.type',
    flow: 'PRODUCTION',
    section: 'productionFlow',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'SIMPLE_ASSEMBLY', label: 'Simple Assembly', description: 'Stock items that are built without tracking labor or machine time.' },
      { value: 'WORK_ORDER', label: 'Work Order Only', description: 'Items built via Work Orders to track production demand and quantity.' },
      { value: 'WIP_ROUTINGS', label: 'WIP & Routings', description: 'Advanced production tracking including labor, steps (routings), and Work-in-Process (WIP).' },
    ],
    label: 'How does the company build its products?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This selection determines which NetSuite modules need to be enabled. WIP & Routings requires the "Work Orders" and "Routings" features and involves much more complex setup.',
    exampleText: 'A furniture maker often needs WIP & Routings to track time spent in Cutting, Assembly, and Finishing departments.',
  },
  {
    id: 'mfg.productionFlow.trackLabor',
    flow: 'PRODUCTION',
    section: 'productionFlow',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need to track labor or machine costs against specific production jobs?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Tracking labor requires WIP & Routings. If enabled, production teams must record "Manufacturing Operations" to log time spent on each step.',
    exampleText: 'If a worker spends 2 hours assembling a pump, should that AED 200 labor cost be added to the value of the finished pump?',
    dependsOn: { questionId: 'mfg.productionFlow.type', value: 'WIP_ROUTINGS' },
  },

  // ── SECTION: bom ──────────────────────────────────────────────────────────
  {
    id: 'mfg.bom.multiBom',
    flow: 'PRODUCTION',
    section: 'bom',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do items have multiple Bills of Materials (BOMs) — for example, different recipes for different production sites?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite "Advanced BOM" allows an item to have multiple BOM records. This is useful if a product is made differently in different factories or if there are seasonal recipe changes.',
    exampleText: 'The same detergent might use different raw materials depending on which factory is making it.',
  },
  {
    id: 'mfg.bom.usePhantoms',
    flow: 'PRODUCTION',
    section: 'bom',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use "Phantom Assemblies" — sub-assemblies that are built and immediately consumed into a parent item without being stocked?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Phantoms simplify production by allowing you to group components in a BOM without requiring a separate Work Order for the sub-assembly.',
    exampleText: 'An electronics group includes a standard "Cable Set" in 10 different products. The cable set isn\'t stocked separately, it\'s just a group of parts.',
  },

  // ── SECTION: outsourced ─────────────────────────────────────────────────────
  {
    id: 'mfg.outsourced.useOutsourced',
    flow: 'PRODUCTION',
    section: 'outsourced',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company send raw materials to external vendors to be processed or assembled (Outsourced Manufacturing)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Outsourced manufacturing requires specific configuration to track inventory at the vendor\'s location and automate the generation of Purchase Orders for the manufacturing service.',
    exampleText: 'Acme sends raw fabric to a third-party stitching company. The company stitches shirts and sends the finished goods back.',
  },
  {
    id: 'mfg.outsourced.shipToVendor',
    flow: 'PRODUCTION',
    section: 'outsourced',
    order: 2,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Will the company ship components directly from their warehouse to the manufacturer?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This affects the inventory transfer logic. If enabled, NetSuite will suggest "Transfer Orders" to move raw materials to the vendor location.',
    exampleText: 'We send the fabric from our Jebel Ali warehouse to the tailor\'s site in Sharjah.',
    dependsOn: { questionId: 'mfg.outsourced.useOutsourced', value: true },
  },

  // ── SECTION: demand ───────────────────────────────────────────────────────
  {
    id: 'mfg.demand.useDemandPlanning',
    flow: 'PRODUCTION',
    section: 'demand',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need the system to calculate production requirements based on sales forecasts and historical trends?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite Demand Planning uses historical data and sales forecasts to suggest when to create work orders. This is a licensed module.',
    exampleText: 'If we expect to sell 1,000 units in June, the system should tell us to start production in May based on the 4-week lead time.',
  },
  {
    id: 'mfg.demand.planningTimeFence',
    flow: 'PRODUCTION',
    section: 'demand',
    order: 2,
    inputType: 'NUMBER',
    required: false,
    label: 'What is the "Planning Time Fence" (in days) — the period during which the system should not suggest new production orders?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This prevents "nervousness" in the plan. Within the time fence, the schedule is treated as fixed and should only be changed manually.',
    exampleText: 'If the fence is 7 days, the system won\'t suggest a new production order starting tomorrow, as materials are already committed.',
    dependsOn: { questionId: 'mfg.demand.useDemandPlanning', value: true },
  },

  // ── SECTION: workOrders ───────────────────────────────────────────────────
  {
    id: 'mfg.workOrders.useWorkOrders',
    flow: 'PRODUCTION',
    section: 'workOrders',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use Work Orders to manage and track production jobs?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Work Orders allow you to plan materials, assign labour, and track production costs against a specific job.',
    exampleText: 'Each customer order or batch is assigned a Work Order to track what materials were consumed and how much labour was spent.',
  },
  {
    id: 'mfg.workOrders.autoCreateWO',
    flow: 'PRODUCTION',
    section: 'workOrders',
    order: 2,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should Work Orders be automatically created when a Sales Order is confirmed?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Demand-driven production eliminates manual WO creation and links sales demand directly to the shop floor.',
    exampleText: 'When a sales order is confirmed, the system automatically creates a corresponding Work Order so production can start immediately.',
    dependsOn: { questionId: 'mfg.workOrders.useWorkOrders', value: true },
  },
  {
    id: 'mfg.workOrders.woApprovalRequired',
    flow: 'PRODUCTION',
    section: 'workOrders',
    order: 3,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Do Work Orders require supervisor approval before production can begin?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Requiring approval ensures quality control and prevents unauthorized production runs.',
    exampleText: 'A production supervisor must review and approve the Work Order before the shop floor team can start assembly.',
    dependsOn: { questionId: 'mfg.workOrders.useWorkOrders', value: true },
  },
  {
    id: 'mfg.workOrders.backflushComponents',
    flow: 'PRODUCTION',
    section: 'workOrders',
    order: 4,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should component materials be automatically consumed (backflushed) when a Work Order is completed?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Backflushing reduces manual inventory issue transactions but requires accurate Bills of Materials.',
    exampleText: 'When a Work Order is marked as complete, the system automatically removes the exact quantities of materials listed in the BOM from inventory.',
    dependsOn: { questionId: 'mfg.workOrders.useWorkOrders', value: true },
  },

  // ── SECTION: inventory ─────────────────────────────────────────────────────
  {
    id: 'mfg.inventory.lotTracking',
    flow: 'PRODUCTION',
    section: 'inventory',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company track inventory by lot or batch number?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Required for food, pharmaceutical, and regulated industries. Enables full traceability from supplier to customer.',
    exampleText: 'Each batch of raw material is assigned a lot number. If a supplier batch is found to be defective, all finished goods made from that lot can be traced and recalled.',
  },
  {
    id: 'mfg.inventory.serialTracking',
    flow: 'PRODUCTION',
    section: 'inventory',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company track individual serial numbers for finished goods?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Serial tracking is common for high-value items, electronics, and warranty management.',
    exampleText: 'Each laptop sold has a unique serial number. If a customer has a warranty claim, support can look up that specific unit in the inventory system.',
  },
  {
    id: 'mfg.inventory.multiLocationInventory',
    flow: 'PRODUCTION',
    section: 'inventory',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company manage stock across multiple warehouses or bin locations?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Multi-location inventory requires the Advanced Inventory module.',
    exampleText: 'The company has three warehouses. Each location stocks the same items but in different quantities, and the system must track them separately.',
  },
  {
    id: 'mfg.inventory.reorderPoints',
    flow: 'PRODUCTION',
    section: 'inventory',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Should the system automatically trigger replenishment when inventory falls below a minimum level?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Reorder points prevent stockouts and help maintain optimal inventory levels.',
    exampleText: 'If raw material stock drops below 100 units, the system automatically suggests creating a purchase order for the supplier.',
  },

  // ── SECTION: costing ──────────────────────────────────────────────────────
  {
    id: 'mfg.costing.costingMethod',
    flow: 'PRODUCTION',
    section: 'costing',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'What inventory costing method does the company use?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The costing method determines how Cost of Goods Sold is calculated and affects GL posting values.',
    exampleText: 'Using Standard Costing allows us to set expected material and labor costs upfront, then track variances from actual production.',
    options: [
      { value: 'AVERAGE_COST', label: 'Average Cost', description: 'Cost is calculated as the average of all units in inventory.' },
      { value: 'FIFO', label: 'FIFO (First In, First Out)', description: 'The oldest inventory is consumed first.' },
      { value: 'LIFO', label: 'LIFO (Last In, First Out)', description: 'The newest inventory is consumed first.' },
      { value: 'STANDARD_COST', label: 'Standard Cost', description: 'Costs are set in advance based on expected material and labor.' },
    ],
  },
  {
    id: 'mfg.costing.standardCostVariance',
    flow: 'PRODUCTION',
    section: 'costing',
    order: 2,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should the system track and report variances between standard and actual production costs?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Variance analysis helps identify production inefficiencies and drives continuous improvement.',
    exampleText: 'If the standard cost of a unit is AED 100 but actual production costs AED 115, the system flags a AED 15 unfavorable variance.',
    dependsOn: { questionId: 'mfg.costing.costingMethod', value: 'STANDARD_COST' },
  },
  {
    id: 'mfg.costing.overheadAllocation',
    flow: 'PRODUCTION',
    section: 'costing',
    order: 3,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Does the company allocate indirect overhead costs (rent, utilities, indirect labour) to manufactured items?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Overhead allocation provides more accurate product costing by spreading indirect costs across all produced items.',
    exampleText: 'Factory rent of AED 50,000 per month is allocated to products based on production volume, so each unit bears its share of overhead.',
  },

  // ── SECTION: quality ──────────────────────────────────────────────────────
  {
    id: 'mfg.quality.qualityInspection',
    flow: 'PRODUCTION',
    section: 'quality',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Is a quality inspection required before finished goods can be received into sellable inventory?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Quality inspections ensure that only conforming items enter sellable stock, preventing defects from reaching customers.',
    exampleText: 'When a Work Order is completed, items must pass a QA check and be approved before they can be transferred to finished goods inventory.',
  },
  {
    id: 'mfg.quality.ncr',
    flow: 'PRODUCTION',
    section: 'quality',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company issue Non-Conformance Reports (NCRs) for defective or out-of-spec production output?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NCRs document quality failures and drive continuous improvement by tracking root causes and trends.',
    exampleText: 'If a batch of 50 items fails inspection, an NCR is created to document the failure, the cause, and whether items will be scrapped or reworked.',
  },
];
