import type { Question } from './types.js';

export const o2cQuestions: Question[] = [

  // ── SECTION: customers ────────────────────────────────────────────────────
  {
    id: 'o2c.customers.hasMultipleCustomerTypes',
    flow: 'O2C',
    section: 'customers',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company sell to different types of customers — for example, wholesale distributors, retail clients, and government entities?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Customer categories drive pricing tiers, approval rules, payment terms, and reporting. Knowing this upfront avoids restructuring the customer master mid-implementation.',
    exampleText: 'The company sells to retailers (who get trade discounts), government bodies (requiring formal tenders), and direct consumers (at list price).',
  },
  {
    id: 'o2c.customers.customerCategories',
    flow: 'O2C',
    section: 'customers',
    order: 2,
    inputType: 'TABLE',
    required: false,
    label: 'List the customer categories to create (category name and description).',
    helpTitle: 'Why does this matter?',
    helpBody: 'Categories map to pricing levels, payment terms defaults, and reporting segments in NetSuite.',
    exampleText: 'Row 1: Wholesale — distributors buying in bulk. Row 2: Government — public sector with 60-day terms. Row 3: Direct — individual customers at list price.',
    dependsOn: { questionId: 'o2c.customers.hasMultipleCustomerTypes', value: true },
  },
  {
    id: 'o2c.customers.creditLimits',
    flow: 'O2C',
    section: 'customers',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company set credit limits on customers and block or warn when a sales order would exceed that limit?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Credit limit enforcement is a key AR control. NetSuite can soft-warn or hard-block sales orders for customers who have exceeded their credit limit.',
    exampleText: 'A distributor has a AED 500,000 credit limit. If they try to place a new order that would bring their outstanding balance above this, the order is held.',
  },
  {
    id: 'o2c.customers.defaultPaymentTerms',
    flow: 'O2C',
    section: 'customers',
    order: 4,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'What is the standard payment term offered to customers?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The default payment term drives invoice due dates and AR aging. It can be overridden per customer.',
    exampleText: 'Most customers are given Net 30 payment terms.',
    options: [
      { value: 'cod',   label: 'Due on receipt / COD',             description: 'Payment expected immediately upon delivery or invoice receipt.' },
      { value: 'net15', label: 'Net 15',                           description: 'Payment due within 15 days of invoice date.' },
      { value: 'net30', label: 'Net 30',                           description: 'Standard term; payment due within 30 days of invoice date.' },
      { value: 'net45', label: 'Net 45',                           description: 'Payment due within 45 days; common in government or large retail.' },
      { value: 'net60', label: 'Net 60',                           description: 'Extended terms; typically reserved for large or strategic customers.' },
      { value: 'mixed', label: 'Mixed — varies by customer segment', description: 'Different segments receive different payment terms based on their category.' },
    ],
  },
  {
    id: 'o2c.customers.customerApproval',
    flow: 'O2C',
    section: 'customers',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Must new customers be reviewed and approved before sales orders can be raised for them?',
    helpTitle: 'Why does this matter?',
    helpBody: 'A customer onboarding approval prevents sales to unapproved or high-risk counterparties. It is common in B2B and regulated industries.',
    exampleText: 'The credit controller must approve each new customer and set their credit limit before the first sale can be processed.',
  },

  // ── SECTION: pricing ──────────────────────────────────────────────────────
  {
    id: 'o2c.pricing.multiplePriceLevels',
    flow: 'O2C',
    section: 'pricing',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use different price lists or price levels for different customer groups?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Price levels in NetSuite allow you to assign a tier (e.g. retail, wholesale, VIP) to each customer. The system automatically uses the right price on each transaction.',
    exampleText: 'Distributors get a 20% trade discount off list price; government customers get a special tender price.',
  },
  {
    id: 'o2c.pricing.priceLevelList',
    flow: 'O2C',
    section: 'pricing',
    order: 2,
    inputType: 'TABLE',
    required: false,
    label: 'List the price levels to configure (level name, discount % or description).',
    helpTitle: 'Why does this matter?',
    helpBody: 'Each row becomes a price level record in NetSuite and is linked to the appropriate customer category.',
    exampleText: 'Row 1: Base Price — standard list price. Row 2: Wholesale — 15% off list. Row 3: VIP — 25% off list.',
    dependsOn: { questionId: 'o2c.pricing.multiplePriceLevels', value: true },
  },
  {
    id: 'o2c.pricing.quantityDiscounts',
    flow: 'O2C',
    section: 'pricing',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company offer quantity-based discounts — lower unit prices when customers order larger quantities?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Quantity-based pricing ("quantity breaks") requires the Quantity Pricing module in NetSuite and a pricing matrix per item.',
    exampleText: 'Buying 1–9 units costs AED 100 each; 10–49 units costs AED 85 each; 50+ units costs AED 70 each.',
  },
  {
    id: 'o2c.pricing.promotionalPricing',
    flow: 'O2C',
    section: 'pricing',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company run time-limited promotions or discount campaigns that temporarily change prices?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Promotional pricing can be handled via promotion codes, temporary price levels, or scheduled price changes in NetSuite. The approach depends on how the promotions are structured.',
    exampleText: 'During Ramadan, all products are 10% off for the month.',
  },
  {
    id: 'o2c.pricing.foreignCurrencyPricing',
    flow: 'O2C',
    section: 'pricing',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company sell to customers in foreign currencies, or maintain price lists in currencies other than the base currency?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Multi-currency selling requires currency-specific price lists or live exchange rate conversion. This affects invoice amounts and AR reporting.',
    exampleText: 'The company sells to UK customers in GBP and US customers in USD, with local price lists for each market.',
  },

  // ── SECTION: salesOrders ──────────────────────────────────────────────────
  {
    id: 'o2c.salesOrders.useSalesOrders',
    flow: 'O2C',
    section: 'salesOrders',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use formal sales orders before shipping goods or delivering services?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Sales orders are the core O2C transaction. They drive fulfillment, invoicing, and revenue recognition. Without them, the system cannot manage the full order-to-cash cycle.',
    exampleText: 'Every customer order is entered as a sales order that must be approved before the warehouse picks the goods.',
  },
  {
    id: 'o2c.salesOrders.soApprovalRequired',
    flow: 'O2C',
    section: 'salesOrders',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do sales orders need to be approved before they can be fulfilled or invoiced?',
    helpTitle: 'Why does this matter?',
    helpBody: 'SO approval workflows are common in B2B environments to ensure credit checks, margin reviews, or management sign-off before committing stock.',
    exampleText: 'Any sales order above AED 100,000 requires the Sales Director to approve before the warehouse processes it.',
    dependsOn: { questionId: 'o2c.salesOrders.useSalesOrders', value: true },
  },
  {
    id: 'o2c.salesOrders.quotations',
    flow: 'O2C',
    section: 'salesOrders',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do sales staff issue formal quotations to customers before they confirm an order?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite estimates (quotations) can be converted into sales orders with one click. Using them keeps track of win/loss rates and pipeline value.',
    exampleText: 'The sales team creates a quotation in NetSuite, emails it to the customer as a PDF, and converts it to an SO when the customer accepts.',
  },
  {
    id: 'o2c.salesOrders.backOrders',
    flow: 'O2C',
    section: 'salesOrders',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Can the company accept and hold orders when stock is not available (backorders), and fulfil them when stock arrives?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Backorder management requires the system to keep partial sales orders open and fulfil them as stock becomes available.',
    exampleText: 'A customer orders 50 units. Only 30 are in stock. The company ships 30 now and holds the order open for the remaining 20.',
    dependsOn: { questionId: 'o2c.salesOrders.useSalesOrders', value: true },
  },
  {
    id: 'o2c.salesOrders.dropShipping',
    flow: 'O2C',
    section: 'salesOrders',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company ever fulfil customer orders directly from a supplier (drop-shipping) without the goods passing through its own warehouse?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Drop-shipping requires linking a sales order to a purchase order. NetSuite supports this as a specific transaction flow.',
    exampleText: 'For large equipment orders, the manufacturer ships directly to the end customer on behalf of the company.',
  },

  // ── SECTION: fulfillment ──────────────────────────────────────────────────
  {
    id: 'o2c.fulfillment.usesWarehouse',
    flow: 'O2C',
    section: 'fulfillment',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company ship physical goods from a warehouse or storage location?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Physical fulfilment requires item fulfilment records, inventory tracking, and potentially multi-location stock management in NetSuite.',
    exampleText: 'The company operates a warehouse in Jebel Ali from which all customer orders are picked, packed, and dispatched.',
  },
  {
    id: 'o2c.fulfillment.multipleLocations',
    flow: 'O2C',
    section: 'fulfillment',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company fulfil orders from more than one location or warehouse?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Multi-location fulfillment requires the Multi-Location Inventory module and affects how stock is allocated and transferred between locations.',
    exampleText: 'The company has warehouses in Dubai and Riyadh. Orders are fulfilled from whichever is closest to the customer.',
    dependsOn: { questionId: 'o2c.fulfillment.usesWarehouse', value: true },
  },
  {
    id: 'o2c.fulfillment.pickPackShip',
    flow: 'O2C',
    section: 'fulfillment',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the warehouse use a pick-pack-ship process where goods are picked from shelves, packed into boxes, and then dispatched?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Pick-pack-ship workflows require the Advanced Shipping module and generate pick lists, packing slips, and shipping labels from NetSuite.',
    exampleText: 'Warehouse staff print a pick list, collect items, pack them, and attach a shipping label before handing to the courier.',
    dependsOn: { questionId: 'o2c.fulfillment.usesWarehouse', value: true },
  },
  {
    id: 'o2c.fulfillment.thirdPartyLogistics',
    flow: 'O2C',
    section: 'fulfillment',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use a third-party logistics provider (3PL) to store or ship goods on its behalf?',
    helpTitle: 'Why does this matter?',
    helpBody: 'If a 3PL manages inventory, NetSuite needs to sync stock levels with the 3PL system, either via integration or manual updates.',
    exampleText: 'All storage and shipping is handled by a logistics partner. NetSuite needs to receive stock confirmation from them.',
  },
  {
    id: 'o2c.fulfillment.serviceDelivery',
    flow: 'O2C',
    section: 'fulfillment',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company deliver services (rather than physical goods), and need to track project or service delivery against sales orders?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Service-based fulfillment may require Project Management or Professional Services Automation modules linked to sales orders.',
    exampleText: 'Each consulting engagement is a sales order. Time logged against the project automatically drives the invoicing.',
  },

  // ── SECTION: invoicing ────────────────────────────────────────────────────
  {
    id: 'o2c.invoicing.invoiceTrigger',
    flow: 'O2C',
    section: 'invoicing',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'When does the company generate a customer invoice?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The invoicing trigger determines the O2C transaction sequence and revenue recognition timing.',
    exampleText: 'Invoices are generated at the time of shipment.',
    options: [
      { value: 'on_order',      label: 'When the sales order is confirmed',          description: 'Invoice is raised as soon as the order is approved, before fulfilment.' },
      { value: 'on_shipment',   label: 'When goods are shipped (item fulfillment)',   description: 'Invoice is generated at the point of dispatch; most common for product businesses.' },
      { value: 'on_delivery',   label: 'When goods are delivered and signed for',     description: 'Invoice is issued only after proof of delivery is received.' },
      { value: 'on_completion', label: 'When a project or service is completed',      description: 'Invoice is raised after the service or project milestone is signed off.' },
      { value: 'periodic',      label: 'Periodically (weekly/monthly billing runs)',  description: 'Invoices are batched and issued on a regular schedule regardless of individual transactions.' },
      { value: 'milestone',     label: 'At contract milestones',                      description: 'Invoice timing is tied to specific contract deliverables or project milestones.' },
    ],
  },
  {
    id: 'o2c.invoicing.electronicInvoicing',
    flow: 'O2C',
    section: 'invoicing',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Is the company required to issue electronic invoices (e-invoicing) in a government-mandated format such as ZATCA (KSA) or e-Finance (UAE)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Government e-invoicing mandates (like ZATCA Phase 2 in Saudi Arabia) require specific invoice formats, QR codes, and direct submission to tax authority systems from NetSuite.',
    exampleText: 'The company operates in Saudi Arabia and must submit all invoices to ZATCA\'s Fatoora platform in real time.',
  },
  {
    id: 'o2c.invoicing.creditMemos',
    flow: 'O2C',
    section: 'invoicing',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company issue credit notes or credit memos to customers (e.g. for returns, pricing adjustments, or goodwill credits)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Credit memos reduce AR balances and affect revenue reporting. They need to be linked to original invoices for proper audit trails.',
    exampleText: 'When a customer returns goods or disputes a charge, the AR team issues a credit memo that can be applied against future invoices.',
  },
  {
    id: 'o2c.invoicing.recurringInvoices',
    flow: 'O2C',
    section: 'invoicing',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company have subscription or retainer clients that need recurring invoices generated automatically each period?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite can auto-generate recurring invoices on a schedule, which is essential for SaaS, retainer, or subscription billing models.',
    exampleText: 'The company charges a monthly managed service fee of AED 15,000 to 40 clients. A recurring billing template generates all 40 invoices on the 1st of each month.',
  },
  {
    id: 'o2c.invoicing.revenueRecognition',
    flow: 'O2C',
    section: 'invoicing',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need to defer or spread revenue recognition — for example, recognising subscription revenue monthly rather than all on the invoice date?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Revenue deferral (required by IFRS 15) needs the Advanced Revenue Management module in NetSuite and recognition schedules linked to each item.',
    exampleText: 'A 12-month software licence is invoiced upfront but the AED 120,000 revenue is recognised at AED 10,000/month.',
  },

  // ── SECTION: collections ──────────────────────────────────────────────────
  {
    id: 'o2c.collections.arAgingTracking',
    flow: 'O2C',
    section: 'collections',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company actively track overdue customer invoices and manage collections through an AR aging process?',
    helpTitle: 'Why does this matter?',
    helpBody: 'AR aging reports and collections management are standard in NetSuite but need to be set up with the correct ageing buckets and collection workflows.',
    exampleText: 'The AR team reviews overdue invoices every week and follows up with customers on the 30, 60, and 90-day buckets.',
  },
  {
    id: 'o2c.collections.agingBuckets',
    flow: 'O2C',
    section: 'collections',
    order: 2,
    inputType: 'TABLE',
    required: false,
    label: 'List the AR aging buckets used for reporting and collections (e.g. 0–30, 31–60, 61–90, 90+ days).',
    helpTitle: 'Why does this matter?',
    helpBody: 'Ageing buckets are configured in the AR module and appear on all AR aging reports and collection dashboards.',
    exampleText: 'Row 1: Current (0–30 days). Row 2: 31–60 days. Row 3: 61–90 days. Row 4: 91–120 days. Row 5: Over 120 days.',
    dependsOn: { questionId: 'o2c.collections.arAgingTracking', value: true },
  },
  {
    id: 'o2c.collections.dunningLetters',
    flow: 'O2C',
    section: 'collections',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company send formal dunning letters or automated reminder emails to customers with overdue invoices?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Automated dunning requires the Collections Management module or SuiteApp. Manual dunning can be done via statements and custom saved searches.',
    exampleText: 'Customers overdue by 15 days get a polite reminder; 30 days get a formal notice; 60 days triggers an escalation to the Finance Director.',
    dependsOn: { questionId: 'o2c.collections.arAgingTracking', value: true },
  },
  {
    id: 'o2c.collections.cashApplication',
    flow: 'O2C',
    section: 'collections',
    order: 4,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'How does the company match incoming customer payments to outstanding invoices?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Cash application (payment matching) is one of the highest-effort AR activities. The process determines how much automation or manual work is needed in NetSuite.',
    exampleText: 'Payments are matched manually by the AR team using remittance advice from customers.',
    options: [
      { value: 'manual',      label: 'Manual — AR team matches each payment to invoices', description: 'Staff review each bank receipt and manually apply it to open invoices.' },
      { value: 'bank_import', label: 'Bank statement import with auto-match rules',       description: 'Bank statements are imported and the system suggests or applies matches automatically.' },
      { value: 'remittance',  label: 'Customer remittance advice drives matching',        description: 'Customers send a remittance slip that specifies which invoices the payment covers.' },
      { value: 'auto',        label: 'Fully automated via payment gateway or EDI',        description: 'Payment and invoice data flow through an integration with no manual intervention.' },
    ],
  },
  {
    id: 'o2c.collections.badDebtProvision',
    flow: 'O2C',
    section: 'collections',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company make periodic provisions for bad or doubtful debts and write off uncollectable invoices?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Bad debt provisioning requires specific GL accounts and journal entries. Write-offs in NetSuite need to be mapped to the correct accounts to avoid distorting AR balances.',
    exampleText: 'At quarter end, the finance team provisions 5% of invoices over 90 days old as a doubtful debt reserve.',
  },
];
