import type { Question } from './types.js';

export const p2pQuestions: Question[] = [

  // ── SECTION: vendors ──────────────────────────────────────────────────────
  {
    id: 'p2p.vendors.hasMultipleVendorTypes',
    flow: 'P2P',
    section: 'vendors',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company deal with different types of vendors — for example, suppliers of goods, service providers, and contractors?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite allows you to categorise vendors so that reporting and approval rules can be applied per type. Knowing this upfront prevents having to restructure the vendor master later.',
    exampleText: 'The company buys raw materials from product suppliers, hires IT consultants, and uses logistics companies — three distinct vendor types.',
  },
  {
    id: 'p2p.vendors.vendorCategories',
    flow: 'P2P',
    section: 'vendors',
    order: 2,
    inputType: 'TABLE',
    required: false,
    label: 'List the vendor categories to be created (category name and a brief description).',
    helpTitle: 'Why does this matter?',
    helpBody: 'Vendor categories drive reporting, approval routing, and tax treatment. A clear list speeds up vendor master configuration.',
    exampleText: 'Row 1: Goods Suppliers — vendors who supply physical inventory. Row 2: Service Providers — consultants and agencies. Row 3: Utilities — recurring fixed-cost vendors.',
    dependsOn: { questionId: 'p2p.vendors.hasMultipleVendorTypes', value: true },
  },
  {
    id: 'p2p.vendors.defaultPaymentTerms',
    flow: 'P2P',
    section: 'vendors',
    order: 3,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'What is the most common vendor payment term used by this company?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite uses payment terms to calculate due dates on vendor bills. This default can be overridden per vendor but needs a system-wide default.',
    exampleText: 'Most suppliers require payment within 30 days of invoice date.',
    options: [
      { value: 'net15',   label: 'Net 15 — due 15 days from invoice',  description: 'Short payment window; common for fast-moving goods suppliers.' },
      { value: 'net30',   label: 'Net 30 — due 30 days from invoice',  description: 'Most common standard term for B2B vendor payments.' },
      { value: 'net45',   label: 'Net 45 — due 45 days from invoice',  description: 'Extended term; common in construction and project-based procurement.' },
      { value: 'net60',   label: 'Net 60 — due 60 days from invoice',  description: 'Long term; common for large suppliers or government contractors.' },
      { value: 'cod',     label: 'COD — cash on delivery',             description: 'Payment required at point of delivery; common for petty vendors.' },
      { value: 'prepaid', label: 'Prepaid — payment before delivery',  description: 'Full payment in advance; typical for new relationships or custom orders.' },
      { value: 'mixed',   label: 'Mixed — varies by vendor',           description: 'No single default; each vendor has individually negotiated terms.' },
    ],
  },
  {
    id: 'p2p.vendors.earlyPaymentDiscount',
    flow: 'P2P',
    section: 'vendors',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do any vendors offer an early payment discount (e.g. 2% discount if paid within 10 days)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Early payment discount terms need to be configured so NetSuite automatically calculates the discount amount during payment processing.',
    exampleText: 'Key suppliers offer 2% off if the company pays within 10 days instead of the standard 30.',
  },
  {
    id: 'p2p.vendors.withholding',
    flow: 'P2P',
    section: 'vendors',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need to withhold tax on payments to certain vendors (e.g. WHT on contractor payments)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Withholding tax requires a dedicated tax code configuration and affects how vendor bill amounts are calculated. Common in GCC and African markets.',
    exampleText: 'Payments to local contractors are subject to 5% withholding tax which must be remitted to the tax authority separately.',
  },
  {
    id: 'p2p.vendors.vendorApprovalRequired',
    flow: 'P2P',
    section: 'vendors',
    order: 6,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Must new vendors be approved before they can be used to raise purchase orders or record bills?',
    helpTitle: 'Why does this matter?',
    helpBody: 'A vendor approval workflow prevents unauthorised vendors from being added. It requires a custom workflow or role-based restriction on vendor record creation.',
    exampleText: 'Finance policy requires the CFO to approve any new vendor before the first PO can be raised.',
  },

  // ── SECTION: purchasing ───────────────────────────────────────────────────
  {
    id: 'p2p.purchasing.usePurchaseOrders',
    flow: 'P2P',
    section: 'purchasing',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company raise formal purchase orders before ordering goods or services from vendors?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Using purchase orders is the backbone of a controlled P2P process. It enables 3-way matching and budget commitment tracking.',
    exampleText: 'The procurement team must create a PO in the system before contacting any supplier.',
  },
  {
    id: 'p2p.purchasing.poApprovalRequired',
    flow: 'P2P',
    section: 'purchasing',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do purchase orders need to be approved before they are sent to the vendor?',
    helpTitle: 'Why does this matter?',
    helpBody: 'PO approval workflows are one of the most common control requirements. NetSuite routes POs for approval based on amount, department, or item type.',
    exampleText: 'Any PO over AED 5,000 requires the department manager to approve; over AED 50,000 requires the CFO.',
    dependsOn: { questionId: 'p2p.purchasing.usePurchaseOrders', value: true },
  },
  {
    id: 'p2p.purchasing.approvalThresholds',
    flow: 'P2P',
    section: 'purchasing',
    order: 3,
    inputType: 'TABLE',
    required: false,
    label: 'List the PO approval levels: amount threshold, approver role, and any conditions.',
    helpTitle: 'Why does this matter?',
    helpBody: 'This table maps directly to the approval workflow configuration. Each row becomes an approval step in the NetSuite workflow.',
    exampleText: 'Row 1: Up to 5,000 — Department Manager. Row 2: 5,001–50,000 — Finance Manager. Row 3: Over 50,000 — CFO.',
    dependsOn: { questionId: 'p2p.purchasing.poApprovalRequired', value: true },
  },
  // Real-code companion to approvalThresholds (TABLE). Free-text form is
  // what the SuiteScript User Event generator parses into a hardcoded
  // APPROVAL_TIERS array — one line per tier, format
  // "<range_label>: <approver>". The TABLE answer above remains the
  // consultant-facing source of truth; this TEXTAREA is the
  // generator-friendly projection. Empty / missing answer skips
  // SuiteScript emission.
  {
    id: 'p2p.purchasing.poApprovalTiers',
    flow: 'P2P',
    section: 'purchasing',
    order: 7,
    inputType: 'TEXTAREA',
    required: false,
    label:
      "Purchase Order approval tiers (one per line — '<range>: <approver>'; e.g., '<$5,000: auto-approve', '$5,000-$50,000: Department Manager', '$50,000-$250,000: VP Operations', '>$250,000: CFO + Steering')",
    helpTitle: 'Why does this matter?',
    helpBody:
      'This is the generator-readable form of the approval thresholds. ERPLaunch parses each line into a tier in the auto-generated User Event script (NSIX_UE_PurchaseOrderApproval.js) so the deployed script already has the correct amount thresholds and approver roles wired before the consultant ever opens it.',
    exampleText:
      "<$5,000: auto-approve\n$5,000-$50,000: Department Manager\n$50,000-$250,000: VP Operations\n>$250,000: CFO + Steering",
    dependsOn: { questionId: 'p2p.purchasing.poApprovalRequired', value: true },
  },
  {
    id: 'p2p.purchasing.budgetCheck',
    flow: 'P2P',
    section: 'purchasing',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Should the system check available budget before allowing a purchase order to be approved?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Budget checking on POs prevents departments from overspending. It requires the budgeting module and a defined chart of accounts structure.',
    exampleText: 'If Operations has only AED 10,000 left in its travel budget, a PO for AED 15,000 should be blocked until the budget is increased.',
    dependsOn: { questionId: 'p2p.purchasing.usePurchaseOrders', value: true },
  },
  {
    id: 'p2p.purchasing.blanketPOs',
    flow: 'P2P',
    section: 'purchasing',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use blanket or standing purchase orders — a single PO covering multiple deliveries over a period?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Blanket POs are used for recurring purchases from the same vendor. NetSuite handles these differently from one-time POs and they need specific configuration.',
    exampleText: 'An annual contract with a cleaning company for AED 120,000, processed as monthly deliveries of AED 10,000 each against one PO.',
  },
  {
    id: 'p2p.purchasing.purchaseRequisitions',
    flow: 'P2P',
    section: 'purchasing',
    order: 6,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do staff submit purchase requisitions (internal requests) that procurement then converts into purchase orders?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Purchase requisitions add a pre-PO step. Requires enabling the Purchase Requests module.',
    exampleText: 'A marketing manager fills a requisition for 10 branded notebooks. Procurement validates it and creates the PO.',
  },

  // ── SECTION: receiving ────────────────────────────────────────────────────
  {
    id: 'p2p.receiving.formalReceiving',
    flow: 'P2P',
    section: 'receiving',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company formally record the receipt of goods or services before approving vendor invoices for payment?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Item receipts are the foundation of 3-way matching. Recording what was received prevents paying for goods never delivered.',
    exampleText: 'When the warehouse receives a delivery, a team member creates an item receipt in NetSuite referencing the original PO.',
  },
  {
    id: 'p2p.receiving.threeWayMatch',
    flow: 'P2P',
    section: 'receiving',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Should vendor bills be matched against both the purchase order AND the item receipt before payment is allowed?',
    helpTitle: 'Why does this matter?',
    helpBody: '3-way matching (PO → receipt → bill) ensures the company only pays for what was ordered AND received. NetSuite can enforce this as a hard block.',
    exampleText: 'A supplier bills for 100 units. The system checks the PO and receipt both show 100 units before releasing payment.',
    dependsOn: { questionId: 'p2p.receiving.formalReceiving', value: true },
  },
  {
    id: 'p2p.receiving.partialReceipts',
    flow: 'P2P',
    section: 'receiving',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Can the company receive and pay for partial deliveries — for example, 60 out of 100 ordered items?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Partial receipts affect how the PO remains open and how the bill is matched. NetSuite supports this natively.',
    exampleText: 'A supplier delivers 60 items now and the remaining 40 next month. The PO stays open for the balance.',
    dependsOn: { questionId: 'p2p.receiving.formalReceiving', value: true },
  },
  {
    id: 'p2p.receiving.returnsToVendor',
    flow: 'P2P',
    section: 'receiving',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company return goods to vendors and need to track vendor return transactions and credit notes?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Vendor returns require Vendor Return Authorisations in NetSuite and generate vendor credit memos that offset future bills.',
    exampleText: 'Defective items are returned to the supplier and a credit note is applied against the next bill.',
  },
  {
    id: 'p2p.receiving.serviceReceipts',
    flow: 'P2P',
    section: 'receiving',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'For service-based POs, does the company create a formal service confirmation before paying?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Services cannot be physically received so a service confirmation record serves the same purpose as an item receipt for 3-way matching.',
    exampleText: 'The project manager confirms delivery of 10 days of consulting work before the invoice is approved.',
  },

  // ── SECTION: bills ────────────────────────────────────────────────────────
  {
    id: 'p2p.bills.billEntryProcess',
    flow: 'P2P',
    section: 'bills',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'How does the company currently process vendor invoices?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The bill entry process determines whether NetSuite needs an approval workflow, OCR integration, or a simple manual entry screen.',
    exampleText: 'Currently, the AP team receives emailed PDFs and manually keys them in.',
    options: [
      { value: 'manual',   label: 'Manual entry — AP team keys each invoice',      description: 'AP staff read each paper or PDF invoice and enter the details manually.' },
      { value: 'scan_ocr', label: 'Scanned and OCR extracted into the system',     description: 'Invoices are scanned and data is captured automatically via OCR technology.' },
      { value: 'edi',      label: 'Received electronically (EDI or vendor portal)', description: 'Vendors submit invoices through a structured electronic channel.' },
      { value: 'auto_po',  label: 'Auto-created from approved POs (services)',      description: 'Bills are generated automatically when a PO is fully receipted.' },
    ],
  },
  {
    id: 'p2p.bills.billApprovalRequired',
    flow: 'P2P',
    section: 'bills',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do vendor bills need to be approved before they can be scheduled for payment?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Bill approval adds a second layer of control after 3-way matching. Even if a bill matches the PO and receipt, a manager may need to approve before payment runs.',
    exampleText: 'All vendor bills above AED 10,000 must be approved by the Finance Manager.',
  },
  {
    id: 'p2p.bills.billApprovalThresholds',
    flow: 'P2P',
    section: 'bills',
    order: 3,
    inputType: 'TABLE',
    required: false,
    label: 'List bill approval thresholds: amount, approver role, and any conditions.',
    helpTitle: 'Why does this matter?',
    helpBody: 'This maps directly to the bill approval workflow configuration in NetSuite.',
    exampleText: 'Row 1: Under 10,000 — auto-approved if matched to PO. Row 2: 10,001–100,000 — Finance Manager. Row 3: Over 100,000 — CFO.',
    dependsOn: { questionId: 'p2p.bills.billApprovalRequired', value: true },
  },
  {
    id: 'p2p.bills.creditNotes',
    flow: 'P2P',
    section: 'bills',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company receive vendor credit notes that need to be matched and applied against outstanding bills?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Vendor credit memos must be applied to open bills to reduce the amount due.',
    exampleText: 'A supplier issues a credit note for a pricing error. The AP team applies it to the next bill.',
  },
  {
    id: 'p2p.bills.recurringBills',
    flow: 'P2P',
    section: 'bills',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company have recurring bills on a fixed schedule — such as rent, subscriptions, or utilities?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite can auto-generate recurring bills on a schedule, reducing manual entry and ensuring nothing is missed.',
    exampleText: 'Office rent is AED 50,000/month. A recurring bill template generates it automatically on the 1st.',
  },
  {
    id: 'p2p.bills.multiCurrencyBills',
    flow: 'P2P',
    section: 'bills',
    order: 6,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company receive vendor invoices in foreign currencies?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Foreign currency bills require exchange rate management and generate realised/unrealised FX gains or losses.',
    exampleText: 'Software licences are billed in USD but the company books in AED, creating FX differences at payment.',
  },

  // ── SECTION: payments ─────────────────────────────────────────────────────
  {
    id: 'p2p.payments.paymentMethods',
    flow: 'P2P',
    section: 'payments',
    order: 1,
    inputType: 'MULTI_SELECT',
    required: true,
    label: 'What payment methods does the company use to pay vendors?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Each payment method needs its own bank account configuration and may require different integration points (e.g. bank file export).',
    exampleText: 'Most payments are bank transfers; cheques used for petty vendors; SWIFT for international.',
    options: [
      { value: 'bank_transfer', label: 'Bank transfer (EFT / SWIFT)', description: 'Electronic funds transfer within the same country or internationally via SWIFT.' },
      { value: 'cheque',        label: 'Cheque / check',              description: 'Paper cheque or check issued to the vendor.' },
      { value: 'credit_card',   label: 'Corporate credit card',       description: 'Payments made using company-issued credit or charge cards.' },
      { value: 'cash',          label: 'Cash (petty cash)',           description: 'Physical cash payments for small incidental purchases.' },
      { value: 'dd',            label: 'Direct debit / auto-debit',   description: 'Vendor pulls payment automatically on a set date.' },
    ],
  },
  {
    id: 'p2p.payments.paymentRunFrequency',
    flow: 'P2P',
    section: 'payments',
    order: 2,
    inputType: 'SINGLE_SELECT',
    required: true,
    label: 'How frequently does the company run its accounts payable payment batch?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Payment run frequency determines how AP aging is used and how cash flow planning is structured.',
    exampleText: 'The company pays all due invoices every Thursday.',
    options: [
      { value: 'daily',    label: 'Daily',             description: 'Payment batch is processed every business day.' },
      { value: 'weekly',   label: 'Weekly',            description: 'All due invoices are paid once per week, typically on a fixed day.' },
      { value: 'biweekly', label: 'Twice a month',     description: 'Payment runs are processed on two fixed dates each month.' },
      { value: 'monthly',  label: 'Monthly',           description: 'A single payment run covers all invoices due that month.' },
      { value: 'adhoc',    label: 'Ad hoc — as needed', description: 'No fixed schedule; payments are processed whenever bills are due or as requested.' },
    ],
  },
  {
    id: 'p2p.payments.bankFileExport',
    flow: 'P2P',
    section: 'payments',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need to export a payment file from NetSuite to upload directly into the bank portal?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Bank file export (e.g. ISO 20022, local bank formats) requires customised SuiteScript or a SuiteApp. This is a common integration requirement.',
    exampleText: 'After the payment run, the AP team exports a file and uploads it to the bank portal to initiate transfers.',
  },
  {
    id: 'p2p.payments.bankName',
    flow: 'P2P',
    section: 'payments',
    order: 4,
    inputType: 'TEXT',
    required: false,
    label: 'What is the name of the primary bank used for vendor payments, and in which country?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Knowing the bank and country helps determine which payment file format is required.',
    exampleText: 'Emirates NBD, UAE — uses the ENBD bulk payment format.',
    dependsOn: { questionId: 'p2p.payments.bankFileExport', value: true },
  },
  {
    id: 'p2p.payments.paymentApproval',
    flow: 'P2P',
    section: 'payments',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does a payment batch need to be approved by a manager before it is released to the bank?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Payment run approval is a critical cash control. It ensures someone with authority reviews the total outgoing amount.',
    exampleText: 'The CFO reviews and approves the weekly payment batch before the AP team uploads the bank file.',
  },
  {
    id: 'p2p.payments.advancePayments',
    flow: 'P2P',
    section: 'payments',
    order: 6,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company make advance payments or deposits to vendors before receiving goods or an invoice?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Prepayments require a vendor deposit transaction and need to be applied later against the actual bill.',
    exampleText: 'A contractor requires 30% payment upfront. The advance is recorded and cleared when the final bill arrives.',
  },

  // ── SECTION: expenses ─────────────────────────────────────────────────────
  {
    id: 'p2p.expenses.employeeExpenses',
    flow: 'P2P',
    section: 'expenses',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do employees submit out-of-pocket expense claims for reimbursement (e.g. travel, meals, client entertainment)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Employee expense reports in NetSuite allow staff to submit, get approval, and be reimbursed. Requires the Expense Reports module.',
    exampleText: 'Sales staff regularly travel and submit hotel, flights, and meal receipts monthly.',
  },
  {
    id: 'p2p.expenses.expenseCategories',
    flow: 'P2P',
    section: 'expenses',
    order: 2,
    inputType: 'TABLE',
    required: false,
    label: 'List the main expense categories employees claim (category name and the GL account it maps to).',
    helpTitle: 'Why does this matter?',
    helpBody: 'Expense categories map to specific GL accounts for correct financial reporting.',
    exampleText: 'Row 1: Air Travel — T&E. Row 2: Hotel — T&E. Row 3: Client Meals — Business Development. Row 4: Transport — T&E.',
    dependsOn: { questionId: 'p2p.expenses.employeeExpenses', value: true },
  },
  {
    id: 'p2p.expenses.expenseApproval',
    flow: 'P2P',
    section: 'expenses',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Do expense claims need to be approved by a line manager before payment?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite routes expense reports to the employee\'s manager by default but can be customised for multi-level approval.',
    exampleText: 'Each expense report goes to the direct manager; amounts over AED 5,000 also require Finance sign-off.',
    dependsOn: { questionId: 'p2p.expenses.employeeExpenses', value: true },
  },
  {
    id: 'p2p.expenses.corporateCards',
    flow: 'P2P',
    section: 'expenses',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company issue corporate credit or charge cards to employees?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Corporate cards require a statement reconciliation process where transactions are matched against expense reports or coded directly.',
    exampleText: 'Senior managers have corporate Amex cards. Monthly statements are imported and reconciled against receipts.',
  },
  {
    id: 'p2p.expenses.perDiemPolicy',
    flow: 'P2P',
    section: 'expenses',
    order: 5,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use fixed per diem rates for travel (set daily allowances rather than actual receipt amounts)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Per diem rates simplify expense processing — employees claim a fixed daily rate. Needs to be configured as expense rate rules in NetSuite.',
    exampleText: 'Staff travelling to Saudi Arabia receive AED 800/day flat allowance covering meals and incidentals.',
  },
  {
    id: 'p2p.expenses.mileageReimbursement',
    flow: 'P2P',
    section: 'expenses',
    order: 6,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company reimburse staff for using personal vehicles for business travel, based on distance driven?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Mileage reimbursement requires a per-kilometre rate in expense settings. Employees enter distance and the system calculates the reimbursement.',
    exampleText: 'Field engineers use personal cars and claim AED 0.30 per kilometre driven for business purposes.',
  },
];
