import type { Question } from './types.js';

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

export const r2rQuestions: Question[] = [
  // ── SECTION: entities ────────────────────────────────────────────────────
  {
    id: 'r2r.entities.multiEntity',
    flow: 'R2R',
    section: 'entities',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does this company have more than one legal entity — for example, a parent company with subsidiaries, or branches registered in different countries?',
    helpTitle: 'Why does this matter?',
    helpBody: 'If the company has multiple legal entities, the system needs to be set up to manage each one separately while still providing a combined financial view. This is the most fundamental structural decision in the entire implementation — it affects everything else.',
    exampleText: 'Acme Group has three companies: Acme UAE (the parent), Acme Saudi Arabia, and Acme Egypt. They are all separate legal entities but owned by the same group.',
    consultantNote: 'YES → Requires OneWorld license. In NS, go to Setup → Company → Subsidiaries and create a subsidiary record for each entity. Each subsidiary needs its own chart of accounts segment, base currency, and fiscal calendar. Budget 1-2 extra days of setup per additional entity.',
  },
  {
    id: 'r2r.entities.entityCount',
    flow: 'R2R',
    section: 'entities',
    order: 2,
    inputType: 'NUMBER',
    required: true,
    label: 'How many legal entities need to be set up in the system?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Each entity needs its own chart of accounts, currency settings, and period structure. Knowing the count helps plan how much setup time is needed and whether OneWorld licensing is required.',
    exampleText: 'Acme Group has 3 entities, so we will create 3 separate company records in NetSuite.',
    consultantNote: 'NS OneWorld is priced per subsidiary. Confirm with the account manager that the license covers the count here. If the count is 10+, discuss the "Unlimited Subsidiaries" tier. Also verify if any are inactive (historical) subsidiaries that still need to be migrated but won\'t transact going forward.',
    dependsOn: { questionId: 'r2r.entities.multiEntity', value: true },
  },
  {
    id: 'r2r.entities.intercompanyJE',
    flow: 'R2R',
    section: 'entities',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Will the company need to record transactions between its own entities — such as intercompany loans, cost allocations, or shared service charges?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Intercompany transactions require special journal entries that automatically create a matching entry in the other entity. This needs the OneWorld module and affects how the chart of accounts is structured.',
    exampleText: 'Acme UAE charges Acme Saudi Arabia a monthly management fee of $10,000. This needs to appear as income in UAE and an expense in Saudi Arabia.',
    consultantNote: 'YES → Enable "Intercompany Journal Entries" under Setup → Accounting → Accounting Preferences. You must create "Intercompany Payable" and "Intercompany Receivable" accounts in every subsidiary\'s chart of accounts. NS auto-creates the offsetting entry when you post. Ask the client who approves intercompany JEs — this is often an audit issue.',
    dependsOn: { questionId: 'r2r.entities.multiEntity', value: true },
  },
  {
    id: 'r2r.entities.subsidiaryNames',
    flow: 'R2R',
    section: 'entities',
    order: 4,
    inputType: 'TABLE',
    required: false,
    label: 'List each legal entity: name, country of registration, and base currency.',
    helpTitle: 'Why does this matter?',
    helpBody: 'We use this list to create the subsidiary records in NetSuite. Each entity needs its own name, country, and currency configuration. This information will be used directly in the SDF deployment package.',
    exampleText: 'Row 1: Acme UAE, United Arab Emirates, AED. Row 2: Acme KSA, Saudi Arabia, SAR.',
    consultantNote: 'Use the exact legal entity name (as registered) — this appears on all official documents. Country determines which local tax features NS enables (e.g., VAT for UAE, Zakat/VAT for KSA). Base currency cannot be changed after go-live, so double-check with the CFO before proceeding.',
    dependsOn: { questionId: 'r2r.entities.multiEntity', value: true },
  },

  // ── SECTION: segmentation ─────────────────────────────────────────────────
  {
    id: 'r2r.segmentation.useDepartments',
    flow: 'R2R',
    section: 'segmentation',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company track income and expenses by department — for example, Sales, Operations, Finance, or HR?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Departments are a financial dimension that allows the company to see a profit and loss view for each part of the business. Once enabled, most transactions will require a department to be selected.',
    exampleText: 'The company wants to know how much the Marketing department spent last month versus the Sales department.',
    consultantNote: 'YES → Enable at Setup → Company → Enable Features → Accounting → Departments. Then create department records at Lists → Accounting → Departments. If YES, add a "Department" column to all major transaction forms (SO, PO, JE). Warn the client: making department mandatory is irreversible once transactions exist — plan the list carefully before go-live.',
  },
  {
    id: 'r2r.segmentation.departmentList',
    flow: 'R2R',
    section: 'segmentation',
    order: 2,
    inputType: 'TABLE',
    required: false,
    label: 'List the departments that need to be created (name and any parent department if it has one).',
    helpTitle: 'Why does this matter?',
    helpBody: 'We create each department as a record in NetSuite. If departments have a hierarchy — for example, Inside Sales and Field Sales both roll up to Sales — we need to know the parent-child relationships.',
    exampleText: 'Sales, Operations, Finance, Human Resources, Information Technology.',
    dependsOn: { questionId: 'r2r.segmentation.useDepartments', value: true },
  },
  {
    id: 'r2r.segmentation.useClasses',
    flow: 'R2R',
    section: 'segmentation',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need to track financial data by business line, product line, or project type?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Classes are a flexible financial dimension — they can represent product lines, projects, business units, or any grouping that does not fit neatly into a department structure. Companies often use Classes alongside Departments.',
    exampleText: 'A professional services firm tracks revenue separately for Consulting, Training, and Managed Services.',
  },
  {
    id: 'r2r.segmentation.useLocations',
    flow: 'R2R',
    section: 'segmentation',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company have multiple physical locations — offices, warehouses, or retail sites — that need to be reported on separately?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Locations allow the company to see financial and inventory reports broken down by physical site. This is separate from subsidiaries — a single legal entity can have multiple locations.',
    exampleText: 'The company has a head office in Dubai, a warehouse in Jebel Ali, and a showroom in Abu Dhabi.',
  },
  {
    id: 'r2r.segmentation.locationList',
    flow: 'R2R',
    section: 'segmentation',
    order: 5,
    inputType: 'TABLE',
    required: false,
    label: 'List the locations that need to be created (name and address).',
    helpTitle: 'Why does this matter?',
    helpBody: 'Location records are used on transactions, inventory, and reports. They also drive inventory availability calculations across sites.',
    exampleText: 'Dubai Head Office (Sheikh Zayed Road), Jebel Ali Warehouse, Abu Dhabi Showroom.',
    dependsOn: { questionId: 'r2r.segmentation.useLocations', value: true },
  },

  // ── SECTION: accountingPeriods ─────────────────────────────────────────────
  {
    id: 'r2r.accountingPeriods.fiscalYearStart',
    flow: 'R2R',
    section: 'accountingPeriods',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: MONTHS.map(m => ({ value: m, label: m, description: `Fiscal year begins in ${m}` })),
    label: 'Which month does the company\'s financial year start?',
    helpTitle: 'Why does this matter?',
    helpBody: 'NetSuite creates all accounting periods based on the fiscal year start month. This cannot easily be changed after the system is live, so it must be confirmed with the company\'s finance team.',
    exampleText: 'Most companies in the UAE use a January fiscal year start. Companies with a UK parent often use April.',
    consultantNote: 'This is set at company creation. In NS, go to Setup → Accounting → Manage Accounting Periods → Set Up Year and Period Dates. Once you post any transaction, changing the fiscal year start requires a support ticket and is often not possible without data loss. Always confirm in writing with the CFO.',
  },
  {
    id: 'r2r.accountingPeriods.periodType',
    flow: 'R2R',
    section: 'accountingPeriods',
    order: 2,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'MONTHLY', label: 'Monthly', description: '12 periods per year — most common' },
      { value: 'QUARTERLY', label: 'Quarterly', description: '4 periods per year — simpler but less granular' },
      { value: 'MONTHLY_QUARTERLY', label: 'Monthly with quarterly rollups', description: 'Monthly periods that roll into quarters and an annual period' },
    ],
    label: 'How often does the company close its books?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This determines how accounting periods are created in NetSuite. Monthly periods give the most flexibility for reporting and are the standard for most businesses.',
    exampleText: 'Most mid-size companies close monthly. Small businesses sometimes close quarterly.',
    consultantNote: 'Always recommend Monthly — it gives the most reporting flexibility and is required if the client wants monthly budgeting. Quarterly is only suitable for very simple businesses. After go-live, you can always choose not to close a period early, but you cannot retroactively add monthly periods if you started with quarterly.',
  },
  {
    id: 'r2r.accountingPeriods.lockClosedPeriods',
    flow: 'R2R',
    section: 'accountingPeriods',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Should closed accounting periods be locked so that no one can post transactions back into them?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Locking periods is a financial control that prevents accidental or unauthorized changes to already-reported figures. Most companies with audited financials require this.',
    exampleText: 'Once March is closed and reported to management, no one should be able to post a March journal entry in April.',
    consultantNote: 'YES is the best-practice answer for any audited company. In NS, locking is done at Setup → Accounting → Manage Accounting Periods → Lock. Users with the "Override Period Restrictions" permission can still post to locked periods — you must carefully manage who gets this permission. Typically only the Finance Manager should have it.',
  },
  {
    id: 'r2r.accountingPeriods.adjustmentPeriods',
    flow: 'R2R',
    section: 'accountingPeriods',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use adjustment periods at year end for audit or closing entries?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Some companies create a 13th accounting period at year end for audit adjustments. This allows auditors to post entries without reopening regular periods.',
    exampleText: 'The auditors request several adjusting entries in January after the December close. An adjustment period allows these to be posted as December entries.',
    consultantNote: 'YES → NetSuite supports year-end adjustment periods natively. Enable "Year End Adjustment Periods" at Setup → Accounting Preferences. Create the adjustment period when setting up the fiscal year. Note: adjustment period entries do NOT appear in regular P&L reports unless you specifically include them — warn the client so they don\'t miss them in their month-end review.',
  },

  // ── SECTION: currencies ───────────────────────────────────────────────────
  {
    id: 'r2r.currencies.baseCurrency',
    flow: 'R2R',
    section: 'currencies',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'AED', label: 'AED — UAE Dirham', description: 'United Arab Emirates' },
      { value: 'SAR', label: 'SAR — Saudi Riyal', description: 'Saudi Arabia' },
      { value: 'USD', label: 'USD — US Dollar', description: 'United States' },
      { value: 'EUR', label: 'EUR — Euro', description: 'European Union' },
      { value: 'GBP', label: 'GBP — British Pound', description: 'United Kingdom' },
      { value: 'EGP', label: 'EGP — Egyptian Pound', description: 'Egypt' },
      { value: 'OTHER', label: 'Other', description: 'Specify in the notes' },
    ],
    label: 'What is the company\'s primary reporting currency — the currency that all financial statements are produced in?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The base currency is set at company creation and cannot be changed after transactions are posted. All other currencies are converted to the base currency for reporting.',
    exampleText: 'A company headquartered in Dubai typically uses AED as the base currency even if most transactions are in USD.',
    consultantNote: 'BASE CURRENCY CANNOT BE CHANGED AFTER GO-LIVE. This is one of the most critical decisions in the implementation. Get written sign-off from the CFO. In NS, this is set at Setup → Company → Company Information → Base Currency. If a multi-entity client wants consolidated reports in USD but each entity has its own base currency, that is handled by OneWorld consolidation — the base currency of each subsidiary is still their own local currency.',
  },
  {
    id: 'r2r.currencies.isMultiCurrency',
    flow: 'R2R',
    section: 'currencies',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company transact in more than one currency — for example, paying suppliers in USD while reporting in AED?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Multi-currency requires additional setup including exchange rates, revaluation runs, and more complex bank reconciliation. It also requires a Mid-Market or OneWorld NetSuite licence.',
    exampleText: 'The company buys goods from suppliers who invoice in USD and EUR, but reports to shareholders in AED.',
    consultantNote: 'YES → Enable at Setup → Company → Enable Features → Multi-Currency. You must then: (1) add active currencies at Lists → Accounting → Currencies, (2) configure exchange rate types (spot vs. average), (3) schedule monthly currency revaluation runs, (4) create unrealised/realised gain-loss accounts in the CoA. Budget 0.5 extra days for multi-currency setup and train the finance team on the revaluation process.',
  },
  {
    id: 'r2r.currencies.additionalCurrencies',
    flow: 'R2R',
    section: 'currencies',
    order: 3,
    inputType: 'MULTI_SELECT',
    required: false,
    options: [
      { value: 'USD', label: 'USD — US Dollar', description: '' },
      { value: 'EUR', label: 'EUR — Euro', description: '' },
      { value: 'GBP', label: 'GBP — British Pound', description: '' },
      { value: 'AED', label: 'AED — UAE Dirham', description: '' },
      { value: 'SAR', label: 'SAR — Saudi Riyal', description: '' },
      { value: 'EGP', label: 'EGP — Egyptian Pound', description: '' },
      { value: 'CAD', label: 'CAD — Canadian Dollar', description: '' },
      { value: 'AUD', label: 'AUD — Australian Dollar', description: '' },
      { value: 'JPY', label: 'JPY — Japanese Yen', description: '' },
      { value: 'CNY', label: 'CNY — Chinese Yuan', description: '' },
    ],
    label: 'Which additional currencies will the company use for transactions?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Each currency selected will be set up with an exchange rate schedule and enabled on vendor, customer, and bank account records. Only select currencies that will actually appear on transactions.',
    exampleText: 'The company pays suppliers in USD and EUR, and has a bank account in GBP.',
    dependsOn: { questionId: 'r2r.currencies.isMultiCurrency', value: true },
  },
  {
    id: 'r2r.currencies.autoExchangeRateUpdate',
    flow: 'R2R',
    section: 'currencies',
    order: 4,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should exchange rates be updated automatically from a live feed, or will they be entered manually by the finance team?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Automatic exchange rate updates require Mid-Market or OneWorld edition and a scheduled script. Manual rates give more control but require someone to update them regularly.',
    exampleText: 'The treasury team prefers to set their own exchange rates each Monday morning rather than use a live feed.',
    dependsOn: { questionId: 'r2r.currencies.isMultiCurrency', value: true },
  },
  {
    id: 'r2r.currencies.revaluationRequired',
    flow: 'R2R',
    section: 'currencies',
    order: 5,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Does the company need to revalue foreign currency balances at period end — adjusting for exchange rate movements on open receivables, payables, and bank accounts?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Currency revaluation is an accounting requirement under most international standards (IFRS, US GAAP). It creates unrealized gain/loss journal entries at period end to reflect the current exchange rate on open balances.',
    exampleText: 'The company has a $100,000 USD receivable on the books at 3.67 AED. If the rate changes to 3.69 AED by month end, a revaluation entry is needed.',
    dependsOn: { questionId: 'r2r.currencies.isMultiCurrency', value: true },
  },

  // ── SECTION: bankTransactions ─────────────────────────────────────────────
  {
    id: 'r2r.bankTransactions.bankAccountCount',
    flow: 'R2R',
    section: 'bankTransactions',
    order: 1,
    inputType: 'NUMBER',
    required: true,
    label: 'How many bank accounts does the company have that need to be tracked in the system?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Each bank account is set up as a record in NetSuite linked to a GL account. The count helps plan the chart of accounts structure and bank reconciliation workflow.',
    exampleText: 'The company has 4 accounts: an AED current account, a USD current account, a payroll account, and a petty cash account.',
  },
  {
    id: 'r2r.bankTransactions.reconciliationFrequency',
    flow: 'R2R',
    section: 'bankTransactions',
    order: 2,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'DAILY', label: 'Daily', description: 'Reconcile every business day' },
      { value: 'WEEKLY', label: 'Weekly', description: 'Reconcile once a week' },
      { value: 'MONTHLY', label: 'Monthly', description: 'Reconcile at period close — most common' },
    ],
    label: 'How often will bank accounts be reconciled against bank statements?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Bank reconciliation frequency affects how the system is configured for bank statement imports and who needs access to the reconciliation screens.',
    exampleText: 'Most companies reconcile monthly as part of their period close process. High-volume businesses may reconcile weekly.',
  },
  {
    id: 'r2r.bankTransactions.importBankFeeds',
    flow: 'R2R',
    section: 'bankTransactions',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Will bank statement data be imported electronically (CSV upload or bank feed), or will transactions be entered manually?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Electronic bank statement import significantly reduces reconciliation time. We need to know in advance to configure the import format and set up the matching rules.',
    exampleText: 'The finance team downloads a CSV from the bank\'s online portal each month and uploads it to NetSuite.',
  },
  {
    id: 'r2r.bankTransactions.hasOpeningBalances',
    flow: 'R2R',
    section: 'bankTransactions',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company have existing bank balances that need to be entered as opening balances on the go-live date?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Opening bank balances are entered as a journal entry on the go-live date to establish the starting position in the new system. These need to match the closing balance from the old system.',
    exampleText: 'On 1 January, the company\'s AED account had AED 250,000. This balance needs to appear in NetSuite from day one.',
  },
  {
    id: 'r2r.bankTransactions.openingBalanceDate',
    flow: 'R2R',
    section: 'bankTransactions',
    order: 5,
    inputType: 'DATE',
    required: false,
    label: 'What is the cutover date — the date from which opening balances will be entered?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The opening balance date is the first date that transactions will be recorded in NetSuite. It is usually the first day of a new accounting period.',
    exampleText: '1 January 2025 — all balances as of 31 December 2024 are entered as opening entries.',
    dependsOn: { questionId: 'r2r.bankTransactions.hasOpeningBalances', value: true },
  },

  // ── SECTION: tax ──────────────────────────────────────────────────────────
  {
    id: 'r2r.tax.taxRegime',
    flow: 'R2R',
    section: 'tax',
    order: 1,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'VAT', label: 'VAT (Value Added Tax)', description: 'Standard VAT system — UAE, UK, Europe' },
      { value: 'GST', label: 'GST (Goods and Services Tax)', description: 'Australia, India, Canada' },
      { value: 'SALES_TAX', label: 'Sales Tax', description: 'US state-based sales tax' },
      { value: 'ZAKAT', label: 'Zakat (Saudi Arabia)', description: 'Saudi Arabian corporate tax' },
      { value: 'NONE', label: 'No tax', description: 'Company does not charge or pay tax' },
      { value: 'MULTIPLE', label: 'Multiple tax regimes', description: 'Company operates across multiple tax jurisdictions' },
    ],
    label: 'Which tax system does the company operate under?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The tax system determines which NetSuite tax features to enable and how tax codes are structured. Different regions have different tax rules that need to be reflected in the configuration.',
    exampleText: 'A UAE company uses VAT at 5%. A Saudi company uses Zakat. A US company uses state-based sales tax.',
  },
  {
    id: 'r2r.tax.vatRate',
    flow: 'R2R',
    section: 'tax',
    order: 2,
    inputType: 'NUMBER',
    required: false,
    label: 'What is the standard VAT or GST rate as a percentage (e.g. enter 5 for 5%)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The standard rate is set up as the default tax code and applied automatically to most transactions. Reduced rates and exempt codes are added separately.',
    exampleText: 'UAE VAT is 5%. UK VAT is 20%. Saudi VAT is 15%.',
  },
  {
    id: 'r2r.tax.multipleRates',
    flow: 'R2R',
    section: 'tax',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company use multiple tax rates — for example, different rates for different products or services, or zero-rated and exempt categories?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Multiple tax rates require multiple tax codes to be set up. Common examples include a standard rate, a zero rate for exports, and an exempt code for financial services.',
    exampleText: 'The company charges 5% VAT on most products but 0% on exported goods and has some exempt financial transactions.',
  },
  {
    id: 'r2r.tax.taxCodeList',
    flow: 'R2R',
    section: 'tax',
    order: 4,
    inputType: 'TABLE',
    required: false,
    label: 'List each tax code needed: code name, rate percentage, and what it applies to.',
    helpTitle: 'Why does this matter?',
    helpBody: 'Each tax code becomes a selectable option on transactions. Clear naming makes it easy for the accounts team to pick the correct code when entering bills and invoices.',
    exampleText: 'SR (Standard Rate 5%), ZR (Zero Rate 0% — Exports), EX (Exempt — Financial Services).',
    dependsOn: { questionId: 'r2r.tax.multipleRates', value: true },
  },
  {
    id: 'r2r.tax.taxRegistrationNumber',
    flow: 'R2R',
    section: 'tax',
    order: 5,
    inputType: 'TEXT',
    required: false,
    label: 'What is the company\'s tax registration number (TRN, VAT number, or equivalent)?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The tax registration number is printed on tax invoices and must match the number registered with the tax authority. It is required on all compliant invoices.',
    exampleText: 'UAE TRN example: 100123456789003',
  },

  // ── SECTION: journalEntries ───────────────────────────────────────────────
  {
    id: 'r2r.journalEntries.manualJEsRequired',
    flow: 'R2R',
    section: 'journalEntries',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Will the accounting team need to post manual journal entries — for example, for accruals, prepayments, or corrections?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Manual journal entries are used for adjustments that cannot be made through standard transactions. Enabling them requires setting up the correct roles and permissions.',
    exampleText: 'At month end, the accountant posts an accrual for utilities that have been consumed but not yet invoiced.',
  },
  {
    id: 'r2r.journalEntries.approvalRequired',
    flow: 'R2R',
    section: 'journalEntries',
    order: 2,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should manual journal entries require approval from a manager before they are posted to the ledger?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Approval workflows on journal entries are a key financial control. They ensure that a second person reviews any manual adjustment before it affects the books.',
    exampleText: 'The company requires the Finance Manager to approve all journal entries above AED 10,000 before they are posted.',
    dependsOn: { questionId: 'r2r.journalEntries.manualJEsRequired', value: true },
  },
  {
    id: 'r2r.journalEntries.approverRoles',
    flow: 'R2R',
    section: 'journalEntries',
    order: 3,
    inputType: 'MULTI_SELECT',
    required: false,
    options: [
      { value: 'FINANCE_MANAGER', label: 'Finance Manager', description: 'First-level approver for most JEs' },
      { value: 'CFO', label: 'CFO', description: 'Required for high-value or sensitive entries' },
      { value: 'CONTROLLER', label: 'Financial Controller', description: 'Alternative to Finance Manager' },
      { value: 'DIRECTOR', label: 'Finance Director', description: 'Senior approval for material entries' },
    ],
    label: 'Which roles can approve journal entries?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The approval workflow is set up to route journal entries to users with these roles. Users without these roles will not be able to approve entries, even if they have journal entry access.',
    exampleText: 'Entries up to AED 50,000 are approved by the Finance Manager. Entries above AED 50,000 go to the CFO.',
    dependsOn: { questionId: 'r2r.journalEntries.approvalRequired', value: true },
  },
  {
    id: 'r2r.journalEntries.recurringJEs',
    flow: 'R2R',
    section: 'journalEntries',
    order: 4,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company have recurring monthly journal entries — such as depreciation, prepayment amortisation, or fixed monthly accruals?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Recurring journal entries can be templated in NetSuite so they are automatically created each period. This reduces manual work and the risk of forgetting a regular entry.',
    exampleText: 'Every month, the same depreciation entry of AED 15,000 is posted. A template means it is created automatically and just needs to be reviewed and posted.',
  },

  // ── SECTION: fiscalClose ──────────────────────────────────────────────────
  {
    id: 'r2r.fiscalClose.hasCloseChecklist',
    flow: 'R2R',
    section: 'fiscalClose',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company follow a formal period close checklist with tasks assigned to different people?',
    helpTitle: 'Why does this matter?',
    helpBody: 'A period close checklist ensures every required step is completed before the period is locked. NetSuite can replicate this checklist with task assignments and completion tracking.',
    exampleText: 'The close checklist includes: post depreciation, reconcile all bank accounts, review aged receivables, post accruals, get CFO sign-off.',
  },
  {
    id: 'r2r.fiscalClose.closeTaskCount',
    flow: 'R2R',
    section: 'fiscalClose',
    order: 2,
    inputType: 'NUMBER',
    required: false,
    label: 'Approximately how many tasks are on the period close checklist?',
    helpTitle: 'Why does this matter?',
    helpBody: 'The number of tasks affects how long it takes to set up the close checklist in the system and helps estimate the complexity of the month-end workflow.',
    exampleText: 'A typical close checklist has 10-25 tasks. Complex multi-entity companies can have 50+.',
    dependsOn: { questionId: 'r2r.fiscalClose.hasCloseChecklist', value: true },
  },
  {
    id: 'r2r.fiscalClose.closeApprovalRequired',
    flow: 'R2R',
    section: 'fiscalClose',
    order: 3,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Should the period close require formal sign-off from the Finance Manager or CFO before the period is locked?',
    helpTitle: 'Why does this matter?',
    helpBody: 'A close approval workflow means the Finance Manager or CFO must actively confirm that the period is ready to close. This is a key governance control for financial reporting.',
    exampleText: 'The CFO must review the trial balance and click "Approve Close" before February can be locked and March opened.',
  },
  {
    id: 'r2r.fiscalClose.autoLockAfterApproval',
    flow: 'R2R',
    section: 'fiscalClose',
    order: 4,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should the system automatically lock the period once the close is approved, preventing any further transaction postings?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Auto-lock ensures that once the period is signed off, no one can accidentally post into it. Without auto-lock, someone would need to manually lock each period.',
    exampleText: 'When the CFO approves the February close, the system automatically locks February so no further entries can be posted.',
  },

  // ── SECTION: reporting ────────────────────────────────────────────────────
  {
    id: 'r2r.reporting.standardReportsRequired',
    flow: 'R2R',
    section: 'reporting',
    order: 1,
    inputType: 'MULTI_SELECT',
    required: true,
    options: [
      { value: 'BALANCE_SHEET', label: 'Balance Sheet', description: 'Assets, liabilities, and equity at a point in time' },
      { value: 'PL', label: 'P&L / Income Statement', description: 'Revenue and expenses over a period' },
      { value: 'TRIAL_BALANCE', label: 'Trial Balance', description: 'All GL account balances' },
      { value: 'CASH_FLOW', label: 'Cash Flow Statement', description: 'Sources and uses of cash' },
      { value: 'CONSOLIDATED', label: 'Consolidated Financials', description: 'Combined view across all entities' },
      { value: 'BUDGET_VS_ACTUAL', label: 'Budget vs Actual', description: 'Variance analysis against plan' },
    ],
    label: 'Which standard financial reports does the company need from the system?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Standard reports are pre-built in NetSuite and just need to be verified against the chart of accounts. Custom reports require additional build time. Knowing which standard reports are needed guides the chart of accounts design.',
    exampleText: 'The board requires a Balance Sheet, P&L, and Budget vs Actual every month. The auditors require a Cash Flow Statement at year end.',
  },
  {
    id: 'r2r.reporting.customReportsRequired',
    flow: 'R2R',
    section: 'reporting',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company need reports that go beyond the standard NetSuite financial reports — for example, custom management packs or KPI dashboards?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Custom reports are built as Saved Searches or custom financial report layouts. Each custom report adds to the implementation scope and needs to be specified in detail.',
    exampleText: 'Management wants a weekly gross margin report by product line that is not available as a standard NetSuite report.',
  },
  {
    id: 'r2r.reporting.customReportDescriptions',
    flow: 'R2R',
    section: 'reporting',
    order: 3,
    inputType: 'TABLE',
    required: false,
    label: 'Describe each custom report needed: report name, data it shows, and who uses it.',
    helpTitle: 'Why does this matter?',
    helpBody: 'A clear description lets us scope the build effort for each custom report and identify which ones are feasible within the implementation timeline.',
    exampleText: 'Weekly Gross Margin by Product — shows revenue, COGS, and margin % per product line — used by the CEO.',
    dependsOn: { questionId: 'r2r.reporting.customReportsRequired', value: true },
  },
  {
    id: 'r2r.reporting.managementPackFrequency',
    flow: 'R2R',
    section: 'reporting',
    order: 4,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'MONTHLY', label: 'Monthly', description: 'Management pack produced every month' },
      { value: 'QUARTERLY', label: 'Quarterly', description: 'Produced every quarter' },
      { value: 'NOT_REQUIRED', label: 'Not required', description: 'No regular management pack produced' },
    ],
    label: 'How often does the company produce a formal management reporting pack for the board or owners?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Understanding the management reporting cadence helps design the report layout and ensure the chart of accounts captures all the data points needed for the pack.',
    exampleText: 'The board meets monthly and requires a management pack with P&L, balance sheet, cash flow, and KPIs by the 10th working day of the following month.',
  },
  {
    id: 'r2r.reporting.consolidationRequired',
    flow: 'R2R',
    section: 'reporting',
    order: 5,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Does the company need consolidated financial statements that combine all legal entities into a single group view?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Consolidated reporting combines the financials of all subsidiaries, eliminating intercompany balances, to give a group-level view. This requires OneWorld and careful intercompany configuration.',
    exampleText: 'The board wants to see a single P&L and balance sheet for the entire Acme Group, not just individual entities.',
    dependsOn: { questionId: 'r2r.entities.multiEntity', value: true },
  },
];
