import type { Question } from './types.js';
// Placeholder — import type { Question } from './types.js';

export const rtnQuestions: Question[] = [
  // ── SECTION: customerReturns ──────────────────────────────────────────────
  {
    id: 'rtn.customerReturns.useRMA',
    flow: 'RETURNS',
    section: 'customerReturns',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company require a Return Merchandise Authorization (RMA) to be created before a customer can return a product?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Using RMAs ensures that every return is authorized and tracked. It also allows the warehouse to know what is coming back so they can prepare for the receipt.',
    exampleText: 'A customer calls support, and the support agent creates an RMA in NetSuite. The customer then ships the product back with the RMA number on the box.',
  },
  {
    id: 'rtn.customerReturns.refundPolicy',
    flow: 'RETURNS',
    section: 'customerReturns',
    order: 2,
    inputType: 'SINGLE_SELECT',
    required: true,
    options: [
      { value: 'REFUND_AFTER_RECEIPT', label: 'Refund after receipt', description: 'Credit memo or refund is only issued once the item is received and inspected.' },
      { value: 'REFUND_BEFORE_RECEIPT', label: 'Refund immediately', description: 'Credit is issued as soon as the RMA is created (e.g. for high-value customers).' },
      { value: 'REPLACEMENT_ONLY', label: 'Replacement only', description: 'The company does not issue refunds, only sends a replacement product.' },
    ],
    label: 'What is the standard refund policy for customer returns?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This determines the sequence of transactions in NetSuite. "Refund after receipt" is much safer for inventory and financial accuracy.',
    exampleText: 'We don\'t pay the customer back until we check that the phone they returned isn\'t actually broken by them.',
  },
  {
    id: 'rtn.customerReturns.returnWindow',
    flow: 'RETURNS',
    section: 'customerReturns',
    order: 3,
    inputType: 'NUMBER',
    required: false,
    label: 'How many days after delivery does the company allow customers to initiate a return?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Standard windows are 30, 60, or 90 days. This is used in the RMA creation rules.',
    exampleText: '30',
  },
  {
    id: 'rtn.customerReturns.returnShippingResponsibility',
    flow: 'RETURNS',
    section: 'customerReturns',
    order: 4,
    inputType: 'SINGLE_SELECT',
    required: false,
    label: 'Who is responsible for return shipping costs?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Return shipping responsibility affects customer satisfaction and affects the financial impact of returns.',
    exampleText: 'For non-faulty returns, the customer pays for return shipping.',
    options: [
      { value: 'CUSTOMER_PAYS', label: 'Customer pays return shipping', description: 'The customer covers the cost of returning the item.' },
      { value: 'COMPANY_PAYS', label: 'Company provides return shipping label', description: 'The company prepays return shipping via a label or carrier account.' },
      { value: 'CASE_BY_CASE', label: 'Decided case by case', description: 'Return shipping responsibility varies by customer type, item, or reason for return.' },
    ],
  },
  {
    id: 'rtn.customerReturns.creditNoteAutoGenerate',
    flow: 'RETURNS',
    section: 'customerReturns',
    order: 5,
    inputType: 'BOOLEAN',
    required: false,
    label: 'Should a Credit Note be automatically generated when a customer return is accepted and goods are received?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Automatic credit notes reduce manual data entry and ensure refunds are processed consistently.',
    exampleText: 'When a returned item is received and passed QA inspection, the system automatically creates a Credit Memo for the customer.',
  },

  // ── SECTION: vendorReturns ────────────────────────────────────────────────
  {
    id: 'rtn.vendorReturns.useVendorRMA',
    flow: 'RETURNS',
    section: 'vendorReturns',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company follow a formal Vendor RMA process when returning faulty raw materials or stock to suppliers?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Vendor RMAs track what is being sent back to the supplier and ensure that the company receives the correct credit or replacement from the vendor.',
    exampleText: 'We found 100 broken valves in the delivery. We create a Vendor RMA in NetSuite to track the return to the factory.',
  },

  // ── SECTION: processing ───────────────────────────────────────────────────
  {
    id: 'rtn.processing.inspectionRequired',
    flow: 'RETURNS',
    section: 'processing',
    order: 1,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Is a formal quality inspection required for all returned items before they can be added back to sellable stock?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This adds a step to the warehouse flow. If enabled, returned items are received into a "Quarantine" location or status and must be "Released" by a QA user.',
    exampleText: 'Every returned laptop must be turned on and checked for data wipes before it can be sold as "Renewed".',
  },
  {
    id: 'rtn.processing.restockingFees',
    flow: 'RETURNS',
    section: 'processing',
    order: 2,
    inputType: 'BOOLEAN',
    required: true,
    label: 'Does the company charge restocking fees for non-faulty returns?',
    helpTitle: 'Why does this matter?',
    helpBody: 'Restocking fees require a specific non-inventory item and automated calculation logic (usually a percentage of the original price) on the Credit Memo.',
    exampleText: 'If you return a working camera just because you changed your mind, we deduct 15% from your refund.',
  },
  {
    id: 'rtn.processing.feePercentage',
    flow: 'RETURNS',
    section: 'processing',
    order: 3,
    inputType: 'NUMBER',
    required: false,
    label: 'What is the standard restocking fee percentage?',
    helpTitle: 'Why does this matter?',
    helpBody: 'This value is used to default the fee amount on the return transaction.',
    exampleText: '15',
    dependsOn: { questionId: 'rtn.processing.restockingFees', value: true },
  },
];
