import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import type * as dbModule from '../db/index.js';
import { generateBRD, generateBRDHtml, type AdaptorContext } from './generators/brdGenerator.js';
import { getAdaptorRegistry } from '@ofoq/adaptor-registry';
import { generateSDFPackage } from './generators/sdfGenerator.js';
import { validateSDFBundle, isValidationEnabled } from './generators/sdfValidator.js';
import { generateScripts } from './generators/scriptGenerator.js';
import { generateRiskRegister } from './generators/riskGenerator.js';
import { generateUATPlan, generateUATPlanHtml } from './generators/uatGenerator.js';
import { generateSolutionDoc, generateSolutionDocHtml } from './generators/solutionDocGenerator.js';
import { generateTrainingManual, generateTrainingManualHtml } from './generators/trainingManualGenerator.js';
import { generateImplementationPlanHtml } from './generators/planGenerator.js';
import { generateOdooConfigurationPlan, generateOdooConfigurationPlanHtml } from './generators/odooConfigurationPlanGenerator.js';
import { convertHtmlToPdf } from './pdfService.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type DbModule = typeof dbModule;

/**
 * Resolve the engagement's adaptorId + selected edition into the prose
 * context every generator consumes. Built-in shape per adaptor:
 *
 *   netsuite  — preserves the existing "NetSuite Mid-Market" edition
 *               prefix the pilot deck has used and the SDF deployment
 *               package hand-off voice.
 *   odoo      — bare edition label ("Community" or "Enterprise") and
 *               a generic "configuration package" hand-off until the
 *               Odoo Configuration Plan generator lands (Phase 4 of
 *               the cross-platform fix).
 *   custom:*  — fall-through default. Adaptor name comes from the
 *               registry; if the adaptor isn't registered we Capitalize
 *               the adaptorId so the prose still reads cleanly.
 */
function buildAdaptorContext(adaptorId: string, editionId: string): AdaptorContext {
  const adaptor = getAdaptorRegistry().find(adaptorId);
  const adaptorName = adaptor?.manifest.name ?? capitalize(adaptorId.replace(/^custom:/, ''));
  const editionDef = adaptor?.license?.editions.find((e) => e.id === editionId);
  const bareEdition = editionDef?.label ?? editionId;

  // Adaptor-driven flow tree — each generator iterates this to render
  // wizard answers grouped by flow + section. Replaces the hardcoded
  // r2r/p2p/o2c/mfg/rtn list that only worked for NetSuite-style keys
  // and produced an empty Workstream Requirements section for every
  // Odoo engagement.
  const flows = (adaptor?.schema?.flows ?? []).map((f) => ({
    id: f.id,
    label: f.label,
    description: f.description,
    sections: f.sections.map((s) => ({
      id: s.id,
      label: s.label,
      order: s.order,
      questions: s.questions.map((q) => ({
        id: q.id,
        label: q.label,
        inputType: q.inputType,
        options: q.options,
      })),
    })),
  }));

  if (adaptorId === 'netsuite') {
    return {
      id: 'netsuite',
      name: 'NetSuite',
      // Pilot voice: prefix the platform name onto the edition so the
      // header reads "NetSuite Mid-Market". Other adaptors get the bare
      // label — that's the convention the BRD test contract enforces.
      editionLabel: `NetSuite ${bareEdition}`,
      consultantQualifier: 'NetSuite',
      nextStepLanguage:
        'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
      flows,
    };
  }

  if (adaptorId === 'odoo') {
    return {
      id: 'odoo',
      name: 'Odoo',
      editionLabel: bareEdition,
      consultantQualifier: 'Odoo',
      // Refined wording (PO sign-off): Odoo doesn't ship a single deployment
      // artifact like NetSuite SDF. The post-Discovery hand-off is a module
      // install plan + l10n_<country> localization + (optional) Studio XML
      // exports. This phrasing previews the Phase-4 odooConfigurationPlan
      // generator while staying honest about what comes next on Odoo.
      nextStepLanguage:
        'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
      flows,
    };
  }

  // Fall-through for custom: adaptors. Capitalize(adaptorId) covers the
  // case where the registry hasn't been queried yet (offline test path);
  // adaptor.manifest.name is preferred when available.
  return {
    id: adaptorId,
    name: adaptorName,
    editionLabel: bareEdition,
    consultantQualifier: adaptorName,
    nextStepLanguage: `the ${adaptorName} build phase using the configuration package generated by ERPLaunch`,
    flows,
  };
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

/**
 * Generation pipeline — Phase 6: adaptor-aware
 *
 * Branches on the engagement's adaptor:
 *   - NetSuite (built-in): emits the full pack the pilot always produced —
 *     BRD + Risk Register + UAT + Solution Design + Training + Plan PLUS
 *     the NetSuite-only SDF package and SuiteScript scaffolds.
 *   - Everything else (Odoo, published custom adaptors): emits the
 *     platform-neutral document pack only. SDF / SuiteScript are NetSuite
 *     artifacts and would be meaningless against an Odoo or in-house system,
 *     so the runner skips them and lets the catalog decide which other
 *     documents land in the bundle.
 *
 * This is a pragmatic first cut — the six "document" generators already
 * work off clientName + answers + comments + images + aiAdvice with no
 * NetSuite-specific data, so they can run against any adaptor. A later
 * phase can replace the static calls with a dispatch table keyed on
 * generator id when more adaptor-native generators (Odoo .po modules,
 * Dynamics extensions, etc.) arrive.
 */
export async function processJob(jobId: string, db: DbModule) {
  try {
    await db.updateJob(jobId, { status: 'RUNNING' });

    const job = await db.findJobById(jobId) as Record<string, any> | null;
    if (!job) return;

    const eng = await db.findEngagementById(job.engagementId as string) as Record<string, any> | null;
    if (!eng) return;

    const adaptorId = (eng.adaptorId as string | undefined) ?? 'netsuite';
    const isNetSuite = adaptorId === 'netsuite';

    const rootOutputDir = path.join(__dirname, '..', '..', 'outputs', jobId);
    const docDir = path.join(rootOutputDir, 'Documentation');
    await fs.mkdir(docDir, { recursive: true });

    const license = (eng.license ?? {}) as Record<string, any>;
    const profile = (eng.profile ?? {}) as Record<string, any>;
    const answers = profile.answers ?? {};

    // Load rich content (comments, images, AI advice)
    const comments = await db.getSectionComments(eng.id);
    const images = await db.getSectionImages(eng.id);
    const aiAdvice = await db.getAllAIAdvice(eng.id);

    // ── 1. Platform-neutral document pack (runs for every adaptor) ──────────
    const editionId = (license.edition as string | undefined)
      ?? (isNetSuite ? 'MID_MARKET' : 'DEFAULT');
    const adaptorCtx = buildAdaptorContext(adaptorId, editionId);

    const brdData = {
      clientName: eng.clientName as string,
      adaptor: adaptorCtx,
      license: {
        edition: editionId,
        modules: license.modules ?? [],
      },
      answers,
      comments,
      images,
      aiAdvice,
    };

    await fs.writeFile(path.join(docDir, 'BRD.md'), generateBRD(brdData));
    const brdHtml = generateBRDHtml(brdData);
    await fs.writeFile(path.join(docDir, 'BRD.html'), brdHtml);
    await convertHtmlToPdf(brdHtml, path.join(docDir, 'BRD.pdf'));

    const riskContent = generateRiskRegister({
      clientName: eng.clientName as string,
      conflicts: eng.conflicts?.filter((c: any) => c.severity === 'BLOCK') ?? [],
      warnings: eng.conflicts?.filter((c: any) => c.severity === 'WARN') ?? [],
    });
    await fs.writeFile(path.join(docDir, 'Risk_Register.md'), riskContent);

    const uatData = { clientName: eng.clientName as string, adaptor: adaptorCtx, answers, comments, images, aiAdvice };
    await fs.writeFile(path.join(docDir, 'UAT_Plan.md'), generateUATPlan(uatData));
    await fs.writeFile(path.join(docDir, 'UAT_Plan.html'), generateUATPlanHtml(uatData));

    const sddData = {
      clientName: eng.clientName as string,
      adaptor: adaptorCtx,
      license: brdData.license,
      answers,
      conflicts: eng.conflicts ?? [],
      comments,
      images,
      aiAdvice,
    };
    await fs.writeFile(path.join(docDir, 'Solution_Design.html'), generateSolutionDocHtml(sddData));

    const trainingData = { clientName: eng.clientName as string, adaptor: adaptorCtx, answers, comments, images, aiAdvice };
    await fs.writeFile(path.join(docDir, 'Training_Manual.html'), generateTrainingManualHtml(trainingData));

    await fs.writeFile(
      path.join(docDir, 'Implementation_Plan.html'),
      generateImplementationPlanHtml({
        clientName: eng.clientName as string,
        adaptor: adaptorCtx,
        license: brdData.license,
        answers,
        conflicts: eng.conflicts ?? [],
      }),
    );

    // ── 2. NetSuite-only artifacts: SDF + SuiteScript ───────────────────────
    if (isNetSuite) {
      const sdfDir = path.join(rootOutputDir, 'SDF');
      const ssDir = path.join(rootOutputDir, 'SuiteScript');
      await fs.mkdir(sdfDir, { recursive: true });
      await fs.mkdir(ssDir, { recursive: true });

      const { files: sdfFiles } = generateSDFPackage({
        modules: license.modules ?? [],
        answers,
        clientName: eng.clientName as string,
      });

      // Phase 8: structural SDF validation gate. Fails the job loudly if any
      // generated XML file would be rejected by Oracle's schema — catches
      // regressions to Fixes #1–#6 before they ever hit disk. Default on;
      // opt out with SDF_VALIDATE=0 for local debugging only.
      if (isValidationEnabled()) {
        const validation = validateSDFBundle(sdfFiles);
        if (!validation.ok) {
          const payload = JSON.stringify(validation.errors, null, 2);
          throw new Error(`SDF validation failed with ${validation.errors.length} error(s):\n${payload}`);
        }
      }

      for (const [relPath, content] of Object.entries(sdfFiles)) {
        const fullPath = path.join(sdfDir, relPath);
        await fs.mkdir(path.dirname(fullPath), { recursive: true });
        await fs.writeFile(fullPath, content);
      }

      const scriptFiles = generateScripts({
        clientName: eng.clientName as string,
        answers,
        modules: license.modules ?? [],
      });
      for (const [filename, content] of Object.entries(scriptFiles)) {
        await fs.writeFile(path.join(ssDir, filename), content);
      }
    } else {
      // ── 2b. Non-NetSuite build artefact: Configuration Plan ────────────────
      // Replaces the NetSuite-only SDF + SuiteScript bundle for Odoo and any
      // future / firm-authored adaptor (custom:*). Module install plan,
      // l10n_<country> localisation, fiscal year setup, and multi-company
      // checklist — the concrete steps the consultant takes after Discovery
      // sign-off on a non-NetSuite platform.
      const configPlanData = {
        clientName: eng.clientName as string,
        adaptor: adaptorCtx,
        license: brdData.license,
        answers,
        comments,
        images,
        aiAdvice,
      };
      await fs.writeFile(
        path.join(docDir, 'Configuration_Plan.md'),
        generateOdooConfigurationPlan(configPlanData),
      );
      await fs.writeFile(
        path.join(docDir, 'Configuration_Plan.html'),
        generateOdooConfigurationPlanHtml(configPlanData),
      );
    }

    // ── 3. Manifest: record which artifacts actually landed ─────────────────
    const manifest = {
      jobId,
      engagementId: eng.id as string,
      adaptorId,
      clientName: eng.clientName as string,
      completedAt: new Date().toISOString(),
      artifacts: {
        documentation: [
          'BRD.md', 'BRD.html', 'BRD.pdf',
          'Risk_Register.md',
          'UAT_Plan.md', 'UAT_Plan.html',
          'Solution_Design.html',
          'Training_Manual.html',
          'Implementation_Plan.html',
          ...(isNetSuite ? [] : ['Configuration_Plan.md', 'Configuration_Plan.html']),
        ],
        ...(isNetSuite ? { sdf: 'SDF/', suiteScript: 'SuiteScript/' } : {}),
      },
    };
    await fs.writeFile(path.join(rootOutputDir, 'manifest.json'), JSON.stringify(manifest, null, 2));

    // ── 4. Mark job complete ────────────────────────────────────────────────
    await db.updateJob(jobId, {
      status: 'COMPLETE',
      outputUrl: `/outputs/${jobId}`,
      completedAt: new Date().toISOString(),
    });

    if (process.env.NODE_ENV !== 'production') {
      console.log(`Job ${jobId} complete (adaptor=${adaptorId}). Artifacts generated in ${rootOutputDir}`);
    }
  } catch (error) {
    console.error(`[generation] Job ${jobId} failed:`, error);
    await db.updateJob(jobId, { status: 'FAILED', error: String(error) });
  }
}
