import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Build a minimal valid PDF containing the document title and a note that
 * the full HTML version is available alongside this file.
 * Uses raw PDF 1.4 syntax — no external dependencies.
 */
function buildFallbackPdf(html: string, outputPath: string): string {
  const baseName = path.basename(outputPath, '.pdf');
  const titleMatch = html.match(/<h1[^>]*>([^<]+)<\/h1>/i);
  const title = titleMatch ? titleMatch[1] : baseName;

  const lines = [
    `%PDF-1.4`,
    `1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj`,
    `2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj`,
    `3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj`,
  ];

  const textLines = [
    title,
    '',
    'This PDF was generated as a placeholder because Chromium is not',
    'available in the current environment. The complete styled version',
    `is available in the accompanying HTML file: ${baseName}.html`,
    '',
    `Generated by Ofoq NetSuite Accelerator`,
  ];

  const streamLines: string[] = [];
  streamLines.push('BT');
  streamLines.push('/F1 16 Tf');
  streamLines.push('50 780 Td');
  streamLines.push('14 TL');
  textLines.forEach((line, i) => {
    const safe = line.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
    if (i === 0) {
      streamLines.push(`(${safe}) Tj`);
    } else {
      streamLines.push(`T*`);
      streamLines.push(`(${safe}) Tj`);
    }
  });
  streamLines.push('ET');
  const stream = streamLines.join('\n');

  lines.push(`4 0 obj<</Length ${stream.length}>>`);
  lines.push('stream');
  lines.push(stream);
  lines.push('endstream');
  lines.push('endobj');
  lines.push(`5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj`);

  const body = lines.join('\n') + '\n';
  const xrefOffset = body.length;
  const xref = [
    'xref',
    '0 6',
    '0000000000 65535 f ',
    `${String(body.indexOf('1 0 obj')).padStart(10, '0')} 00000 n `,
    `${String(body.indexOf('2 0 obj')).padStart(10, '0')} 00000 n `,
    `${String(body.indexOf('3 0 obj')).padStart(10, '0')} 00000 n `,
    `${String(body.indexOf('4 0 obj')).padStart(10, '0')} 00000 n `,
    `${String(body.indexOf('5 0 obj')).padStart(10, '0')} 00000 n `,
    'trailer<</Size 6/Root 1 0 R>>',
    'startxref',
    String(xrefOffset),
    '%%EOF',
  ].join('\n');

  return body + xref;
}

/**
 * Convert HTML to PDF using Puppeteer (lazy-loaded so server boots without Chromium).
 * Falls back to writing the raw HTML if Puppeteer or Chromium is unavailable.
 */
export async function convertHtmlToPdf(html: string, outputPath: string): Promise<void> {
  try {
    // Dynamic import — server starts even if puppeteer/chromium is missing
    const puppeteer = await import('puppeteer').then((m) => m.default ?? m);

    const browser = await (puppeteer as any).launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });

      await page.pdf({
        path: outputPath,
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
      });
    } finally {
      await browser.close();
    }
  } catch {
    // Puppeteer unavailable — write a minimal single-page PDF using raw PDF syntax
    // so the .pdf file is always present in the output package.
    try {
      const pdfContent = buildFallbackPdf(html, outputPath);
      await fs.writeFile(outputPath, pdfContent, 'binary');
      console.warn(`[pdfService] Puppeteer unavailable — wrote text-based PDF fallback at ${outputPath}`);
    } catch {
      // Last resort: save HTML with .pdf extension so the file exists
      await fs.writeFile(outputPath, html);
      console.warn(`[pdfService] PDF fallback failed — saved raw HTML at ${outputPath}`);
    }
  }
}
