/**
 * Cutover Team Roster generator (Pack V — Component 7b).
 *
 * Cross-platform — emits Documentation/Cutover/Cutover_Team_Roster.md.
 *
 * Renders the on-call schedule + comms channel + coverage validation
 * checklist. Roster comes from cutover.team.cutoverTeamRoster (one
 * line per member, 3 colon-separated segments).
 */

export interface CutoverTeamRosterGeneratorInput {
  clientName: string;
  adaptorName?: string;
  /** TEXTAREA cutover.team.cutoverTeamRoster. */
  cutoverTeamRoster?: string | null;
  /** TEXT kickoff.mandate.targetGoLiveDate. */
  targetGoLiveDate?: string | null;
}

export interface CutoverTeamRosterGeneratorOutput {
  markdown: string;
}

interface ParsedRosterRow {
  name: string;
  role: string;
  onCallWindow: string;
}

function parseRoster(raw: string): ParsedRosterRow[] {
  const out: ParsedRosterRow[] = [];
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;
    const firstColon = trimmed.indexOf(':');
    if (firstColon < 0) continue;
    const name = trimmed.slice(0, firstColon).trim();
    const rest = trimmed.slice(firstColon + 1).trim();
    const secondColon = rest.indexOf(':');
    if (secondColon < 0) {
      out.push({ name, role: rest, onCallWindow: '' });
      continue;
    }
    out.push({
      name,
      role: rest.slice(0, secondColon).trim(),
      onCallWindow: rest.slice(secondColon + 1).trim(),
    });
  }
  return out;
}

export function generateCutoverTeamRoster(
  input: CutoverTeamRosterGeneratorInput,
): CutoverTeamRosterGeneratorOutput {
  const platform = (input.adaptorName ?? '').toString();
  const platformLabel = platform.length > 0 ? platform : 'ERP';
  const roster = parseRoster((input.cutoverTeamRoster ?? '').toString());
  const slug = input.clientName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

  const rosterRows =
    roster.length === 0
      ? '| _[ASSIGN]_ | _[ASSIGN]_ | _[ASSIGN]_ | _______ | _______ |'
      : roster
          .map(
            (r) =>
              `| ${r.name} | ${r.role} | ${r.onCallWindow.length > 0 ? r.onCallWindow : '_[ASSIGN window]_'} | _______ | _______ |`,
          )
          .join('\n');

  const markdown = [
    `# Cutover Team Roster — ${input.clientName}`,
    '',
    `**Platform:** ${platformLabel}  `,
    `**Target Go-Live:** ${input.targetGoLiveDate ?? 'TBD'}  `,
    `**Roster Size:** ${roster.length || '_[ASSIGN]_'}  `,
    `**Date prepared:** ${new Date().toLocaleDateString()}`,
    '',
    'On-call schedule for the cutover weekend. Every name on this roster is reachable ',
    'within their stated on-call window. Phone numbers + backup contacts are filled in ',
    'at T-7 days during the final cutover huddle.',
    '',
    '## 1. On-Call Schedule',
    '',
    '| Name | Role | On-Call Window | Phone | Backup |',
    '|------|------|----------------|-------|--------|',
    rosterRows,
    '',
    '## 2. Communication Channel',
    '',
    `- **Slack channel:** \`#cutover-${slug}\` (or engagement equivalent)`,
    '- **Bridge line:** _______________ (provisioned at T-3 days, tested at T-1 days)',
    '- **Status board:** _______________ (Confluence / SharePoint / engagement portal)',
    '',
    '## 3. Coverage Validation Checklist',
    '',
    '- [ ] 24h coverage confirmed across the entire cutover window',
    '- [ ] At least 2 people awake at all times (rotating overnight if window > 18h)',
    '- [ ] Backup contacts identified for each primary',
    '- [ ] All phone numbers tested 24h before T+0:00',
    '- [ ] Slack channel access tested (every member can post + read)',
    '- [ ] Bridge line tested (audio works for all members)',
    '- [ ] Escalation paths reviewed (per `Documentation/Cutover/Communication_Plan.md`)',
    '',
    '## 4. Roles + Responsibilities Quick-Reference',
    '',
    '| Role | Primary Responsibility |',
    '|------|------------------------|',
    '| Consultant PM | Overall command + go/no-go declarations + escalation owner |',
    '| Client PM | Client-side coordination + sponsor communications |',
    '| Migration Lead | Owns extract / transform / load + tie-out validation |',
    '| IT Lead | Production access + snapshot management + integrations |',
    '| Functional Lead(s) | Per-workstream smoke + sign-off on workstream readiness |',
    '| Power Users | Available for ad-hoc validation + first-day support |',
    '',
    '## 5. Cross-References',
    '',
    '- Cutover Runbook: `Documentation/Cutover/Cutover_Runbook.md`',
    '- Communication Plan: `Documentation/Cutover/Communication_Plan.md`',
    '- Go/No-Go Matrix: `Documentation/Cutover/Go_No_Go_Matrix.md`',
    '',
    '_Generated by ERPLaunch — Pack V (Cutover Runbook)._',
    '',
  ].join('\n');

  return { markdown };
}
