export interface ScriptData {
  clientName: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON-blob answers; see brdGenerator BRDData.
  answers: Record<string, any>;
  modules: string[];
}

/** Helper: look up a flat dot-key answer (e.g. 'r2r.fiscalClose.autoLockAfterApproval') — fixed v2 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- generic JSON-blob lookup; return widens at the per-question call site.
function ans(answers: Record<string, any>, key: string): any {
  return answers[key];
}

/**
 * Phase 7 banner. Prepended to every generated .js file so a developer
 * opening the bundle sees immediately that the handlers are stubs. The
 * exact text is mirrored byte-for-byte in scriptAndSolutionDoc.test.ts —
 * edit one, edit the other.
 */
const STARTER_SCAFFOLDING_BANNER = `/**
 * ⚠ STARTER SCAFFOLDING — NOT A WORKING IMPLEMENTATION
 * The handler bodies below are intentionally empty. A NetSuite
 * developer must implement the logic before this file is deployed.
 */`;

export function generateScripts(data: ScriptData): Record<string, string> {
  const { clientName, answers, modules } = data;
  const files: Record<string, string> = {};

  // 1. Always generate: UserEvent Script
  const userEventScript = `/**
 * @NApiVersion 2.1
 * @NScriptType UserEventScript
 * @NModuleScope SameAccount
 *
 * Client: ${clientName}
 * Generated by: Ofoq NetSuite Accelerator
 */

define(['N/log', 'N/record'], (log, record) => {

    const beforeLoad = (scriptContext) => {
        log.debug({
            title: 'Before Load',
            details: 'Initialized for ${clientName}'
        });
    };

    const beforeSubmit = (scriptContext) => {
        // Placeholder for ${clientName} business logic
    };

    const afterSubmit = (scriptContext) => {
        // Placeholder for ${clientName} triggers
    };

    return {
        beforeLoad,
        beforeSubmit,
        afterSubmit
    };
});`;

  files['NSIX_UE_CustomisationBase.js'] = userEventScript;

  // 2. Conditional: Period Close Scheduled Script
  const autoLockAfterApproval = ans(answers, 'r2r.fiscalClose.autoLockAfterApproval') === true;
  const lockClosedPeriods = ans(answers, 'r2r.accountingPeriods.lockClosedPeriods') === true;

  if (autoLockAfterApproval || lockClosedPeriods) {
    const periodCloseScript = `/**
 * @NApiVersion 2.1
 * @NScriptType ScheduledScript
 * @NModuleScope SameAccount
 * Client: ${clientName}
 * Purpose: Automates period-close validation and lock enforcement
 * Generated by: Ofoq NetSuite Accelerator
 */
define(['N/log', 'N/record', 'N/search', 'N/runtime'], (log, record, search, runtime) => {
    const execute = (scriptContext) => {
        log.audit({ title: 'Period Close', details: 'Starting period close validation for ${clientName}' });
        // TODO: Add period-close validation logic
        // 1. Check for unposted transactions in current period
        // 2. Validate all approvals are complete
        // 3. Lock period if all checks pass
        log.audit({ title: 'Period Close', details: 'Period close validation complete' });
    };
    return { execute };
});`;

    files['NSIX_SS_PeriodClose.js'] = periodCloseScript;
  }

  // 3. Conditional: Integration Endpoint RESTlet
  const isCurrencyMulti = ans(answers, 'r2r.currencies.isMultiCurrency') === true;
  const hasAdvancedInventory = modules.includes('ADVANCED_INVENTORY');

  if (isCurrencyMulti || hasAdvancedInventory) {
    const restletScript = `/**
 * @NApiVersion 2.1
 * @NScriptType Restlet
 * @NModuleScope SameAccount
 * Client: ${clientName}
 * Purpose: REST integration endpoint for external system connectivity
 * Generated by: Ofoq NetSuite Accelerator
 */
define(['N/log', 'N/record', 'N/search', 'N/https'], (log, record, search, https) => {
    const get = (requestParams) => {
        log.debug({ title: 'RESTlet GET', details: JSON.stringify(requestParams) });
        return JSON.stringify({ status: 'ok', client: '${clientName}', params: requestParams });
    };
    const post = (requestBody) => {
        log.debug({ title: 'RESTlet POST', details: JSON.stringify(requestBody) });
        // TODO: Implement inbound data processing
        return JSON.stringify({ status: 'received', client: '${clientName}' });
    };
    return { get, post };
});`;

    files['NSIX_RL_IntegrationEndpoint.js'] = restletScript;
  }

  // 4. Conditional: Form Validation Client Script
  const poApprovalRequired = ans(answers, 'p2p.purchasing.poApprovalRequired') === true;
  const creditLimits = ans(answers, 'o2c.customers.creditLimits') === true;

  if (poApprovalRequired || creditLimits) {
    const clientScript = `/**
 * @NApiVersion 2.1
 * @NScriptType ClientScript
 * @NModuleScope SameAccount
 * Client: ${clientName}
 * Purpose: Client-side form validation for approval and credit limit workflows
 * Generated by: Ofoq NetSuite Accelerator
 */
define(['N/currentRecord', 'N/log', 'N/ui/dialog'], (currentRecord, log, dialog) => {
    const saveRecord = (scriptContext) => {
        const rec = scriptContext.currentRecord;
        // PO approval threshold check
        const amount = rec.getValue({ fieldId: 'amount' }) || 0;
        if (amount > 10000) {
            dialog.alert({ title: 'Approval Required', message: 'This transaction exceeds the approval threshold and requires manager sign-off.' });
        }
        return true;
    };
    const fieldChanged = (scriptContext) => {
        log.debug({ title: 'Field Changed', details: scriptContext.fieldId });
    };
    return { saveRecord, fieldChanged };
});`;

    files['NSIX_CS_FormValidation.js'] = clientScript;
  }

  // Phase 6 note: we previously emitted an NSIX_WF_ApprovalChain.xml here
  // based on bill/PO approval triggers. The XML used a SOAP webservices
  // namespace and a <sendemailaction> shape that SDF rejects outright —
  // Oracle's own guidance is explicit: author workflows in the NetSuite UI
  // and export via SDF, don't hand-write them. The approval flow is now
  // described in prose in the Solution Design document so the consultant
  // can build it in the UI before deploy.

  // Phase 7: prepend the scaffolding banner to every .js file. Done at the
  // end of the function — one pass over the file map instead of touching
  // every individual template literal above, so future handlers pick up
  // the banner automatically with no extra wiring.
  for (const name of Object.keys(files)) {
    if (name.endsWith('.js')) {
      files[name] = `${STARTER_SCAFFOLDING_BANNER}\n${files[name]}`;
    }
  }

  return files;
}
