export interface ScriptData {
  clientName: string;
  answers: Record<string, any>;
  modules: string[];
}

/** Helper: look up a flat dot-key answer (e.g. 'r2r.fiscalClose.autoLockAfterApproval') — fixed v2 */
function ans(answers: Record<string, any>, key: string): any {
  return answers[key];
}

export function generateScripts(data: ScriptData): Record<string, string> {
  const { clientName, answers, modules } = data;
  const files: Record<string, string> = {};

  // 1. Always generate: UserEvent Script
  const userEventScript = `/**
 * @NApiVersion 2.1
 * @NScriptType UserEventScript
 * @NModuleScope SameAccount
 *
 * Client: ${clientName}
 * Generated by: Ofoq NetSuite Accelerator
 */

define(['N/log', 'N/record'], (log, record) => {

    const beforeLoad = (scriptContext) => {
        log.debug({
            title: 'Before Load',
            details: 'Initialized for ${clientName}'
        });
    };

    const beforeSubmit = (scriptContext) => {
        // Placeholder for ${clientName} business logic
    };

    const afterSubmit = (scriptContext) => {
        // Placeholder for ${clientName} triggers
    };

    return {
        beforeLoad,
        beforeSubmit,
        afterSubmit
    };
});`;

  files['NSIX_UE_CustomisationBase.js'] = userEventScript;

  // 2. Conditional: Period Close Scheduled Script
  const autoLockAfterApproval = ans(answers, 'r2r.fiscalClose.autoLockAfterApproval') === true;
  const lockClosedPeriods = ans(answers, 'r2r.accountingPeriods.lockClosedPeriods') === true;

  if (autoLockAfterApproval || lockClosedPeriods) {
    const periodCloseScript = `/**
 * @NApiVersion 2.1
 * @NScriptType ScheduledScript
 * @NModuleScope SameAccount
 * Client: ${clientName}
 * Purpose: Automates period-close validation and lock enforcement
 * Generated by: Ofoq NetSuite Accelerator
 */
define(['N/log', 'N/record', 'N/search', 'N/runtime'], (log, record, search, runtime) => {
    const execute = (scriptContext) => {
        log.audit({ title: 'Period Close', details: 'Starting period close validation for ${clientName}' });
        // TODO: Add period-close validation logic
        // 1. Check for unposted transactions in current period
        // 2. Validate all approvals are complete
        // 3. Lock period if all checks pass
        log.audit({ title: 'Period Close', details: 'Period close validation complete' });
    };
    return { execute };
});`;

    files['NSIX_SS_PeriodClose.js'] = periodCloseScript;
  }

  // 3. Conditional: Integration Endpoint RESTlet
  const isCurrencyMulti = ans(answers, 'r2r.currencies.isMultiCurrency') === true;
  const hasAdvancedInventory = modules.includes('ADVANCED_INVENTORY');

  if (isCurrencyMulti || hasAdvancedInventory) {
    const restletScript = `/**
 * @NApiVersion 2.1
 * @NScriptType Restlet
 * @NModuleScope SameAccount
 * Client: ${clientName}
 * Purpose: REST integration endpoint for external system connectivity
 * Generated by: Ofoq NetSuite Accelerator
 */
define(['N/log', 'N/record', 'N/search', 'N/https'], (log, record, search, https) => {
    const get = (requestParams) => {
        log.debug({ title: 'RESTlet GET', details: JSON.stringify(requestParams) });
        return JSON.stringify({ status: 'ok', client: '${clientName}', params: requestParams });
    };
    const post = (requestBody) => {
        log.debug({ title: 'RESTlet POST', details: JSON.stringify(requestBody) });
        // TODO: Implement inbound data processing
        return JSON.stringify({ status: 'received', client: '${clientName}' });
    };
    return { get, post };
});`;

    files['NSIX_RL_IntegrationEndpoint.js'] = restletScript;
  }

  // 4. Conditional: Form Validation Client Script
  const poApprovalRequired = ans(answers, 'p2p.purchasing.poApprovalRequired') === true;
  const creditLimits = ans(answers, 'o2c.customers.creditLimits') === true;

  if (poApprovalRequired || creditLimits) {
    const clientScript = `/**
 * @NApiVersion 2.1
 * @NScriptType ClientScript
 * @NModuleScope SameAccount
 * Client: ${clientName}
 * Purpose: Client-side form validation for approval and credit limit workflows
 * Generated by: Ofoq NetSuite Accelerator
 */
define(['N/currentRecord', 'N/log', 'N/ui/dialog'], (currentRecord, log, dialog) => {
    const saveRecord = (scriptContext) => {
        const rec = scriptContext.currentRecord;
        // PO approval threshold check
        const amount = rec.getValue({ fieldId: 'amount' }) || 0;
        if (amount > 10000) {
            dialog.alert({ title: 'Approval Required', message: 'This transaction exceeds the approval threshold and requires manager sign-off.' });
        }
        return true;
    };
    const fieldChanged = (scriptContext) => {
        log.debug({ title: 'Field Changed', details: scriptContext.fieldId });
    };
    return { saveRecord, fieldChanged };
});`;

    files['NSIX_CS_FormValidation.js'] = clientScript;
  }

  // 5. Conditional: Approval Chain Workflow
  const billApprovalRequired = ans(answers, 'p2p.bills.billApprovalRequired') === true;

  if (billApprovalRequired || poApprovalRequired) {
    const workflowXml = `<?xml version="1.0" encoding="UTF-8"?>
<workflow
  name="NSIX Approval Chain"
  recordtype="vendorbill"
  runasadmin="F"
  initoncreate="T"
  inittriggerdefinition="BEFORESUBMIT"
  xmlns="urn:workflow.webservices.netsuite.com">
  <initcondition>
    <formula>true</formula>
  </initcondition>
  <workflowstates>
    <workflowstate name="Pending Approval" positionx="100" positiony="100">
      <workflowactions triggertype="ONENTRY">
        <sendemailaction>
          <recipient type="ROLE" role="3"/>
          <subject>Approval Required: ${clientName} Bill Pending</subject>
          <body>A new vendor bill requires your approval. Please review in NetSuite.</body>
        </sendemailaction>
      </workflowactions>
      <workflowtransitions>
        <workflowtransition tostate="Approved">
          <initcondition>
            <formula>{{custbody_nsix_je_approval_status}} = 'Approved'</formula>
          </initcondition>
        </workflowtransition>
        <workflowtransition tostate="Rejected">
          <initcondition>
            <formula>{{custbody_nsix_je_approval_status}} = 'Rejected'</formula>
          </initcondition>
        </workflowtransition>
      </workflowtransitions>
    </workflowstate>
    <workflowstate name="Approved" positionx="300" positiony="100">
      <workflowactions triggertype="ONENTRY">
        <setfieldvalueaction>
          <field name="approvalstatus" value="2"/>
        </setfieldvalueaction>
      </workflowactions>
    </workflowstate>
    <workflowstate name="Rejected" positionx="300" positiony="200">
      <workflowactions triggertype="ONENTRY">
        <setfieldvalueaction>
          <field name="approvalstatus" value="3"/>
        </setfieldvalueaction>
      </workflowactions>
    </workflowstate>
  </workflowstates>
</workflow>`;

    files['NSIX_WF_ApprovalChain.xml'] = workflowXml;
  }

  return files;
}
