/**
 * SDF Accounting Preferences generator (Pack C — Roles + Permissions
 * + Account Preferences).
 *
 * Emits a single Oracle SDF `accountingpreferences.xml` to the
 * SDF/AccountConfiguration/ folder. Drives NetSuite account-level
 * accounting preferences (period-lock policy, multi-book on/off,
 * ARM on/off, etc.) from the foundation + design wizard answers.
 *
 * Scope: only the preferences that flip on a wizard flag are
 * declared. Defaults that NetSuite ships with don't appear — the
 * deploy will leave them alone, which is the correct behaviour for
 * an Account Customization Project that's adjusting + not
 * fully-replacing tenant configuration.
 *
 * Sources:
 *   - NetSuite SDF AccountConfiguration / accountingpreferences XML
 *     reference (Oracle Help — SuiteCloud Development Framework XML
 *     Reference).
 */

export interface AccountingPreferencesInput {
  /** ns.foundation.multiBookAccounting — drives multibookaccountingenabled
   *  + restrictbookaccess. */
  multiBookAccounting?: boolean;
  /** ns.foundation.advancedRevRecInScope — drives armenabled. */
  advancedRevRecInScope?: boolean;
  /** ns.design.sodMatrixRequired — drives forceperiodlock (SoD-aware
   *  engagements lock periods automatically once approved). */
  sodMatrixRequired?: boolean;
}

export function generateAccountingPreferences(
  input: AccountingPreferencesInput,
): string {
  const tFlag = (b: boolean | undefined): 'T' | 'F' => (b === true ? 'T' : 'F');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by ERPLaunch Account Preferences Generator from wizard
  foundation + design answers.
  Drives NetSuite account-level accounting preferences. Review and
  adjust per client policy before deploy.
-->
<accountingpreferences>
  <maintaincurrentbalance>T</maintaincurrentbalance>
  <forceperiodlock>${tFlag(input.sodMatrixRequired)}</forceperiodlock>
  <multibookaccountingenabled>${tFlag(input.multiBookAccounting)}</multibookaccountingenabled>
  <armenabled>${tFlag(input.advancedRevRecInScope)}</armenabled>
  <enableallowedauthorizations>T</enableallowedauthorizations>
  <restrictbookaccess>${tFlag(input.multiBookAccounting)}</restrictbookaccess>
  <enableaccountnumbers>T</enableaccountnumbers>
</accountingpreferences>
`;
}
