/**
 * SDF Currency generator (Pack A — OneWorld Foundation).
 *
 * Emits one Oracle SDF `currency` XML per ISO 4217 code that appears
 * in the engagement's subsidiary list. Without these files the
 * subsidiaries reference currency codes that don't exist on the
 * tenant — SDF deploy fails immediately.
 *
 * Caller passes a deduplicated array of ISO 4217 codes (extract via
 * `extractCurrenciesFromSubsidiaries` from the subsidiary generator).
 * Each code → one XML with a name + symbol from a built-in lookup
 * table. Unknown codes get name = symbol = the code itself (the
 * consultant fixes manually post-generation).
 *
 * Sources:
 *   - NetSuite SDF currency XML reference (Oracle docs).
 *   - ISO 4217 currency code list.
 */

export interface CurrencyGeneratorInput {
  /** Array of uppercased ISO 4217 codes. Duplicates are tolerated
   *  (deduped internally) but the orchestrator should already have
   *  deduplicated before passing in. */
  currencies: string[];
}

export interface EmittedCurrency {
  filename: string;
  scriptid: string;
  iso: string;
  name: string;
  symbol: string;
}

export interface CurrencyGeneratorOutput {
  files: Record<string, string>;
  emitted: EmittedCurrency[];
}

interface CurrencyMeta {
  name: string;
  symbol: string;
}

/**
 * ISO 4217 → display name + symbol lookup. Codes not in the map fall
 * back to {name: <code>, symbol: <code>} — valid SDF, just less
 * polished output than the curated set.
 */
const CURRENCY_META: Record<string, CurrencyMeta> = {
  USD: { name: 'US Dollar', symbol: '$' },
  EUR: { name: 'Euro', symbol: '€' },
  GBP: { name: 'British Pound', symbol: '£' },
  AED: { name: 'UAE Dirham', symbol: 'AED' },
  SAR: { name: 'Saudi Riyal', symbol: 'SAR' },
  EGP: { name: 'Egyptian Pound', symbol: 'EGP' },
  AUD: { name: 'Australian Dollar', symbol: 'A$' },
  CAD: { name: 'Canadian Dollar', symbol: 'C$' },
  JPY: { name: 'Japanese Yen', symbol: '¥' },
  CNY: { name: 'Chinese Yuan', symbol: '¥' },
  INR: { name: 'Indian Rupee', symbol: '₹' },
  CHF: { name: 'Swiss Franc', symbol: 'CHF' },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$' },
  SGD: { name: 'Singapore Dollar', symbol: 'S$' },
  ZAR: { name: 'South African Rand', symbol: 'R' },
  NGN: { name: 'Nigerian Naira', symbol: '₦' },
  KES: { name: 'Kenyan Shilling', symbol: 'KSh' },
  BHD: { name: 'Bahraini Dinar', symbol: 'BHD' },
  QAR: { name: 'Qatari Riyal', symbol: 'QAR' },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'KWD' },
  OMR: { name: 'Omani Rial', symbol: 'OMR' },
  JOD: { name: 'Jordanian Dinar', symbol: 'JOD' },
  LBP: { name: 'Lebanese Pound', symbol: 'LBP' },
};

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function buildCurrencyXml(args: {
  scriptid: string;
  iso: string;
  name: string;
  symbol: string;
}): string {
  const escapedName = xmlEscape(args.name);
  const escapedSymbol = xmlEscape(args.symbol);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by ERPLaunch Currency Generator. ISO 4217: ${args.iso}.
  Verify exchange-rate provider + base-currency designation in NetSuite UI before deploy.
-->
<currency scriptid="${args.scriptid}">
  <name>${escapedName}</name>
  <symbol>${escapedSymbol}</symbol>
  <isbasecurrency>F</isbasecurrency>
  <isinactive>F</isinactive>
  <displaysymbol>${escapedSymbol}</displaysymbol>
  <symbolplacement>_BEFORENUMBER</symbolplacement>
  <currencyprecision>2</currencyprecision>
</currency>
`;
}

/**
 * Emit one currency XML per ISO code. Empty input → empty output.
 * Deduplication + uppercasing applied defensively.
 */
export function generateCurrencies(input: CurrencyGeneratorInput): CurrencyGeneratorOutput {
  const files: Record<string, string> = {};
  const emitted: EmittedCurrency[] = [];

  const seen = new Set<string>();
  for (const codeRaw of input.currencies) {
    const iso = (codeRaw ?? '').trim().toUpperCase();
    if (!/^[A-Z]{3}$/.test(iso)) continue; // drop garbage
    if (seen.has(iso)) continue;
    seen.add(iso);

    const meta = CURRENCY_META[iso] ?? { name: iso, symbol: iso };
    const scriptid = `currency_${iso.toLowerCase()}`;
    const filename = `Objects/${scriptid}.xml`;
    files[filename] = buildCurrencyXml({
      scriptid,
      iso,
      name: meta.name,
      symbol: meta.symbol,
    });
    emitted.push({ filename, scriptid, iso, name: meta.name, symbol: meta.symbol });
  }

  return { files, emitted };
}
