/**
 * SDF Company Information generator (Pack C — Roles + Permissions
 * + Account Preferences).
 *
 * Emits a single Oracle SDF `companyinformation.xml` to the
 * SDF/AccountConfiguration/ folder. Captures the engagement's legal
 * name, country, base currency, and fiscal year start — the
 * top-level identity an SDF deploy stamps on a fresh tenant.
 *
 * Base currency is inferred from the FIRST subsidiary parsed from
 * ns.foundation.subsidiaryList (the root tenant subsidiary). Other
 * subsidiaries' currencies land via the Pack A currency generator;
 * companyinformation only carries one base.
 *
 * Sources:
 *   - NetSuite SDF AccountConfiguration / companyinformation XML
 *     reference (Oracle Help — SuiteCloud Development Framework XML
 *     Reference).
 */

export interface CompanyInformationInput {
  /** Engagement / client name — drives <legalname>. */
  clientName: string;
  /** ns.foundation.primaryCountry (ISO alpha-2). Drives <country>. */
  primaryCountry: string;
  /** ns.foundation.fiscalYearStart in MM-DD form (e.g., "01-01"). */
  fiscalYearStart: string;
  /** ISO 4217 base currency code. The orchestrator passes the FIRST
   *  parsed subsidiary's currency (the root tenant subsidiary). */
  baseCurrency: string;
}

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function generateCompanyInformation(input: CompanyInformationInput): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by ERPLaunch Company Information Generator from
  ns.foundation.* wizard answers + the engagement client name.
  Review before deploy: confirm legal name + country + base currency
  match what's on the customer's filing statements (especially in
  multi-jurisdiction OneWorld engagements).
-->
<companyinformation>
  <legalname>${xmlEscape(input.clientName)}</legalname>
  <country>${xmlEscape(input.primaryCountry)}</country>
  <basecurrency>${xmlEscape(input.baseCurrency)}</basecurrency>
  <fiscalyearstart>${xmlEscape(input.fiscalYearStart)}</fiscalyearstart>
  <employerid></employerid>
</companyinformation>
`;
}
