/**
 * SDF Customlist generator (Pack B — Custom Field Full Coverage).
 *
 * SELECT-classified custom fields need a customlist to reference. This
 * generator emits a placeholder customlist per such field so the
 * SELECT field deploys cleanly (audit Fix #4 contract — every
 * customlist must contain at least one customvalue, otherwise SDF
 * deploy fails).
 *
 * Why placeholder values:
 *   - We don't have the actual list values from the wizard yet (the
 *     answer just gives us the field label, not its picklist
 *     contents). Future packs may collect them.
 *   - A single placeholder value with isinactive=T satisfies the
 *     deploy-time validation while clearly signalling "fill me in" to
 *     the consultant. They un-inactivate, add real values, redeploy.
 *
 * Audit Fix #4 closeout (commit 307901c) requires:
 *   - Root <customlist> (not legacy <customrecord> — distinct schema)
 *   - <label> (not legacy <name>)
 *   - At least one <customvalue> under <customvalues>
 *
 * Sources:
 *   - NetSuite SDF XML Reference — customlist schema (Oracle docs).
 *   - audit Fix #4 closeout (commit 307901c) — label-not-name +
 *     non-empty customvalues invariants.
 *   - sdfValidator.ts validateCustomList enforces the contract this
 *     generator emits.
 */

export interface CustomListInput {
  /** scriptid for the list — must start with `customlist_` and be
   *  unique across the bundle. Caller is responsible for uniqueness. */
  listScriptid: string;
  /** Human label shown to users in the picklist UI. Drives the
   *  <label> tag and the <description> prose. */
  label: string;
  /** Optional explicit set of placeholder values. When omitted, a
   *  single inactive placeholder is emitted (the minimum to satisfy
   *  audit Fix #4). When provided, each value is emitted with
   *  isinactive=T so the consultant can un-inactivate after review. */
  placeholderValues?: string[];
}

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function buildCustomvaluesXml(values: string[]): string {
  return values
    .map((value, index) => {
      const escaped = xmlEscape(value);
      return `    <customvalue scriptid="val_placeholder_${index + 1}">
      <value>${escaped}</value>
      <isinactive>T</isinactive>
    </customvalue>`;
    })
    .join('\n');
}

/**
 * Emit one customlist XML.
 *
 * Output bundle path is the caller's concern — this generator just
 * returns the XML body. The orchestrator pairs it with
 * `Objects/${listScriptid}.xml`.
 */
export function generateSdfCustomList(input: CustomListInput): string {
  const escapedLabel = xmlEscape(input.label);
  const values =
    input.placeholderValues && input.placeholderValues.length > 0
      ? input.placeholderValues
      : ['Placeholder value 1'];
  const customvalues = buildCustomvaluesXml(values);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by ERPLaunch from wizard answer that triggered SELECT inference.
  Source list: ${input.listScriptid}
  Empty value list — consultant must add values before deploy.
-->
<customlist scriptid="${input.listScriptid}">
  <label>${escapedLabel}</label>
  <description>Picklist for ${escapedLabel}. Add values in NetSuite UI before deploy.</description>
  <ismatrixoption>F</ismatrixoption>
  <isordered>T</isordered>
  <customvalues>
${customvalues}
  </customvalues>
</customlist>
`;
}
