/**
 * SDF Entry Form generator (Pack H — Custom Forms).
 *
 * Mirror of sdfTransactionFormGenerator for entity-side records:
 * Customer / Vendor / Item / Employee. Same shape (one form per
 * parent that has Pack B custom fields, fields embedded under a
 * "Custom Fields" fieldgroup), different XML root (<entryform> vs.
 * <transactionform>) and different recordtype enum.
 *
 * Why a separate generator vs. parameterising the transaction-form
 * one? NetSuite SDF distinguishes form types by root element +
 * recordtype enum. Keeping the two emitters independent means each
 * stays small + easy to read; future divergence (e.g. entity forms
 * sometimes need quicklist or tabs blocks that transaction forms
 * don't) is a one-file change rather than a parameterised mess.
 *
 * Sources:
 *   - NetSuite SDF entryform XML reference (Oracle docs).
 *   - NetSuite Custom Forms best practice (Oracle Help — preferred
 *     forms, recordtype enum, fieldgroup layout).
 */

import {
  generateSdfCustomFields,
  type EmittedField,
} from './sdfCustomFieldsGenerator.js';
import { clientSlug } from './sdfTransactionFormGenerator.js';

/**
 * Maps human parent name → NetSuite recordtype enum value used inside
 * <recordtype>...</recordtype>. Entity-side only — Sales Order /
 * Purchase Order / Invoice / Bill / JE / Item Receipt belong on
 * transaction forms, handled by sdfTransactionFormGenerator.
 */
const ENTRY_PARENT_RECORDTYPE: Record<string, string> = {
  Customer: 'CUSTOMER',
  Vendor: 'VENDOR',
  Item: 'ITEM',
  Employee: 'EMPLOYEE',
};

const ENTRY_PARENT_DISPLAY: Record<string, string> = {
  Customer: 'Customer',
  Vendor: 'Vendor',
  Item: 'Item',
  Employee: 'Employee',
};

export interface EntryFormInput {
  /** Raw TEXTAREA from ns.design.customFieldsScope. */
  customFieldsScope: string | null | undefined;
  /** Client / engagement name — drives scriptid client_slug + form name. */
  clientName: string;
}

export interface EntryFormOutput {
  /** Map<bundle-relative path, XML body>. Keys take the form
   *  Objects/custform_<client_slug>_<recordtype_lower>.xml. */
  files: Record<string, string>;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function groupEntryFieldsByParent(
  emitted: EmittedField[],
): Map<string, EmittedField[]> {
  const grouped = new Map<string, EmittedField[]>();
  for (const f of emitted) {
    if (!(f.parent in ENTRY_PARENT_RECORDTYPE)) continue;
    const list = grouped.get(f.parent) ?? [];
    list.push(f);
    grouped.set(f.parent, list);
  }
  return grouped;
}

function buildEntryFormXml(args: {
  scriptid: string;
  formName: string;
  recordtype: string;
  fields: EmittedField[];
}): string {
  const fieldRows = args.fields
    .map(
      (f) => `        <field>
          <id>${f.scriptid}</id>
          <visible>T</visible>
          <mandatory>F</mandatory>
        </field>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by ERPLaunch Entry Form Generator.
  Source: Pack B custom fields parsed from ns.design.customFieldsScope.
  Form embeds custom fields as a starter layout. Adjust in NetSuite UI before deploy.
-->
<entryform scriptid="${args.scriptid}">
  <name>${xmlEscape(args.formName)}</name>
  <recordtype>${args.recordtype}</recordtype>
  <preferred>T</preferred>
  <storedwithrecord>F</storedwithrecord>
  <mainfields>
    <fieldgroup>
      <id>customfields</id>
      <label>Custom Fields</label>
      <visible>T</visible>
      <fields>
${fieldRows}
      </fields>
    </fieldgroup>
  </mainfields>
</entryform>
`;
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Emit the full set of entry-form XMLs for an engagement.
 *
 * Empty / whitespace-only / missing customFieldsScope → empty file
 * map (no errors). Forms are only emitted for entity parents that
 * have at least one custom field. The PO-approval auto-add field
 * lives on Purchase Order, which is a TRANSACTION parent — it never
 * shows up in this generator's output.
 */
export function generateEntryForms(input: EntryFormInput): EntryFormOutput {
  // Re-use Pack B's parser. We don't pass includePoApprovalRequiredField
  // here because the auto-add is a Purchase Order field, which doesn't
  // route to entry forms.
  const fieldsResult = generateSdfCustomFields({
    customFieldsScopeAnswer: input.customFieldsScope,
  });

  const grouped = groupEntryFieldsByParent(fieldsResult.emitted);
  if (grouped.size === 0) return { files: {} };

  const slug = clientSlug(input.clientName);
  const files: Record<string, string> = {};

  for (const [parent, fields] of grouped.entries()) {
    const recordtype = ENTRY_PARENT_RECORDTYPE[parent];
    const display = ENTRY_PARENT_DISPLAY[parent] ?? parent;
    const scriptid = `custform_${slug}_${recordtype.toLowerCase()}`;
    const formName = `${input.clientName} ${display} Form`;
    const filename = `Objects/${scriptid}.xml`;
    files[filename] = buildEntryFormXml({
      scriptid,
      formName,
      recordtype,
      fields,
    });
  }

  return { files };
}
