/**
 * SDF General Preferences generator (Pack C — Roles + Permissions
 * + Account Preferences).
 *
 * Emits a single Oracle SDF `generalpreferences.xml` to the
 * SDF/AccountConfiguration/ folder. Captures account-level
 * authentication, audit, and UI policy preferences from foundation
 * + design wizard answers.
 *
 * Default audit retention is 84 months (7 years) — consistent with
 * the Pack 3 SD default (ns.design.auditLogRetentionMonths). The
 * consultant overrides via the wizard answer when the engagement
 * has a stricter (e.g. 120-month / 10-year) policy — pharma + life
 * sciences typically run 120 months for FDA / GxP compliance.
 *
 * Sources:
 *   - NetSuite SDF AccountConfiguration / generalpreferences XML
 *     reference (Oracle Help — SuiteCloud Development Framework XML
 *     Reference).
 */

export interface GeneralPreferencesInput {
  /** ns.foundation.ssoInScope — drives enablesinglesignon. */
  ssoInScope?: boolean;
  /** ns.foundation.customRolesRequired — drives enablecustomroles. */
  customRolesRequired?: boolean;
  /** ns.design.auditLogRetentionMonths. Defaults to 84 when unset. */
  auditLogRetentionMonths?: number;
}

export function generateGeneralPreferences(input: GeneralPreferencesInput): string {
  const tFlag = (b: boolean | undefined): 'T' | 'F' => (b === true ? 'T' : 'F');
  const retention =
    typeof input.auditLogRetentionMonths === 'number' &&
    Number.isFinite(input.auditLogRetentionMonths) &&
    input.auditLogRetentionMonths > 0
      ? input.auditLogRetentionMonths
      : 84;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by ERPLaunch General Preferences Generator from
  ns.foundation.* + ns.design.* wizard answers.
  Drives account-level authentication + audit + UI defaults. Review
  before deploy: SSO IDP configuration is account-admin work that
  happens AFTER this preference flips on.
-->
<generalpreferences>
  <enablesinglesignon>${tFlag(input.ssoInScope)}</enablesinglesignon>
  <enableauditrail>T</enableauditrail>
  <auditrailretentionmonths>${retention}</auditrailretentionmonths>
  <enablecustomroles>${tFlag(input.customRolesRequired)}</enablecustomroles>
  <emailcase>SENTENCE</emailcase>
  <datedefault>YYYY-MM-DD</datedefault>
</generalpreferences>
`;
}
