/**
 * One-shot driver: generate the full NetSuite demo bundle for a
 * canonical OneWorld engagement. Mirrors generate-odoo-demo-bundle.ts.
 *
 * Calls the generators directly with the same data shape that
 * generation.ts builds for adaptorId='netsuite', then writes the output
 * into NSIX/NETSUITE_DEMO_BUNDLE/<ISO>/Documentation/.
 *
 * No DB, no queue, no API — just the pure generator functions exercised
 * with a representative payload. The bundle is the design-partner /
 * pitch artefact and is intentionally NOT committed to git.
 *
 * Run from apps/api:
 *   pnpm --filter @ofoq/api exec tsx scripts/generate-netsuite-demo-bundle.ts
 */
import path from 'node:path';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { generateBRD, generateBRDHtml, type AdaptorContext } from '../src/services/generators/brdGenerator.js';
import { generateRiskRegister } from '../src/services/generators/riskGenerator.js';
import { generateUATPlan, generateUATPlanHtml } from '../src/services/generators/uatGenerator.js';
import { generateSolutionDoc, generateSolutionDocHtml } from '../src/services/generators/solutionDocGenerator.js';
import { generateTrainingManual, generateTrainingManualHtml } from '../src/services/generators/trainingManualGenerator.js';
import { generateImplementationPlanHtml } from '../src/services/generators/planGenerator.js';
import netsuiteAdaptor from '@ofoq/adaptor-netsuite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// apps/api/scripts → repo root → NSIX/ → NETSUITE_DEMO_BUNDLE/
const NSIX_ROOT = path.resolve(__dirname, '..', '..', '..', '..');

// ── Adaptor context — same shape generation.ts builds for adaptorId='netsuite' ──
const adaptor: AdaptorContext = {
  id: 'netsuite',
  name: 'NetSuite',
  editionLabel: 'NetSuite OneWorld',
  consultantQualifier: 'NetSuite',
  nextStepLanguage:
    'the NetSuite build phase using the SDF deployment package generated by ERPLaunch',
  flows: netsuiteAdaptor.schema.flows.map((f) => ({
    id: f.id,
    label: f.label,
    description: f.description,
    sections: f.sections.map((s) => ({
      id: s.id,
      label: s.label,
      order: s.order,
      questions: s.questions.map((q) => ({
        id: q.id,
        label: q.label,
        inputType: q.inputType,
        options: q.options,
      })),
    })),
  })),
};

// ── Demo data — canonical OneWorld engagement (Atlas Industries Group) ──────
const clientName = 'Atlas Industries Group';
const license = {
  edition: 'ONEWORLD',
  modules: [
    'ONEWORLD',
    'ADVANCED_REVENUE',
    'ADVANCED_INVENTORY',
    'MULTI_BOOK',
    'MANUFACTURING',
    'WORK_ORDERS',
    'WIP_ROUTINGS',
  ],
};

const answers: Record<string, unknown> = {
  // NS Pack 1 — Foundation & Account Type
  'ns.foundation.edition': 'ONEWORLD',
  'ns.foundation.suiteSuccessBundle': 'US',
  'ns.foundation.suiteCloudPlus': true,
  'ns.foundation.sandboxAccount': 'BOTH',
  'ns.foundation.fullUserCount': 85,
  'ns.foundation.essUserCount': 240,
  'ns.foundation.customRolesRequired': true,
  'ns.foundation.ssoInScope': true,
  'ns.foundation.primaryCountry': 'US',
  'ns.foundation.fiscalYearStart': '01-01',
  'ns.foundation.multiBookAccounting': true,
  'ns.foundation.advancedRevRecInScope': true,
  'ns.foundation.subsidiaryCount': 4,
  'ns.foundation.subsidiaryList':
    'Atlas Industries Group Inc., US, USD, parent\n' +
    'Atlas Manufacturing UK Ltd., GB, GBP, Atlas Industries Group Inc.\n' +
    'Atlas Trading Pty., AU, AUD, Atlas Industries Group Inc.\n' +
    'Atlas Services GmbH, DE, EUR, Atlas Industries Group Inc.',
  'ns.foundation.multiCurrencyInScope': true,
  'ns.foundation.eliminationEntity': 'Atlas Group Eliminations',
};

const comments = [
  {
    sectionKey: 'edition',
    text: 'OneWorld confirmed; all 4 subsidiaries on a single tenant. SuiteCloud Plus required for Concur/Workday integrations + heavy SuiteScript footprint. Both Full-copy and Release Preview sandboxes — auditor expects sandbox-validated change control.',
  },
  {
    sectionKey: 'subsidiaries',
    text: 'Elimination entity created upfront so Phase 4 build sees the full tree. Multi-currency live from day one (USD base, GBP/AUD/EUR transactional).',
  },
];
const images: unknown[] = [];
const aiAdvice: unknown[] = [];
const conflicts: unknown[] = [];

// ── Output folder ───────────────────────────────────────────────────────────
const ts = new Date().toISOString().replace(/[:.]/g, '-');
const outRoot = path.join(NSIX_ROOT, 'NETSUITE_DEMO_BUNDLE', ts);
const docDir = path.join(outRoot, 'Documentation');
await fs.mkdir(docDir, { recursive: true });

// ── Generate ────────────────────────────────────────────────────────────────
const brdData = { clientName, adaptor, license, answers, comments, images, aiAdvice };
const sddData = { clientName, adaptor, license, answers, conflicts: conflicts as never[], comments, images, aiAdvice };
const trainingData = { clientName, adaptor, answers, comments, images, aiAdvice };
const uatData = { clientName, adaptor, answers, comments, images, aiAdvice };
const planData = { clientName, adaptor, license, answers, conflicts: conflicts as never[] };
const riskData = { clientName, conflicts: [], warnings: [] };

const writes: Array<[string, string]> = [
  ['BRD.md', generateBRD(brdData)],
  ['BRD.html', generateBRDHtml(brdData)],
  ['Risk_Register.md', generateRiskRegister(riskData)],
  ['UAT_Plan.md', generateUATPlan(uatData)],
  ['UAT_Plan.html', generateUATPlanHtml(uatData)],
  ['Solution_Design.md', generateSolutionDoc(sddData)],
  ['Solution_Design.html', generateSolutionDocHtml(sddData)],
  ['Training_Manual.md', generateTrainingManual(trainingData)],
  ['Training_Manual.html', generateTrainingManualHtml(trainingData)],
  ['Implementation_Plan.html', generateImplementationPlanHtml(planData)],
];

for (const [filename, content] of writes) {
  await fs.writeFile(path.join(docDir, filename), content, 'utf8');
  process.stdout.write(`  ✓ ${filename}\n`);
}

// ── Anti-bleed verification ─────────────────────────────────────────────────
// Confirm NetSuite-specific terminology IS present (this is the inverse of
// the Odoo banlist — for NetSuite we expect to see it). Catches any future
// regression where a generator accidentally renders Odoo prose for a
// NetSuite engagement.
const REQUIRED = ['NetSuite'];
let missingTerms = 0;
const brdContent = writes.find(([f]) => f === 'BRD.md')?.[1] ?? '';
for (const term of REQUIRED) {
  if (!brdContent.includes(term)) {
    // eslint-disable-next-line no-console
    console.error(`  ✗ MISSING: BRD.md does not contain "${term}"`);
    missingTerms++;
  }
}

// eslint-disable-next-line no-console
console.log('');
// eslint-disable-next-line no-console
console.log(`  Bundle: ${outRoot}`);
// eslint-disable-next-line no-console
console.log(`  Files:  ${writes.length}`);
if (missingTerms === 0) {
  // eslint-disable-next-line no-console
  console.log(`  Sanity: ✓ NetSuite terminology present in BRD`);
} else {
  // eslint-disable-next-line no-console
  console.log(`  Sanity: ✗ ${missingTerms} required term(s) missing`);
  process.exit(1);
}
