/**
 * One-shot driver: generate the full Odoo demo bundle for the seeded
 * Sahel Logistics Ltd. engagement. Calls the generators directly with
 * the same data shape that seed-odoo.ts persists, then writes the
 * output into NSIX/ODOO_DEMO_BUNDLE/<ISO>/Documentation/.
 *
 * No DB, no queue, no API — just the pure generator functions exercised
 * with the demo-engagement payload. The bundle is the design-partner
 * artefact and is intentionally NOT committed to git.
 *
 * Run from apps/api:
 *   pnpm --filter @ofoq/api exec tsx scripts/generate-odoo-demo-bundle.ts
 */
import path from 'node:path';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { generateBRD, generateBRDHtml, type AdaptorContext } from '../src/services/generators/brdGenerator.js';
import { generateRiskRegister } from '../src/services/generators/riskGenerator.js';
import { generateUATPlan, generateUATPlanHtml } from '../src/services/generators/uatGenerator.js';
import { generateSolutionDoc, generateSolutionDocHtml } from '../src/services/generators/solutionDocGenerator.js';
import { generateTrainingManual, generateTrainingManualHtml } from '../src/services/generators/trainingManualGenerator.js';
import { generateImplementationPlanHtml } from '../src/services/generators/planGenerator.js';
import { generateOdooConfigurationPlan, generateOdooConfigurationPlanHtml } from '../src/services/generators/odooConfigurationPlanGenerator.js';
import odooAdaptor from '@ofoq/adaptor-odoo';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// apps/api/scripts → repo root → NSIX/ → ODOO_DEMO_BUNDLE/
const NSIX_ROOT = path.resolve(__dirname, '..', '..', '..', '..');

// ── Adaptor context — same shape generation.ts builds for adaptorId='odoo' ──
// Flows pulled from the live adaptor schema so the BRD's Workstream
// Requirements section actually iterates Foundation / Tax / R2R / etc.
// instead of the old hardcoded NetSuite-only flow list.
const adaptor: AdaptorContext = {
  id: 'odoo',
  name: 'Odoo',
  editionLabel: 'Enterprise',
  consultantQualifier: 'Odoo',
  nextStepLanguage:
    'the Odoo configuration phase using the module install plan and localization package generated by ERPLaunch',
  flows: odooAdaptor.schema.flows.map((f) => ({
    id: f.id,
    label: f.label,
    description: f.description,
    sections: f.sections.map((s) => ({
      id: s.id,
      label: s.label,
      order: s.order,
      questions: s.questions.map((q) => ({
        id: q.id,
        label: q.label,
        inputType: q.inputType,
        options: q.options,
      })),
    })),
  })),
};

// ── Demo data — mirror of seed-odoo.ts's Sahel Logistics Ltd. record ────────
const clientName = 'Sahel Logistics Ltd.';
const license = {
  edition: 'ENTERPRISE',
  modules: [
    'BASE_ACCOUNTING', 'BASE_SALES', 'BASE_PURCHASE', 'BASE_INVENTORY',
    'ENTERPRISE_ACCOUNTING', 'ENTERPRISE_STUDIO', 'ENTERPRISE_DOCUMENTS',
    'MRP', 'QUALITY', 'CRM', 'PROJECT', 'TIMESHEETS',
  ],
};
const answers: Record<string, unknown> = {
  // Pack 1 — Foundation
  'odoo.foundation.deploymentMode': 'ODOOSH',
  'odoo.foundation.edition': 'ENTERPRISE',
  'odoo.foundation.usersInternalY1': 35,
  'odoo.foundation.usersInternalY3': 60,
  'odoo.foundation.portalUsers': true,
  'odoo.foundation.primaryCountry': 'AE',
  'odoo.foundation.otherCountries': 'EG\nSA',
  'odoo.foundation.reportingLanguage': 'en',
  'odoo.foundation.uiLanguages': 'ar\nfr',
  'odoo.foundation.fiscalYearStart': '01-01',
  'odoo.foundation.multiCompany': true,
  'odoo.foundation.entityList': 'Sahel Logistics Holding, AE, AED\nSahel Freight Forwarding, AE, AED',
  'odoo.foundation.intercompanyAuto': true,
  'odoo.foundation.multiCurrency': true,
  'odoo.foundation.reportingCurrency': 'USD',

  // Pack 2 — Tax Engine
  'odoo.tax.salesPriceMode': 'EXCLUDED',
  'odoo.tax.purchasePriceMode': 'EXCLUDED',
  'odoo.tax.defaultSalesTax': 'VAT 5%',
  'odoo.tax.defaultPurchaseTax': 'VAT 5%',
  'odoo.tax.hasExemptCustomers': true,
  'odoo.tax.exemptCategories': 'Free zone clients\nGCC export',
  'odoo.tax.hasReducedRates': false,
  'odoo.tax.reducedRateCategories': '',
  'odoo.tax.reverseCharge': true,
  'odoo.tax.withholding': false,
  'odoo.tax.regionalVariation': false,
  'odoo.tax.fiscalPositions': true,
  'odoo.tax.fiscalPositionList': 'Domestic\nExport — GCC\nFree Zone\nReverse-charge import',
  'odoo.tax.einvoicingRequired': 'NO',
  'odoo.tax.einvoicingSystem': '',
  'odoo.tax.taxFilingPeriodicity': 'QUARTERLY',

  // Pack 3 — Localization & Compliance
  'odoo.localization.coaTemplate': 'l10n_ae (UAE Federal Tax Authority chart of accounts)',
  'odoo.localization.statutoryReports': 'GCC VAT return\nIFRS financial statements\nUAE Economic Substance Regulations report',
  'odoo.localization.languagePackInstall': true,
  'odoo.localization.einvoicingProvider': 'UAE FTA (rolling out)',
  'odoo.localization.einvoicingPhase': 'Phase 1',
  'odoo.localization.einvoicingPilotDone': 'IN_PROGRESS',
  'odoo.localization.einvoicingDigitalCert': 'IN_PROGRESS',
  'odoo.localization.payrollInScope': true,
  'odoo.localization.payrollFrequency': 'MONTHLY',
  'odoo.localization.payrollEndOfService': 'UAE end-of-service gratuity per Article 51 of UAE Labour Law (Federal Decree-Law No. 33 of 2021)',
  'odoo.localization.dataResidencyRequired': true,
  'odoo.localization.dataResidencyJurisdiction': 'UAE / GCC',
  'odoo.localization.gdprApplicable': true,

  // Legacy R2R / P2P / O2C / MRP / Returns answers (preserved)
  'odoo.company.multiCompany': true,
  'odoo.company.currency': 'AED',
  'odoo.company.fiscalYearStart': '01-01',
  'odoo.coa.template': 'LOCALIZATION',
  'odoo.coa.analyticAccounting': true,
  'odoo.purchase.approvalTiers': 'DOUBLE',
  'odoo.purchase.threeWayMatch': true,
  'odoo.sales.quoteTemplate': true,
  'odoo.sales.priceListStrategy': 'CUSTOMER_TIER',
  'odoo.invoicing.policy': 'DELIVERED',
  'odoo.mrp.enabled': true,
  'odoo.mrp.workCenters': true,
  'odoo.mrp.quality': true,
  'odoo.returns.policy': 'AUTO_REFUND',
};
const comments = [
  { sectionKey: 'license', text: 'Enterprise edition confirmed; Studio + Documents required for approval matrix + contract storage. MRP + Quality modules for the two production lines.' },
  { sectionKey: 'r2r.company', text: 'Two legal entities: Sahel Logistics Holding (parent) and Sahel Freight Forwarding (sub). Multi-company enabled to share partners and pricelists. Fiscal year Jan–Dec for both.' },
  { sectionKey: 'o2c.sales', text: 'Pricelist tiers: Wholesale, Retail, Contract. Customers tagged at onboarding. Automated renewal reminders for contract-tier customers go via Studio flow.' },
];
const images: unknown[] = [];
const aiAdvice: unknown[] = [];
const conflicts: unknown[] = [];

// ── Output folder ───────────────────────────────────────────────────────────
const ts = new Date().toISOString().replace(/[:.]/g, '-');
const outRoot = path.join(NSIX_ROOT, 'ODOO_DEMO_BUNDLE', ts);
const docDir = path.join(outRoot, 'Documentation');
await fs.mkdir(docDir, { recursive: true });

// ── Generate ────────────────────────────────────────────────────────────────
const brdData = { clientName, adaptor, license, answers, comments, images, aiAdvice };
const sddData = { clientName, adaptor, license, answers, conflicts: conflicts as never[], comments, images, aiAdvice };
const trainingData = { clientName, adaptor, answers, comments, images, aiAdvice };
const uatData = { clientName, adaptor, answers, comments, images, aiAdvice };
const planData = { clientName, adaptor, license, answers, conflicts: conflicts as never[] };
const configPlanData = { clientName, adaptor, license, answers, comments, images, aiAdvice };
const riskData = { clientName, conflicts: [], warnings: [] };

const writes: Array<[string, string]> = [
  ['BRD.md', generateBRD(brdData)],
  ['BRD.html', generateBRDHtml(brdData)],
  ['Risk_Register.md', generateRiskRegister(riskData)],
  ['UAT_Plan.md', generateUATPlan(uatData)],
  ['UAT_Plan.html', generateUATPlanHtml(uatData)],
  ['Solution_Design.md', generateSolutionDoc(sddData)],
  ['Solution_Design.html', generateSolutionDocHtml(sddData)],
  ['Training_Manual.md', generateTrainingManual(trainingData)],
  ['Training_Manual.html', generateTrainingManualHtml(trainingData)],
  ['Implementation_Plan.html', generateImplementationPlanHtml(planData)],
  ['Configuration_Plan.md', generateOdooConfigurationPlan(configPlanData)],
  ['Configuration_Plan.html', generateOdooConfigurationPlanHtml(configPlanData)],
];

for (const [filename, content] of writes) {
  await fs.writeFile(path.join(docDir, filename), content, 'utf8');
  process.stdout.write(`  ✓ ${filename}\n`);
}

// ── Banlist verification ────────────────────────────────────────────────────
const BANNED = ['NetSuite', 'SuiteScript', 'SDF', 'subsidiary', 'OneWorld'];
let banlistViolations = 0;
for (const [filename, content] of writes) {
  for (const term of BANNED) {
    if (content.includes(term)) {
      // eslint-disable-next-line no-console
      console.error(`  ✗ BANLIST VIOLATION: ${filename} contains "${term}"`);
      banlistViolations++;
    }
  }
}

// eslint-disable-next-line no-console
console.log('');
// eslint-disable-next-line no-console
console.log(`  Bundle: ${outRoot}`);
// eslint-disable-next-line no-console
console.log(`  Files:  ${writes.length}`);
if (banlistViolations === 0) {
  // eslint-disable-next-line no-console
  console.log(`  Banlist: ✓ none of NetSuite / SuiteScript / SDF / subsidiary / OneWorld appears anywhere`);
} else {
  // eslint-disable-next-line no-console
  console.log(`  Banlist: ✗ ${banlistViolations} violation(s)`);
  process.exit(1);
}
