/**
 * Phase 51.4 hotfix — inline export-template assets at build time.
 *
 * Reads the textured Xelerate backgrounds + Playfair/Lora TTFs from
 * `apps/api/src/services/exporters/templates/_assets/{bg-*.png,fonts/*.ttf}`
 * and writes a generated TypeScript module
 * `apps/api/src/services/exporters/templates/_assets/assets.generated.ts`
 * containing base64 string consts.
 *
 * Why this exists:
 *   - The Phase 51.4 first cut used `readFileSync(__dirname, 'bg-*.png')`
 *     at runtime. That works under `tsx src/server.ts` (the current
 *     prod entry point) when the binary files happen to be alongside
 *     the .ts module. It is fragile under any future build path that
 *     compiles `.ts` only and drops the binaries (e.g. tsc → dist/,
 *     esbuild bundle, Vercel build cache).
 *   - The blank-PDF prod symptom was the canary for that fragility.
 *     Inlining moves the asset payload from "happens to be on disk
 *     at runtime" to "compiled into the module graph at build time"
 *     — fails loudly if the bake step never ran, never silently.
 *
 * The generated file is committed so dev environments don't need to
 * remember to run the script, and Dockerfile re-runs it during the
 * image build so a stale generated file can't ship to prod.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const ASSETS_DIR = join(__dirname, '..', 'src', 'services', 'exporters', 'templates', '_assets');
const FONTS_DIR = join(ASSETS_DIR, 'fonts');
const OUTPUT_FILE = join(ASSETS_DIR, 'assets.generated.ts');

interface AssetSpec {
  /** TS const name in the generated module. */
  name: string;
  /** Absolute path to the source file. */
  path: string;
  /** Expected leading base64 bytes (for sanity-checking the bake). */
  magic: string;
  /** Human-readable label for the failure message. */
  label: string;
}

const ASSETS: ReadonlyArray<AssetSpec> = [
  {
    name: 'BG_GREEN_B64',
    path: join(ASSETS_DIR, 'bg-green.png'),
    magic: 'iVBOR',
    label: 'Green textured cover background',
  },
  {
    name: 'BG_NAVY_B64',
    path: join(ASSETS_DIR, 'bg-navy.png'),
    magic: 'iVBOR',
    label: 'Navy textured slide background',
  },
  {
    name: 'FONT_PLAYFAIR_B64',
    path: join(FONTS_DIR, 'PlayfairDisplay-Bold.ttf'),
    magic: 'AAEAAA',
    label: 'Playfair Display Bold (TTF)',
  },
  {
    name: 'FONT_LORA_REGULAR_B64',
    path: join(FONTS_DIR, 'Lora-Regular.ttf'),
    magic: 'AAEAAA',
    label: 'Lora Regular (TTF)',
  },
  {
    name: 'FONT_LORA_SEMIBOLD_B64',
    path: join(FONTS_DIR, 'Lora-SemiBold.ttf'),
    magic: 'AAEAAA',
    label: 'Lora SemiBold (TTF)',
  },
];

function bakeAsset(spec: AssetSpec): string {
  const buf = readFileSync(spec.path);
  if (buf.byteLength === 0) {
    throw new Error(`[inline-export-assets] ${spec.label} at ${spec.path} is empty`);
  }
  const b64 = buf.toString('base64');
  if (!b64.startsWith(spec.magic)) {
    throw new Error(
      `[inline-export-assets] ${spec.label} at ${spec.path} did not start with expected magic ${spec.magic} — got ${b64.slice(0, 8)}`,
    );
  }
  return b64;
}

function generateModule(entries: Array<{ spec: AssetSpec; b64: string }>): string {
  const header = [
    '/**',
    ' * Auto-generated by `apps/api/scripts/inline-export-assets.ts`.',
    ' * DO NOT EDIT BY HAND — regenerate via `pnpm -F @ofoq/api build:assets`.',
    ' *',
    ` * Generated at: ${new Date().toISOString()}`,
    ' */',
    '',
    '/* eslint-disable */',
    '',
  ].join('\n');

  const constLines = entries
    .map(({ spec, b64 }) => `export const ${spec.name}: string = '${b64}';`)
    .join('\n\n');

  return `${header}${constLines}\n`;
}

function main(): void {
  const entries = ASSETS.map((spec) => ({ spec, b64: bakeAsset(spec) }));
  const source = generateModule(entries);
  writeFileSync(OUTPUT_FILE, source, 'utf8');

  const sizes = entries
    .map(({ spec, b64 }) => `${spec.name}=${(b64.length / 1024).toFixed(0)}KB`)
    .join(' · ');
  // eslint-disable-next-line no-console
  console.log(`[inline-export-assets] wrote ${OUTPUT_FILE}`);
  // eslint-disable-next-line no-console
  console.log(`[inline-export-assets] ${sizes}`);
}

main();
